### DISCUSSION TITLE
How to match specific modifiers of a method?

### DISCUSSION THREAD

**Discussion by dotjpg3141** [ast-grep/ast-grep#1058] [Q&A] [answered]
How to match specific modifiers of a method? In this example I want to match all public methods.

C#
```csharp
class Bar {
    public static async void Fii() {
    }

    void Foo() {
    }
}
````

Rule:
```yaml
language: csharp
rule:
  kind: method_declaration
  has:
    field: modifier
    regex: ^public$
```

[Playground](https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6ImNzaGFycCIsInF1ZXJ5IjoiY29uc29sZS5sb2coJE1BVENIKSIsInJld3JpdGUiOiJsb2dnZXIubG9nKCRNQVRDSCkiLCJjb25maWciOiJsYW5ndWFnZTogY3NoYXJwXG5ydWxlOlxuICBraW5kOiBtZXRob2RfZGVjbGFyYXRpb25cbiAgaGFzOlxuICAgIGZpZWxkOiBtb2RpZmllclxuICAgIHJlZ2V4OiBecHVibGljJFxuICAgICIsInNvdXJjZSI6ImNsYXNzIEJhciB7XG4gICAgcHVibGljIHN0YXRpYyBhc3luYyB2b2lkIEZpaSgpIHtcbiAgICB9XG5cbiAgICB2b2lkIEZvbygpIHtcbiAgICB9XG59In0=)

**Comment by HerringtonDarkholme** [comment, marked as answer]
field and kind are different.

https://ast-grep.github.io/advanced/core-concepts.html#kind-vs-field

```yaml
language: csharp
rule:
  kind: method_declaration
  has:
    kind: modifier
    regex: ^public$
```

https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6ImNzaGFycCIsInF1ZXJ5IjoiY29uc29sZS5sb2coJE1BVENIKSIsInJld3JpdGUiOiJsb2dnZXIubG9nKCRNQVRDSCkiLCJjb25maWciOiJsYW5ndWFnZTogY3NoYXJwXG5ydWxlOlxuICBraW5kOiBtZXRob2RfZGVjbGFyYXRpb25cbiAgaGFzOlxuICAgIGtpbmQ6IG1vZGlmaWVyXG4gICAgcmVnZXg6IF5wdWJsaWMkXG4gICAgIiwic291cmNlIjoiY2xhc3MgQmFyIHtcbiAgICBwdWJsaWMgc3RhdGljIGFzeW5jIHZvaWQgRmlpKCkge1xuICAgIH1cblxuICAgIHZvaWQgRm9vKCkge1xuICAgIH1cbn0ifQ==
