### DISCUSSION TITLE
String interpolation ?

### DISCUSSION THREAD

**Discussion by fcbry** [ast-grep/ast-grep#1063] [Q&A] [answered]
Hi, 
In bash if I want to interpolate a variable into a string I can do (contrived example):
```bash
$V=" hello "
echo "I say${V},you say goodbye."
I say hello, you say goodbye.
```

Now, I want to do a fix, this works fine (Elixir): 

```
rule:
  any:
    - pattern: |
        defmodule $M do 
          IO.puts($A)
        end
fix: |
  defmodule $M do 
    def msg($A) do 
      IO.puts(:stdout,$A)
    end 
  end
```

But say, I want to rename the Elixir module (suffix it with "ConcreteFactoryImpl")(lets pretend we're Java devs: 

Now `$M` wont match. I could append a quoted string but that wouldn't produce a valid module name.

Ideally, unless I'm being silly, variables could be expressed in a `${M}` form so that they could be expressed in strings, like so:

```
rule:
  any:
    - pattern: |
        defmodule $M do 
          IO.puts($A)
        end
fix: |
  defmodule ${M}ConcreteFactoryImpl do 
    def msg($A) do 
      IO.puts(:stdout,$A)
    end 
  end
```
Is there a better way to do this?

**Comment by fcbry** [comment]
I seem to have gotten around this by splicing in `$_` (which evaluates to nothing in this case) to separate the variable `$M` and the text that follows.

```
rule:
  any:
    - pattern: |
        defmodule $M do 
          IO.puts($A)
        end
fix: |
  defmodule $M$_ConcreteFactoryImpl do 
    def msg($A) do 
      IO.puts(:stdout,$A)
    end 
  end
```

![image](https://github.com/ast-grep/ast-grep/assets/152185182/ddd0de06-eef3-4407-8d9c-751c3d7fd427)

Woops, wrong, it's still eating the letter 'C'

**Comment by HerringtonDarkholme** [comment, marked as answer]
This can be done via transform operation. 
The trick here is `$NEW_MOD` can be freely changed via regex replacement.

```yaml
rule:
  any:
    - pattern: |
        defmodule $M do 
          IO.puts($A)
        end
transform:
  NEW_MOD:
    replace:
      by: ConcreteFactoryImpl
      replace: $
      source: $M
fix: |
  defmodule $NEW_MOD do 
    def msg($A) do 
      IO.puts(:stdout,$A)
    end 
  end
```

https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6ImVsaXhpciIsInF1ZXJ5IjoiY29uc29sZS5sb2coJE1BVENIKSIsInJld3JpdGUiOiJsb2dnZXIubG9nKCRNQVRDSCkiLCJjb25maWciOiJydWxlOlxuICBhbnk6XG4gICAgLSBwYXR0ZXJuOiB8XG4gICAgICAgIGRlZm1vZHVsZSAkTSBkbyBcbiAgICAgICAgICBJTy5wdXRzKCRBKVxuICAgICAgICBlbmRcbnRyYW5zZm9ybTpcbiAgTkVXX01PRDpcbiAgICByZXBsYWNlOlxuICAgICAgYnk6IENvbmNyZXRlRmFjdG9yeUltcGxcbiAgICAgIHJlcGxhY2U6ICRcbiAgICAgIHNvdXJjZTogJE1cbmZpeDogfFxuICBkZWZtb2R1bGUgJE5FV19NT0QgZG8gXG4gICAgZGVmIG1zZygkQSkgZG8gXG4gICAgICBJTy5wdXRzKDpzdGRvdXQsJEEpXG4gICAgZW5kIFxuICBlbmQiLCJzb3VyY2UiOiJkZWZtb2R1bGUgTXlNb2R1bGUgZG8gXG4gIElPLnB1dHMoXCJjbm5cIilcbmVuZCJ9
