### DISCUSSION TITLE
Unable to match content using Relational Rules

### DISCUSSION THREAD

**Discussion by zxhd863943427** [ast-grep/ast-grep#1163] [Q&A]
Hello everyone! I tried to match a statement_block that contains : 

```js
this._initializedCapability = createPromiseCapability()
```

and the code looks like this:

```js
class PDFViewerApplication {
  constructor (pdfId) {
    console.log(111)
    this.pdfId = pdfId
    this._initializedCapability = createPromiseCapability()
    
  }
}
```
I used the following matching rules:
```yaml
rule:
  kind: statement_block
  has:
    pattern: this.$A = createPromiseCapability()
    stopBy: end
```
It shows that it can't be matched. 

But strangely, when I changed the source code to look like this:

```js
class PDFViewerApplication {
  constructor (pdfId) {
    console.log(111)
    this._initializedCapability = createPromiseCapability()
    
  }
}
```
It'll be able to match. This confuses me a lot. Thanks for any suggestions!
