### DISCUSSION TITLE
Need help for variadic key-value pairs transformation

### DISCUSSION THREAD

**Discussion by kiokuless** [ast-grep/ast-grep#1192] [Q&A] [answered]
I am trying to use ast-grep to transform logger calls in Go code. Specifically, I want to convert the following pattern:

### from
```go
log.Info("Hello, World!", "key", "value", "key2", "value2")
```

### to
```go
log.Any("key", "value").Any("key2", "value2").Info().Msg("Hello, World!")
```

I believe it might be necessary to apply some kind of transformation to `$$$ARGS`,  similar to `$key, $value, $rest...`, but I can't come up with a good idea.

```yaml
id: match-logger-info
language: go
rule:
  any:
    - pattern:
      context: "func t() { $$A.Info($MSG, $$$ARGS) }"
      selector: call_expression
```

**Comment by HerringtonDarkholme** [comment]
I think this can be done via [rewriter](https://ast-grep.github.io/reference/yaml/rewriter.html)

Recommended doc:
1. https://ast-grep.github.io/reference/yaml/rewriter.html
2. https://ast-grep.github.io/reference/yaml/transformation.html#rewrite
3. https://ast-grep.github.io/advanced/find-n-patch.html

**Reply by HerringtonDarkholme** [reply, marked as answer]
This rule should work. You can try using gpt-4 to explain the rule.

The tricky part is how to match string appearing at even position, and use advanced features like `transform`/`rewriter`

https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6ImdvIiwicXVlcnkiOiIkTUVUSE9EKFxuICAgICRBLCAvLyBDb21tZW50XG4gICAgJEZcbikiLCJyZXdyaXRlIjoibV9tZW1iZXJOZXdOYW1lIiwiY29uZmlnIjoiaWQ6IG1hdGNoLWxvZ2dlci1pbmZvXG5sYW5ndWFnZTogZ29cbnJ1bGU6XG4gIGFueTpcbiAgICAtIHBhdHRlcm46XG4gICAgICAgIGNvbnRleHQ6IFwiZnVuYyB0KCkgeyAkJEEuSW5mbygkTVNHLCAkJCRBUkdTKSB9XCJcbiAgICAgICAgc2VsZWN0b3I6IGNhbGxfZXhwcmVzc2lvblxudXRpbHM6XG4gIGlzLWZpcnN0OlxuICAgIG5vdDpcbiAgICAgIGZvbGxvd3M6XG4gICAgICAgIHBhdHRlcm46ICRfXG4gICAgICAgIHN0b3BCeTogXG4gICAgICAgICAgcGF0dGVybjogJF9cbiAgaXMtb2RkOlxuICAgIHBhdHRlcm46ICRfXG4gICAgYW55OlxuICAgIC0gbWF0Y2hlczogaXMtZmlyc3QgXG4gICAgLSBmb2xsb3dzOiB7IG1hdGNoZXM6IGlzLWV2ZW4sIHN0b3BCeToge3BhdHRlcm46ICRfIH19XG4gIGlzLWV2ZW46XG4gICAgcGF0dGVybjogJF9cbiAgICBub3Q6IHsgbWF0Y2hlczogaXMtZmlyc3QgfVxuICAgIGZvbGxvd3M6XG4gICAgICB7IG1hdGNoZXM6IGlzLW9kZCwgc3RvcEJ5OiB7cGF0dGVybjogJF8gfSB9XG5yZXdyaXRlcnM6XG4tIGlkOiBjb252ZXJ0X3RvX2FueVxuICBydWxlOlxuICAgIGtpbmQ6IGludGVycHJldGVkX3N0cmluZ19saXRlcmFsXG4gICAgcGF0dGVybjogJEtFWVxuICAgIG1hdGNoZXM6IGlzLWV2ZW5cbiAgICBwcmVjZWRlczpcbiAgICAgIGtpbmQ6IGludGVycHJldGVkX3N0cmluZ19saXRlcmFsXG4gICAgICBwYXR0ZXJuOiAkVkFMXG4gICAgICBzdG9wQnk6IGVuZFxuICBmaXg6IEFueSgkS0VZLCAkVkFMKVxudHJhbnNmb3JtOlxuICBGSVhFRDpcbiAgICByZXdyaXRlOlxuICAgICAgcmV3cml0ZXJzOiBbY29udmVydF90b19hbnldXG4gICAgICBzb3VyY2U6ICQkJEFSR1NcbiAgICAgIGpvaW5CeTogXCIuXCJcbmZpeDogbG9nLiRGSVhFRC5JbmZvKCkuTXNnKCRNU0cpIiwic291cmNlIjoiZnVuYyB0ZXN0KCkge1xuICAgIGxvZy5JbmZvKFwiSGVsbG8sIFdvcmxkIVwiLCBcImtleVwiLCBcInZhbHVlXCIsIFwia2V5MlwiLCBcInZhbHVlMlwiKVxufSJ9

**Reply by HerringtonDarkholme** [reply]
<img width="1126" alt="image" src="https://github.com/ast-grep/ast-grep/assets/2883231/68925461-831c-44c1-972e-17462677b4b2">

**Reply by kiokuless** [reply]
Thank you so much for your incredibly detailed response on the playground. I learn a lot from your example. Thanks again!

**Reply by HerringtonDarkholme** [reply]
In future ast-grep may have `nthChild` rule to filter even/odd ast node. https://github.com/ast-grep/ast-grep/issues/676 It can be used to simplify the rule a lot.

**Reply by HerringtonDarkholme** [reply]
the `nthChild` operator can help simplify the rule a lot! It is currently available on the main branch. 

Example

```yml
id: match-logger-info
language: go
rule:
  any:
  - pattern:
      context: "func t() { $$A.Info($MSG, $$$ARGS) }"
      selector: call_expression
rewriters:
- id: convert_to_any
  rule:
    kind: interpreted_string_literal
    pattern: $KEY
    nthChild: 2n
    precedes:
      kind: interpreted_string_literal
      pattern: $VAL
      stopBy: end
  fix: Any($KEY, $VAL)
transform:
  FIXED:
    rewrite:
      rewriters: [convert_to_any]
      source: $$$ARGS
      joinBy: "."
fix: log.$FIXED.Info().Msg($MSG)
```

Output

<img width="936" alt="image" src="https://github.com/ast-grep/ast-grep/assets/2883231/25714f86-d669-48dd-96a1-f00e363d13ec">
