### DISCUSSION TITLE
How to match object keys and their values in javascript?

### DISCUSSION THREAD

**Discussion by danielo515** [ast-grep/ast-grep#1234] [Q&A]
Hello.
I have a bunch of methods inside objects that I want to transform. However, it seems to be impossible to match both the key name and the arrow_function.
To give you some context, this pattern works for a object with a single method:
```ts
{ $M: ($$$A) => $MATCH }
```

The problem is that using the pattern is only able to match objects with the same amount of properties that I set. So, that will not match this:

```ts
{ a: (x) => x + 1, b: (x) => x + 2 }
```
How can I write such pattern?
I also tried using rules, but the best I can get is matching the arrow function inside the object, but again, I can not match the key name (which I need for my refactor)

**Comment by HerringtonDarkholme** [comment]
Can you try the playground? https://ast-grep.github.io/playground.html

It looks like using pattern object works pretty fine 

<img width="948" alt="image" src="https://github.com/ast-grep/ast-grep/assets/2883231/776d1ec6-3e53-4842-b358-9edf267a4070">



https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6InRzeCIsInF1ZXJ5IjoieyAkTTogKCQkJEEpID0+ICRNQVRDSCB9IiwicmV3cml0ZSI6IkRlYnVnLmFzc2VydCIsImNvbmZpZyI6InJ1bGU6XG4gIHBhdHRlcm46IFxuICAgIGNvbnRleHQ6ICd7ICRNOiAoJCQkQSkgPT4gJE1BVENIIH0nXG4gICAgc2VsZWN0b3I6IHBhaXJcbiIsInNvdXJjZSI6InsgYTogKHgpID0+IHggKyAxLCBiOiAoeCkgPT4geCArIDIgfSJ9

**Reply by danielo515** [reply]
Uh....
I think I tried that, but apparently I did it in reverse order or something. Thank you, yeah, that works.
Can I simplify it even more?
I only care if the right hand side of the pair is an arrow function, but I don't need the details of the arrow function, so my transformation will just 'wrap it'. Is it possible to refine it further with selectors and use a simpler capture ?

**Reply by danielo515** [reply]
For example, this rule is more complex (kind of) but does what I need:
```yaml
id: example1
language: javascript
rule:
  kind: pair
  all:
    - has:
        kind: arrow_function
        pattern: "$MATCH"
    - has:
        kind: property_identifier
        pattern: $M
fix: "$M: withX(titi,'$M', $MATCH)"
```
