### DISCUSSION TITLE
How to transform special if statements to ternary operators in Cpp?

### DISCUSSION THREAD

**Discussion by partner-pierre-vande-laar** [ast-grep/ast-grep#1252] [Q&A]
I have the following code
```cpp
void test_func() {
  if (i<j) {
    f(1,2,i,3,4);
  } else {
    f(1,2,j,3,4);
  }
 
   if (i<j) {
    g(i,3,4);
  } else {
    g(j,3,4);
  }
 
 
   if (i<j) {
    h(1,2,i);
  } else {
    h(1,2, j);
  }
}
```

I would like to change these if statements, such that the condition is at the argument level.

The pattern I expected doesn't work
```
if ($C) { $f($$$before, $valueTrue, $$$after); } else { $f($$$before, $valueFalse, $$$after); }
```
![image](https://github.com/ast-grep/ast-grep/assets/171016967/6360bb37-be3d-4372-9a58-47f29409bb80)

Can't this be written as a pattern?
 If not, how to change this yaml script to get what I want?
```yaml
id: ternary
rule:
  pattern: if ($C) { $f($$$before, $valueTrue, $$$after); } else { $f($$$before, $valueFalse, $$$after); }
fix:
  '$f($$$before, $C ? $valueTrue : $valueFalse, $$$after);'
```

For more background information:
Example taken from https://040coders.nl/slides/2024-05-16-concrete-syntax-patterns.pdf (and translated to ast-grep).
