### DISCUSSION TITLE
How to match these C++ expressions (from gmock / gtest)

### DISCUSSION THREAD

**Discussion by arvid-norlander** [ast-grep/ast-grep#1487] [Q&A] [answered]
Given the following example code:

```c++
class MockMyClass : public IMyClass
{
public:
   MOCK_CONST_METHOD0(getA, SomeType&());

   MOCK_CONST_METHOD0(getB, SomeOtherType());

   MOCK_CONST_METHOD0(getC, SomeThirdType*());
};
```

I tried the following rules:

```yaml
id: mock_const_method0
language: cpp
rule:
  any:
    - pattern:
        context: class { MOCK_CONST_METHOD0($FUNC, $RETURNTYPE()); }
        selector: function_declarator
    - pattern:
        context: class { MOCK_CONST_METHOD0($FUNC, $RETURNTYPE(void)); }
        selector: function_declarator
    - pattern:
        context: class { MOCK_CONST_METHOD0_T($FUNC, $RETURNTYPE()); }
        selector: function_declarator
    - pattern:
        context: class { MOCK_CONST_METHOD0_T($FUNC, $RETURNTYPE(void)); }
        selector: function_declarator

fix: MOCK_METHOD($RETURNTYPE, $FUNC, (), (const, override))
```

Unfortunately, that only seems to work with plain return types. As soon as you add in pointers or references it no longer matches. I could add entirely separate rule sets for these I guess, but that gets really verbose when you start doing the same for `MOCK_METHOD1`, `MOCK_METHOD2` etc. Is there better way of doing this?

EDIT: Even more combinatorial in explosion: `MOCK_CONST_METHOD0(getA, const T&());` is not matched by the same matcher that maches `MOCK_CONST_METHOD0(getA, T&());`

**Comment by HerringtonDarkholme** [comment, marked as answer]
Thanks for using ast-grep. It would not be too easy to "correctly" match all variants since CPP grammar is complex.
That is `Type()`, `Type&()` and `Type*()` have three different AST [kinds](https://ast-grep.github.io/advanced/core-concepts.html#named-vs-unnamed). 

However, you can try something that is not too "correct". Using regular expression [replace transformation](https://ast-grep.github.io/reference/yaml/transformation.html#replace) will be a good way to workaround 

```yml
id: mock_const_method0
language: cpp
rule:
  pattern:
    context:  class { MOCK_CONST_METHOD0($FUNC, $DECL); }
    selector: function_declarator
transform:
  RETURNTYPE:
    replace:
      by: ''
      replace: '\(.*\)'
      source: $DECL

fix: MOCK_METHOD($RETURNTYPE, $FUNC, (), (const, override))
```


[Playground](https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6ImNwcCIsInF1ZXJ5IjoiIGNsYXNzIHsgTU9DS19DT05TVF9NRVRIT0QwKCRGVU5DLCAkREVDTCk7IH0iLCJyZXdyaXRlIjoiIiwic3RyaWN0bmVzcyI6InJlbGF4ZWQiLCJzZWxlY3RvciI6IiIsImNvbmZpZyI6ImlkOiBtb2NrX2NvbnN0X21ldGhvZDBcbmxhbmd1YWdlOiBjcHBcbnJ1bGU6XG4gIHBhdHRlcm46XG4gICAgY29udGV4dDogIGNsYXNzIHsgTU9DS19DT05TVF9NRVRIT0QwKCRGVU5DLCAkREVDTCk7IH1cbiAgICBzZWxlY3RvcjogZnVuY3Rpb25fZGVjbGFyYXRvclxudHJhbnNmb3JtOlxuICBSRVRVUk5UWVBFOlxuICAgIHJlcGxhY2U6XG4gICAgICBieTogJydcbiAgICAgIHJlcGxhY2U6ICdcXCguKlxcKSdcbiAgICAgIHNvdXJjZTogJERFQ0xcblxuZml4OiBNT0NLX01FVEhPRCgkUkVUVVJOVFlQRSwgJEZVTkMsICgpLCAoY29uc3QsIG92ZXJyaWRlKSkiLCJzb3VyY2UiOiJjbGFzcyBNb2NrTXlDbGFzcyA6IHB1YmxpYyBJTXlDbGFzc1xue1xucHVibGljOlxuICAgTU9DS19DT05TVF9NRVRIT0QwKGdldEEsIFNvbWVUeXBlJigpKTtcblxuICAgTU9DS19DT05TVF9NRVRIT0QwKGdldEIsIFNvbWVPdGhlclR5cGUoKSk7XG5cbiAgIE1PQ0tfQ09OU1RfTUVUSE9EMChnZXRDLCBTb21lVGhpcmRUeXBlKigpKTtcbn07In0=)
