### DISCUSSION TITLE
Any way to catch the node type information (for example by assigning to meta variable)?

### DISCUSSION THREAD

**Discussion by AraCoders** [ast-grep/ast-grep#1491] [Q&A] [answered]
Hi,

I need to find a way to print a specific node type. for example if i am searching for a node of type "string_literal" 
and i want to assign its parent to a meta variable called $NODE_PARENT for example. but I don't want to limit the type of this parent i.e. it can be literally any type. 

now for each of string node parents, the meta variable $NODE_PARENT hold the whole textual content of the node. however what i need to print is something like: $NODE x has parent of type "pair" for example, or type "arguments". 

example rule:

```yaml
language: java
id: extract-context
rule:
  pattern: $NODE
  kind: string_literal
  inside:
    pattern: $NODE_PARENT
    stopBy: end

message: $NODE -------> $NODE_PARENT
```

Note: ^ this is a very simple rule as an example. the actual rule(s) are targeting specific strings in a very large corpus of data where we use AST-Grep to easily extract these data. however we couldn't easily find any workaround this, so i appreciate your help:) 

Thanks!
