### DISCUSSION TITLE
Rule to check if function precedes a function with the same arguments in Python

### DISCUSSION THREAD

**Discussion by jelly** [ast-grep/ast-grep#1501] [Q&A]
We have the example code:

```python
b.wait_visible("foo")
b.click("foo")
```

We want to rewrite this to `b.click()` if `b` and the arguments are the same. I tried to start with a simple rule to match precedes:

```
id: unneeded-wait-visible
rule:
  pattern: b.wait_visible($_A)
  precedes:
    kind: call
```

But this doesn't match nor `pattern: b.click(1)`.

The end result rule should basically match any function call preceding which matches `b.$method($_A)`
