### DISCUSSION TITLE
How do you rewrite a pattern recursively?

### DISCUSSION THREAD

**Discussion by steinuil** [ast-grep/ast-grep#1566] [Q&A] [answered]
I wrote two rules to transform Python's `Union[T1, T2] -> T1 | T2` and `Optional[T] -> T | None`.

<details><summary>Here are rules in question.</summary>

```yaml
id: optional
language: Python
rule:
  any:
    - pattern:
        context: 'arg: Optional[$TYPE]'
        selector: generic_type
    - pattern: Optional[$TYPE]
fix: $TYPE | None
---
id: unions
language: Python
rule:
  pattern:
    context: 'a: Union[$$$TYPES]'
    selector: generic_type
rewriters:
  - id: rewrite-unions
    rule:
      pattern: $TYPE
      kind: type
    fix: $TYPE
transform:
  UNIONS:
    rewrite:
      rewriters:
        - rewrite-unions
      source: $$$TYPES
      joinBy: " | "
fix: $UNIONS
```

</details> 

Let's say I have a type that looks like this in my codebase:

```Python
results:  Optional[Union[List[Union[str, dict]], str]]
```

What I've observed is that `ast-grep` will only fix the outermost node that matches a pattern and will not recurse into it, so that to reach a fixpoint I have to run it multiple times.

1. First run:
    ```
   Optional[Union[List[Union[str, dict]], str]] -> Union[List[Union[str, dict]], str] | None
   ```
2. Second run:
   ```
   Union[List[Union[str, dict]], str] | None -> List[Union[str, dict]] | str | None
   ```
3. Third run:
   ```
   List[Union[str, dict]] | str | None -> List[str | dict] | str | None
   ```

Is there any way to tell ast-grep to recurse into an already matched node and apply these fixes recursively without having to run it multiple times?

**Comment by HerringtonDarkholme** [comment, marked as answer]
Hi, sorry for the late reply.

> Is there any way to tell ast-grep to recurse into an already matched node

Yes, it is possible but verbose.

See the [link](https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6InB5dGhvbiIsInF1ZXJ5IjoiIiwicmV3cml0ZSI6IiIsInN0cmljdG5lc3MiOiJzbWFydCIsInNlbGVjdG9yIjoiIiwiY29uZmlnIjoicmV3cml0ZXJzOlxyXG4tIGlkOiBvcHRpb25hbFxyXG4gIGxhbmd1YWdlOiBQeXRob25cclxuICBydWxlOlxyXG4gICAgYW55OlxyXG4gICAgLSBwYXR0ZXJuOlxyXG4gICAgICAgIGNvbnRleHQ6ICdhcmc6IE9wdGlvbmFsWyRUWVBFXSdcclxuICAgICAgICBzZWxlY3RvcjogZ2VuZXJpY190eXBlXHJcbiAgICAtIHBhdHRlcm46IE9wdGlvbmFsWyRUWVBFXVxyXG4gIHRyYW5zZm9ybTpcclxuICAgIE5UOlxyXG4gICAgICByZXdyaXRlOiBcclxuICAgICAgICByZXdyaXRlcnM6IFtvcHRpb25hbCwgdW5pb25zXVxyXG4gICAgICAgIHNvdXJjZTogJFRZUEVcclxuICBmaXg6ICROVCB8IE5vbmVcclxuLSBpZDogdW5pb25zXHJcbiAgbGFuZ3VhZ2U6IFB5dGhvblxyXG4gIHJ1bGU6XHJcbiAgICBwYXR0ZXJuOlxyXG4gICAgICBjb250ZXh0OiAnYTogVW5pb25bJCQkVFlQRVNdJ1xyXG4gICAgICBzZWxlY3RvcjogZ2VuZXJpY190eXBlXHJcbiAgdHJhbnNmb3JtOlxyXG4gICAgVU5JT05TOlxyXG4gICAgICByZXdyaXRlOlxyXG4gICAgICAgIHJld3JpdGVyczpcclxuICAgICAgICAgIC0gcmV3cml0ZS11bmlvbnNcclxuICAgICAgICBzb3VyY2U6ICQkJFRZUEVTXHJcbiAgICAgICAgam9pbkJ5OiBcIiB8IFwiXHJcbiAgZml4OiAkVU5JT05TXHJcbi0gaWQ6IHJld3JpdGUtdW5pb25zXHJcbiAgcnVsZTpcclxuICAgIHBhdHRlcm46ICRUWVBFXHJcbiAgICBraW5kOiB0eXBlXHJcbiAgdHJhbnNmb3JtOlxyXG4gICAgTlQ6XHJcbiAgICAgIHJld3JpdGU6IFxyXG4gICAgICAgIHJld3JpdGVyczogW29wdGlvbmFsLCB1bmlvbnNdXHJcbiAgICAgICAgc291cmNlOiAkVFlQRVxyXG4gIGZpeDogJE5UXHJcbnJ1bGU6XHJcbiAga2luZDogdHlwZVxyXG4gIHBhdHRlcm46ICRUUEVcclxudHJhbnNmb3JtOlxyXG4gIE5FV19UWVBFOlxyXG4gICAgcmV3cml0ZTogXHJcbiAgICAgIHJld3JpdGVyczogW29wdGlvbmFsLCB1bmlvbnNdXHJcbiAgICAgIHNvdXJjZTogJFRQRVxyXG5maXg6ICRORVdfVFlQRSIsInNvdXJjZSI6InJlc3VsdHM6ICBPcHRpb25hbFtVbmlvbltMaXN0W1VuaW9uW3N0ciwgZGljdF1dLCBzdHJdXVxuIn0=)

<details>
<summary>See the rule</summary>

```yml
rewriters:
- id: optional
  language: Python
  rule:
    any:
    - pattern:
        context: 'arg: Optional[$TYPE]'
        selector: generic_type
    - pattern: Optional[$TYPE]
  transform:
    NT:
      rewrite: 
        rewriters: [optional, unions]
        source: $TYPE
  fix: $NT | None
- id: unions
  language: Python
  rule:
    pattern:
      context: 'a: Union[$$$TYPES]'
      selector: generic_type
  transform:
    UNIONS:
      rewrite:
        rewriters:
          - rewrite-unions
        source: $$$TYPES
        joinBy: " | "
  fix: $UNIONS
- id: rewrite-unions
  rule:
    pattern: $TYPE
    kind: type
  transform:
    NT:
      rewrite: 
        rewriters: [optional, unions]
        source: $TYPE
  fix: $NT
rule:
  kind: type
  pattern: $TPE
transform:
  NEW_TYPE:
    rewrite: 
      rewriters: [optional, unions]
      source: $TPE
fix: $NEW_TYPE
```

</details>


The trick here is to apply rewriters to inner types recursively.

<img width="956" alt="image" src="https://github.com/user-attachments/assets/260bbd07-8ba1-417e-8483-1099e3928e86" />
