### DISCUSSION TITLE
[Rewriters] why is this matching a sub-node that doesn't exist on the AST?

### DISCUSSION THREAD

**Discussion by ahmedelgabri** [ast-grep/ast-grep#1613] [Q&A]
I'm trying to build a transformation for TypeScript `enum`s to be simple objects instead. But I want to match `enum`s only who has assignments, here is an example:

This is the rewriter I have

```yaml
rewriters:
- id: enum-rewrite
  rule:
    kind: enum_assignment
    all:
    - has:
        field: name
        pattern: $KEY
    - has:
        field: value
        pattern: $VAL
  fix: "$KEY: $VAL"
```

So this works

```ts
enum A {
  B = 'BBB', // kind is -> enum_assignment
  C = 'CCC'
}

// convert to
const A = {
  B: 'BBB',
  C: 'CCC'
} as const
```

But also matches `enum`s like this, not sure why?

```ts
enum A {
  B,
  C,
}

// convert to
const A = {
  B, // kind is -> property_identifier
  C,
} as const
```

[Playground link](https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6InR5cGVzY3JpcHQiLCJxdWVyeSI6ImltcG9ydCgkQSkiLCJyZXdyaXRlIjoibG9nZ2VyLmxvZygkTUFUQ0gpIiwic3RyaWN0bmVzcyI6InNtYXJ0Iiwic2VsZWN0b3IiOiIiLCJjb25maWciOiJydWxlOlxuICBwYXR0ZXJuOiBlbnVtICRJRCB7JCQkQk9EWX1cbnJld3JpdGVyczpcbi0gaWQ6IGVudW0tcmV3cml0ZVxuICBydWxlOlxuICAgIGtpbmQ6IGVudW1fYXNzaWdubWVudFxuICAgIGFsbDpcbiAgICAtIGhhczpcbiAgICAgICAgZmllbGQ6IG5hbWVcbiAgICAgICAgcGF0dGVybjogJEtFWVxuICAgIC0gaGFzOlxuICAgICAgICBmaWVsZDogdmFsdWVcbiAgICAgICAgcGF0dGVybjogJFZBTFxuICBmaXg6IFwiJEtFWTogJFZBTFwiXG50cmFuc2Zvcm06XG4gIExJVEVSQUw6XG4gICAgcmV3cml0ZTpcbiAgICAgIHJld3JpdGVyczogW2VudW0tcmV3cml0ZV1cbiAgICAgIHNvdXJjZTogJCQkQk9EWVxuZml4OiAnY29uc3QgJElEID0geyRMSVRFUkFMfSBhcyBjb25zdCdcbiIsInNvdXJjZSI6ImVudW0gQSB7XG4gICAgQiA9ICdCQkInLFxuICAgIEMgPSAnQ0NDJyxcbn1cblxuXG5lbnVtIEQge1xuICAgIEUsXG4gICAgRixcbn0ifQ==)
