### DISCUSSION TITLE
[HTML] How to rename a class?

### DISCUSSION THREAD

**Discussion by php-coder** [ast-grep/ast-grep#1671] [Q&A] [answered]
Hi,

I'd like to rename a CSS class from `img-responsive` to `img-fluid` and I was able to create a rule that covers most of the possible cases ([link to playgdound](https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6Imh0bWwiLCJxdWVyeSI6IiIsInJld3JpdGUiOiIiLCJzdHJpY3RuZXNzIjoic21hcnQiLCJzZWxlY3RvciI6IiIsImNvbmZpZyI6ImlkOiByZW5hbWVfaW1nLXJlc3BvbnNpdmVfY2xhc3Ncbmxhbmd1YWdlOiBodG1sXG5ydWxlOlxuICBraW5kOiBhdHRyaWJ1dGVfdmFsdWVcbiAgcmVnZXg6ICcoXnwgKWltZy1yZXNwb25zaXZlKCB8JCknXG4gIHBhdHRlcm46ICRBVFRSU1xuIyBUT0RPOiByZXBsYWNlIG9ubHkgaW4gXCJjbGFzc1wiIGF0dHJpYnV0ZVxuIyAgZm9sbG93czpcbiMgICAga2luZDogYXR0cmlidXRlX25hbWVcbiMgICAgcmVnZXg6ICdjbGFzcydcbnRyYW5zZm9ybTpcbiAgTUlERExFX09SX0VORDpcbiAgICByZXBsYWNlOlxuICAgICAgc291cmNlOiAkQVRUUlNcbiAgICAgIHJlcGxhY2U6ICcgaW1nLXJlc3BvbnNpdmUoPzxSRVNUPiB8JCknXG4gICAgICBieTogJyBpbWctZmx1aWQkUkVTVCdcbiAgQkVHSU5fT1JfV0hPTEU6XG4gICAgcmVwbGFjZTpcbiAgICAgIHNvdXJjZTogJE1JRERMRV9PUl9FTkRcbiAgICAgIHJlcGxhY2U6ICdeaW1nLXJlc3BvbnNpdmUoPzxSRVNUPiB8JCknXG4gICAgICBieTogJ2ltZy1mbHVpZCRSRVNUJ1xuZml4OiAkQkVHSU5fT1JfV0hPTEUiLCJzb3VyY2UiOiI8IS0tIE1VU1QgTUFUQ0ggLS0+XG48aW1nIGNsYXNzPVwiaW1nLXJlc3BvbnNpdmVcIiAvPlxuXG48aW1nIGNsYXNzPVwiaW1nLXJlc3BvbnNpdmUgaW1nLXJlc3BvbnNpdmVcIiAvPlxuXG48aW1nIGNsYXNzPSdpbWctcmVzcG9uc2l2ZScvPlxuXG48c3BhbiBjbGFzcz1cImltZy1yZXNwb25zaXZlXCIgaWQ9XCJzZXJpZXMtaGlkZGVuLWltYWdlLTJcIj48L3NwYW4+XG5cbjxkaXYgY2xhc3M9XCJjbGFzcy1hdC1iZWdnaW5pbmcgaW1nLXJlc3BvbnNpdmVcIj48L2Rpdj5cblxuPGRpdiBjbGFzcz1cImltZy1yZXNwb25zaXZlIGNsYXNzLWF0LXRoZS1lbmRcIj48L2Rpdj5cblxuPGRpdiBjbGFzcz1cImNsYXNzLWF0LWJlZ2dpbmluZyBpbWctcmVzcG9uc2l2ZSBjbGFzcy1hdC10aGUtZW5kXCI+PC9kaXY+XG5cbjxkaXYgY2xhc3M9XCJpbWctcmVzcG9uc2l2ZS1iZWZvcmUgaW1nLXJlc3BvbnNpdmUgaW1nLXJlc3BvbnNpdmUtYWZ0ZXJcIj48L2Rpdj5cblxuPCEtLSBNVVNUIE5PTi1NQVRDSCAtLT5cbjxpbWcgaWQ9XCJpbWctcmVzcG9uc2l2ZVwiLz5cbjxpbWcgY2xhc3M9XCJzdWZmaXgtaW1nLXJlc3BvbnNpdmVcIi8+XG48aW1nIGNsYXNzPVwiaW1nLXJlc3BvbnNpdmUtcHJlZml4XCIvPlxuPGltZyBjbGFzcz1cIm5vbi1yZXNwb25zaXZlXCIvPlxuIn0=)):

```yaml
id: rename_img-responsive_class
language: html
rule:
  kind: attribute_value
  regex: '(^| )img-responsive( |$)'
  pattern: $ATTRS
# FIXME: replace only in "class" attribute
#  follows:
#    kind: attribute_name
#    regex: 'class'
transform:
  MIDDLE_OR_END:
    replace:
      source: $ATTRS
      replace: ' img-responsive(?<REST> |$)'
      by: ' img-fluid$REST'
  BEGIN_OR_WHOLE:
    replace:
      source: $MIDDLE_OR_END
      replace: '^img-responsive(?<REST> |$)'
      by: 'img-fluid$REST'
fix: $BEGIN_OR_WHOLE
```
It produces a false positive that I'd like to address: it should make replacement only within "class" attribute. I tried to use `inside` but it doesn't work because target (`attribute_value`) is located inside `attribute` and not `attribute_name`.

Could you give me a hint, please? Thank you in advance!

**Comment by HerringtonDarkholme** [comment, marked as answer]
You can use [`inside`](https://ast-grep.github.io/reference/rule.html#inside) + [`pattern` object](https://ast-grep.github.io/guide/rule-config/atomic-rule.html#pattern-object)

```yml
id: rename_img-responsive_class
language: html
rule:
  kind: attribute_value
  regex: '(^| )img-responsive( |$)'
  pattern: $ATTRS
  inside:
    pattern: 
      context: <b class=$A>
      selector: attribute 
    stopBy: end
transform:
  MIDDLE_OR_END:
    replace:
      source: $ATTRS
      replace: ' img-responsive(?<REST> |$)'
      by: ' img-fluid$REST'
  BEGIN_OR_WHOLE:
    replace:
      source: $MIDDLE_OR_END
      replace: '^img-responsive(?<REST> |$)'
      by: 'img-fluid$REST'
fix: $BEGIN_OR_WHOLE
```

[playground](https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6Imh0bWwiLCJxdWVyeSI6IiIsInJld3JpdGUiOiIiLCJzdHJpY3RuZXNzIjoic21hcnQiLCJzZWxlY3RvciI6IiIsImNvbmZpZyI6ImlkOiByZW5hbWVfaW1nLXJlc3BvbnNpdmVfY2xhc3Ncbmxhbmd1YWdlOiBodG1sXG5ydWxlOlxuICBraW5kOiBhdHRyaWJ1dGVfdmFsdWVcbiAgcmVnZXg6ICcoXnwgKWltZy1yZXNwb25zaXZlKCB8JCknXG4gIHBhdHRlcm46ICRBVFRSU1xuICBpbnNpZGU6XG4gICAgcGF0dGVybjogXG4gICAgICBjb250ZXh0OiA8YiBjbGFzcz0kQT5cbiAgICAgIHNlbGVjdG9yOiBhdHRyaWJ1dGUgXG4gICAgc3RvcEJ5OiBlbmRcbnRyYW5zZm9ybTpcbiAgTUlERExFX09SX0VORDpcbiAgICByZXBsYWNlOlxuICAgICAgc291cmNlOiAkQVRUUlNcbiAgICAgIHJlcGxhY2U6ICcgaW1nLXJlc3BvbnNpdmUoPzxSRVNUPiB8JCknXG4gICAgICBieTogJyBpbWctZmx1aWQkUkVTVCdcbiAgQkVHSU5fT1JfV0hPTEU6XG4gICAgcmVwbGFjZTpcbiAgICAgIHNvdXJjZTogJE1JRERMRV9PUl9FTkRcbiAgICAgIHJlcGxhY2U6ICdeaW1nLXJlc3BvbnNpdmUoPzxSRVNUPiB8JCknXG4gICAgICBieTogJ2ltZy1mbHVpZCRSRVNUJ1xuZml4OiAkQkVHSU5fT1JfV0hPTEUiLCJzb3VyY2UiOiI8IS0tIE1VU1QgTUFUQ0ggLS0+XG48aW1nIGNsYXNzPVwiaW1nLXJlc3BvbnNpdmVcIiAvPlxuXG48aW1nIGNsYXNzPVwiaW1nLXJlc3BvbnNpdmUgaW1nLXJlc3BvbnNpdmVcIiAvPlxuXG48aW1nIGNsYXNzPSdpbWctcmVzcG9uc2l2ZScvPlxuXG48c3BhbiBjbGFzcz1cImltZy1yZXNwb25zaXZlXCIgaWQ9XCJzZXJpZXMtaGlkZGVuLWltYWdlLTJcIj48L3NwYW4+XG5cbjxkaXYgY2xhc3M9XCJjbGFzcy1hdC1iZWdnaW5pbmcgaW1nLXJlc3BvbnNpdmVcIj48L2Rpdj5cblxuPGRpdiBjbGFzcz1cImltZy1yZXNwb25zaXZlIGNsYXNzLWF0LXRoZS1lbmRcIj48L2Rpdj5cblxuPGRpdiBjbGFzcz1cImNsYXNzLWF0LWJlZ2dpbmluZyBpbWctcmVzcG9uc2l2ZSBjbGFzcy1hdC10aGUtZW5kXCI+PC9kaXY+XG5cbjxkaXYgY2xhc3M9XCJpbWctcmVzcG9uc2l2ZS1iZWZvcmUgaW1nLXJlc3BvbnNpdmUgaW1nLXJlc3BvbnNpdmUtYWZ0ZXJcIj48L2Rpdj5cblxuPCEtLSBNVVNUIE5PTi1NQVRDSCAtLT5cbjxpbWcgaWQ9XCJpbWctcmVzcG9uc2l2ZVwiLz5cbjxpbWcgY2xhc3M9XCJzdWZmaXgtaW1nLXJlc3BvbnNpdmVcIi8+XG48aW1nIGNsYXNzPVwiaW1nLXJlc3BvbnNpdmUtcHJlZml4XCIvPlxuPGltZyBjbGFzcz1cIm5vbi1yZXNwb25zaXZlXCIvPlxuIn0=)

**Reply by HerringtonDarkholme** [reply]
https://ast-grep.github.io/guide/rule-config/relational-rule.html#stopby

**Reply by php-coder** [reply]
Thanks!

The usage of `context` isn't clear to me.
* Why you have used `<a>` tag and it works for any tag?
* Why you haven't quote attribute value and everything works?
* Why it works also when a tag has multiple attributes?

Also I tried to use a variable instead of a tag name: `context: <$TAG class=$ANY>` -- it works. Then I tried to use a non-captured match for a class name: `context: <$TAG class=$_ANY>` -- works again. But it's stopped to work when I add it to a tag name (`context: <$_TAG class=$_ANY>`)! It also doesn't work if I use `$ANY_TAG` instead of `$TAG` :-/ Is it a bug?

**Reply by php-coder** [reply]
How I can find which value I should provide to `selector`? For example, here is another rule where I'm trying to replace `href` attribute of the `link` tag and I'm unable to provide a tag with selector:
```yaml
id: update_link_href
language: html
rule:
  kind: attribute_value
  regex: '/bootstrap\.min\.css$'
  inside:
    all:
      - pattern:
          context: '<$TAG href=$_ANY>'
          selector: attribute
      - pattern:
          context: '<link href=$_ANY>'
          # FIXME: tag_name doesn't work. start_tag either :(
          selector: tag_name
    stopBy: end
fix: 'https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css'
```
