### DISCUSSION TITLE
How to specify path to yaml object?

### DISCUSSION THREAD

**Discussion by dudicoco** [ast-grep/ast-grep#1695] [Q&A] [answered]
Hi,

Given a yaml object:
```yaml
deployment:
  strategy:
    type: RollingUpdate
    maxUnavailable: 0
    maxSurge: 1
```

With `yq` I can specify the path to a value like so: `.deployment.strategy.maxUnavailable`.

I can't seem to achieve this with ast-grep, i've tried all kinds of $ matches after the strategy field with no success: https://ast-grep.github.io/playground.html#eyJtb2RlIjoiUGF0Y2giLCJsYW5nIjoieWFtbCIsInF1ZXJ5IjoiZGVwbG95bWVudDogXG4gIHN0cmF0ZWd5OlxuICAgIG1heFVuYXZhaWxhYmxlOiAkQSIsInJld3JpdGUiOiIiLCJzdHJpY3RuZXNzIjoic21hcnQiLCJzZWxlY3RvciI6IiIsImNvbmZpZyI6IiMgWUFNTCBSdWxlIGlzIG1vcmUgcG93ZXJmdWwhXG4jIGh0dHBzOi8vYXN0LWdyZXAuZ2l0aHViLmlvL2d1aWRlL3J1bGUtY29uZmlnLmh0bWwjcnVsZVxuXG5pZDogdmVyc2lvbmpzb25cbmxhbmd1YWdlOiBqc29uXG5ydWxlOlxuICBwYXR0ZXJuOlxuICAgIHNlbGVjdG9yOiBwYWlyXG4gICAgY29udGV4dDogJ3tcInZlcnNpb25cIjogXCIkQVwiJ1xuZml4OiB8LVxuICAgIFwidmVyc2lvblwiOiBcIjIuMFwiIiwic291cmNlIjoiZGVwbG95bWVudDpcbiAgc3RyYXRlZ3k6XG4gICAgdHlwZTogUm9sbGluZ1VwZGF0ZVxuICAgIG1heFVuYXZhaWxhYmxlOiAwXG4gICAgbWF4U3VyZ2U6IDEifQ==

**Comment by HerringtonDarkholme** [comment, marked as answer]
You need to use `rule`

```yml
rule:
  pattern: 'maxUnavailable: $A'
  inside:
    pattern: |-
      deployment:
        strategy: $B
    stopBy: end
```


https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6InlhbWwiLCJxdWVyeSI6IiIsInJld3JpdGUiOiIiLCJzdHJpY3RuZXNzIjoic21hcnQiLCJzZWxlY3RvciI6IiIsImNvbmZpZyI6InJ1bGU6XG4gIHBhdHRlcm46ICdtYXhVbmF2YWlsYWJsZTogJEEnXG4gIGluc2lkZTpcbiAgICBwYXR0ZXJuOiB8LVxuICAgICAgZGVwbG95bWVudDpcbiAgICAgICAgc3RyYXRlZ3k6ICRCXG4gICAgc3RvcEJ5OiBlbmQiLCJzb3VyY2UiOiJkZXBsb3ltZW50OlxuICBzdHJhdGVneTpcbiAgICB0eXBlOiBSb2xsaW5nVXBkYXRlXG4gICAgbWF4VW5hdmFpbGFibGU6IDBcbiAgICBtYXhTdXJnZTogMSJ9
