### DISCUSSION TITLE
Is it possible to see fixes when using -U?

### DISCUSSION THREAD

**Discussion by liiight** [ast-grep/ast-grep#1705] [Q&A] [answered]
I Apologize it this is documented or already been answered, but I couldn't find the answer if it did.
I wish to run `sg scan -U` and see the report of issues in addition to them being fixed.
As i understand, running without the `-U` flag is the only way to see this report.
I wish to use ast-grep as a pre-commit hook and I'd like to output the changes and fix them in the same process.
Currently I have a workaround for this like so:
```yaml
      - id: ast-grep
        name: Run ast-grep based tests (Report)
        entry: sg scan
        language: system
        types:
          - python

      - id: ast-grep-fix
        name: Run ast-grep based tests (Fix)
        entry: sg scan -U
        language: system
        types:
          - python
 ```
 This works but is a bit clunky. I was wondering if there was something I was missing.

Thanks in advance and thank you for this truly amazing tool! 🙏
