### DISCUSSION TITLE
How to filter matches based in inverse relational conditions?

### DISCUSSION THREAD

**Discussion by goodspark** [ast-grep/ast-grep#1828] [Q&A] [answered]
I'd like to exclude matches for a rule if it's _not_ present inside another rule.

Example:
```py
# Bad
x.asd()

# OK
with something():
  x.asd()
```

I'm trying to make a rule like so but it doesn't seem to work.
```yml
rule:
  kind: call
  pattern: x.asd($$$)
  inside:
    not:
      kind: with_statement
      pattern: |
        with something():
          $$$
```

**Comment by HerringtonDarkholme** [comment, marked as answer]
not and inside should be flipped. the rule read as "a node should **not** be **inside** another node", note the order.

you also need [stopBy](https://ast-grep.github.io/guide/rule-config/relational-rule.html#stopby) modifier

```yaml
rule:
  kind: call
  pattern: x.asd($$$)
  not:
    inside:
      kind: with_statement
      pattern: |
        with something():
          $$$
      stopBy: end
```

https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6InB5dGhvbiIsInF1ZXJ5IjoiRXhwcjo6VmFsdWUoJE1BVENIKSIsInJld3JpdGUiOiJFeHByOjpWYWx1ZSgkTUFUQ0gud2l0aF9lbXB0eV9zcGFuKCkpIiwic3RyaWN0bmVzcyI6InNtYXJ0Iiwic2VsZWN0b3IiOiIiLCJjb25maWciOiJydWxlOlxuICBraW5kOiBjYWxsXG4gIHBhdHRlcm46IHguYXNkKCQkJClcbiAgbm90OlxuICAgIGluc2lkZTpcbiAgICAgIGtpbmQ6IHdpdGhfc3RhdGVtZW50XG4gICAgICBwYXR0ZXJuOiB8XG4gICAgICAgIHdpdGggc29tZXRoaW5nKCk6XG4gICAgICAgICAgJCQkXG4gICAgICBzdG9wQnk6IGVuZCIsInNvdXJjZSI6IiMgQmFkXG54LmFzZCgpXG5cbiMgT0tcbndpdGggc29tZXRoaW5nKCk6XG4gIHguYXNkKCkifQ==
