### DISCUSSION TITLE
Multiple relation requirements

### DISCUSSION THREAD

**Discussion by mathstuf** [ast-grep/ast-grep#1992] [Q&A] [answered]
Is there a way to require two relational rules? For example, I want to say "immediately before a `,`" and "the *next* node needs to be a `string_literal`". Something like:

```yaml
rule:
  precedes:
    - pattern: ','
    - any:
        - kind: string_literal
        - kind: char_literal
      stopBy:
        matches: an-argument
```

**Comment by mathstuf** [comment]
This works, but is kind of repetitive (I only have a few "stop at" tokens that are interesting, but if there were a dozen…):

```yaml
rule:
  precedes:
    any:
      - kind: string_literal
        follows:
          pattern: ','
      - kind: char_literal
        follows:
          pattern: ','
    stopBy:
      matches: an-argument
```

**Reply by HerringtonDarkholme** [reply, marked as answer]
how about this?

```yml
rule:
  precedes:
    any:
      - kind: string_literal
      - kind: char_literal
    follows:
      pattern: ','
    stopBy:
      matches: an-argument
```

**Reply by mathstuf** [reply]
Ah, right `precedes` is a rule with `stopBy` as additional field. Thanks.

I also had the insight to factor out the `any:` bit into its own `utils` rule, so I can end up with:

```yaml
rule:
  precedes:
    matches: my-string-literal
    follows:
      pattern: ','
    stopBy:
      matches: an-argument
```

Which is good because I remembered user-defined literals and raw string literals, so there are two more patterns to match anyways.
