### DISCUSSION TITLE
[JS/TS] Add missing function

### DISCUSSION THREAD

**Discussion by KnisterPeter** [ast-grep/ast-grep#2061] [Q&A] [answered]
Hi there,

I would like to write a rule which checks if a function is exported from a module and if not, add a default implementation. How is this possible? 

So far I can only match exported functions or nothing. And it's not possible to rewrite nothing -> which would be a way to add something.

**Comment by HerringtonDarkholme** [comment, marked as answer]
you can find the root ast node like `program` and capture it to `$PROG`

your fix code can be

```yml
fix:
  $PROG
  export function missing() {}
```

**Reply by KnisterPeter** [reply]
I've found a solution as well which is a bit more complex:

```yaml
rule:
  kind: program
  not:
    has:
      pattern: export function missingFunction($$$_ARGS) { $$$_BODY }
  pattern: $$$PROGRAM
fix: |-
  $PROGRAM
  export function missingFunction() {
    // ...
  }
```
