### DISCUSSION TITLE
Something wrong with regex?

### DISCUSSION THREAD

**Discussion by 93578237** [ast-grep/ast-grep#284] [Q&A] [answered]
Im using this rule to disable url paths without trailing slash (in django)
```yaml
id: test
message: test
severity: error
language: Python
rule:
  regex: ^.+[^/]$
  kind: string
  not:
    kind: keyword_argument
  inside:
    kind: argument_list
    inside:
      pattern: path($$$)
```
but sg returns empty strings or strings with trailing slash. What am I missing?

**Comment by HerringtonDarkholme** [comment, marked as answer]
Regex is written in rust's syntax. https://docs.rs/regex/latest/regex/
Also, yaml has special string symbols. So don't forget to quote regex.

You can also use playground to debug it.
https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6InB5dGhvbiIsInF1ZXJ5IjoiY29uc29sZS5sb2coJE1BVENIKSIsImNvbmZpZyI6ImlkOiB0ZXN0XG5tZXNzYWdlOiB0ZXN0XG5zZXZlcml0eTogZXJyb3Jcbmxhbmd1YWdlOiBQeXRob25cbnJ1bGU6XG4gIHJlZ2V4OiAnXCIuK1teL11cIidcbiAga2luZDogc3RyaW5nXG4gIG5vdDpcbiAgICBraW5kOiBrZXl3b3JkX2FyZ3VtZW50XG4gIGluc2lkZTpcbiAgICBraW5kOiBhcmd1bWVudF9saXN0XG4gICAgaW5zaWRlOlxuICAgICAgcGF0dGVybjogcGF0aCgkJCQpIiwic291cmNlIjoicGF0aCgxMjMpXG5wYXRoKFwic2Rmd2V3ZVwiKSJ9

**Reply by 93578237** [reply]
thx (for fast reply also)! 
I forgot to quote (im using single quotes in code)

**Reply by 93578237** [reply]
can i add `fix` to this rule for adding trailing slash?
maybe somehow map regex match with $META

**Reply by HerringtonDarkholme** [reply]
Not that easy for now... You can try "$META + '/'" at the moment because string manipulation is not supported well now.

**Reply by 93578237** [reply]
But where can I introduce META var, if I use regex as pattern? I tried to use $META as pattern and regex as constraints, but you can constrain only kind.

**Reply by HerringtonDarkholme** [reply]
```
id: test
message: test
severity: error
language: Python
rule:
  pattern: $META
  regex: '".+[^/]"'
  kind: string
  not:
    kind: keyword_argument
  inside:
    kind: argument_list
    inside:
      pattern: path($$$)
fix: $META + '/'
```

https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6InB5dGhvbiIsInF1ZXJ5IjoiY29uc29sZS5sb2coJE1BVENIKSIsImNvbmZpZyI6ImlkOiB0ZXN0XG5tZXNzYWdlOiB0ZXN0XG5zZXZlcml0eTogZXJyb3Jcbmxhbmd1YWdlOiBQeXRob25cbnJ1bGU6XG4gIHBhdHRlcm46ICRNRVRBXG4gIHJlZ2V4OiAnXCIuK1teL11cIidcbiAga2luZDogc3RyaW5nXG4gIG5vdDpcbiAgICBraW5kOiBrZXl3b3JkX2FyZ3VtZW50XG4gIGluc2lkZTpcbiAgICBraW5kOiBhcmd1bWVudF9saXN0XG4gICAgaW5zaWRlOlxuICAgICAgcGF0dGVybjogcGF0aCgkJCQpXG5maXg6ICRNRVRBICsgJy8nIiwic291cmNlIjoicGF0aCgxMjMpXG5wYXRoKFwic2Rmd2V3ZVwiKSJ9
