### DISCUSSION TITLE
`ignores`  in rules  raises `Configuraiont not found!`

### DISCUSSION THREAD

**Discussion by 93578237** [ast-grep/ast-grep#285] [Q&A] [answered]
With `ignores` in rules tests for these rules are always skipped with `Configuraiont not found!...`.
How to fix it?

**Comment by HerringtonDarkholme** [comment]
Can you give a concrete example? Thanks

**Reply by 93578237** [reply]
```yaml
id: django-foreign-key-to
ignores:
  - "./**/migrations/*.py"
message: Use explicit imports of models
severity: warning
language: Python
rule:
  kind: string
  regex: "'*.\\..*'"
  any:
  - inside:
      kind: argument_list
      follows:
        kind: attribute
        pattern: models.ForeignKey
  - inside:
      kind: keyword_argument
      has:
        kind: identifier
        pattern: to
      inside:
        kind: argument_list
        follows:
          kind: attribute
          pattern: models.ForeignKey
```
