### DISCUSSION TITLE
Code Demo for all supported languages?

### DISCUSSION THREAD

**Discussion by HerringtonDarkholme** [ast-grep/ast-grep#364] [General]
What's your favorite hello-world code in your programming language?

We can showcase ast-grep's pattern in your favorite language! 

I'm planning to add them as playground links in the homepage.

**Comment by HerringtonDarkholme** [comment]
JavaScript:

1. remove unnecessary useState type 

```bash
sg -p 'useState<number>($A)' -r 'useState($A)'
sg -p 'useState<string>($A)' -r 'useState($A)'
sg -p 'useState<boolean>($A)' -r 'useState($A)'
```

**Comment by HerringtonDarkholme** [comment]
Avoid wrong usage of jsx

```yaml
id: do-what-brooooooklyn-said
language: Tsx
severity: error
rule:
  kind: jsx_expression
  has:
    pattern: $A && $B
  not:
    inside:
      kind: jsx_attribute
fix: "{$A ? $B : null}"
```

**Comment by HerringtonDarkholme** [comment]
Replace console.log
```bash
sg -p 'console.log' -r 'console.debug'
```

**Comment by HerringtonDarkholme** [comment]
HTML extractor

https://twitter.com/trevmanz/status/1671572111582978049?s=20

**Comment by HerringtonDarkholme** [comment]
check no-non-null-asserted-optional-chain

```
sg -p '$A?.$B!'
sg -p '$A?.()!'
```

https://twitter.com/hd_nvim/status/1676018922066411520/photo/1

**Comment by HerringtonDarkholme** [comment]
おれはイモー党だ
![image](https://github.com/ast-grep/ast-grep/assets/2883231/4d58d65d-1223-4608-85c2-c5deb2f01c6b)


https://ast-grep.github.io/playground.html#eyJtb2RlIjoiUGF0Y2giLCJsYW5nIjoicnVieSIsInF1ZXJ5IjoiSWRvbC5uZXcoJE9TSElfTk9fS08pIiwicmV3cml0ZSI6ImxvZ2dlci5sb2coJE1BVENIKSIsImNvbmZpZyI6InJ1bGU6XG4gIHBhdHRlcm46IElkb2wubmV3KCRPU0hJX05PX0tPKSIsInNvdXJjZSI6IiMgVGhlIElkb2wgY2xhc3NcbmNsYXNzIElkb2xcbiAgZGVmIGluaXRpYWxpemUobmFtZSlcbiAgICBAbmFtZSA9IG5hbWUuY2FwaXRhbGl6ZVxuICBlbmRcbiAgZGVmIGRlYnV0XG4gICAgcHV0cyBcIuiLuuODl+ODreaJgOWxniAje0BuYW1lfeOBp+OBmSFcIlxuICBlbmRcbmVuZFxuXG4jIENyZWF0ZSBhIG5ldyBJZG9sIVxub3NoaSA9IElkb2wubmV3KFwi55Gg576O6KGjXCIpXG5cbiMgT3V0cHV0IFwi6Iu644OX44Ot5omA5bGeIOeRoOe+juiho+OBp+OBmSFcIlxub3NoaS5kZWJ1dFxuXG4ifQ==

**Comment by HerringtonDarkholme** [comment]
#  A to B Inferred Transforms 

Pattern
```ruby
$LIST.select { |$V| $V.$METHOD }
```
Rewrite
```ruby
$LIST.select(&:$METHOD)
```
Example

```ruby
[1, 2, 3].select { |v| v.even? }
[1, 2, 3].select(&:even?)
```

Adapted from https://dev.to/baweaver/future-of-ruby-ast-tooling-9i1

https://ast-grep.github.io/playground.html#eyJtb2RlIjoiUGF0Y2giLCJsYW5nIjoicnVieSIsInF1ZXJ5IjoiJExJU1Quc2VsZWN0IHsgfCRWfCAkVi4kTUVUSE9EIH0iLCJyZXdyaXRlIjoiJExJU1Quc2VsZWN0KCY6JE1FVEhPRCkiLCJjb25maWciOiIjIFlBTUwgUnVsZSBpcyBtb3JlIHBvd2VyZnVsIVxuIyBodHRwczovL2FzdC1ncmVwLmdpdGh1Yi5pby9ndWlkZS9ydWxlLWNvbmZpZy5odG1sI3J1bGVcbnJ1bGU6XG4gIGFueTpcbiAgICAtIHBhdHRlcm46IGNvbnNvbGUubG9nKCRBKVxuICAgIC0gcGF0dGVybjogY29uc29sZS5kZWJ1ZygkQSlcbmZpeDpcbiAgbG9nZ2VyLmxvZygkQSkiLCJzb3VyY2UiOiJbMSwgMiwgM10uc2VsZWN0IHsgfHZ8IHYuZXZlbj8gfSJ9

**Comment by HerringtonDarkholme** [comment]
# Migrate action_filter in RoR

Migrate `{before,after,around}_filter` to `{before,after,around}_action` in Ruby On Rails

https://twitter.com/hd_nvim/status/1680721979471728640?s=20

![image](https://github.com/ast-grep/ast-grep/assets/2883231/f1f76b7f-be4b-4c4a-9d6a-940feb66f13a)

**Comment by HerringtonDarkholme** [comment]
Rust 
https://github.com/ast-grep/ast-grep/discussions/431

**Comment by HerringtonDarkholme** [comment]
Rust
https://github.com/ast-grep/ast-grep/issues/550

**Comment by HerringtonDarkholme** [comment]
A python example https://engineering.soroco.com/abstract-syntax-tree-for-patching-code-and-assessing-code-quality/

**Comment by HerringtonDarkholme** [comment]
Rewriting Mobx https://twitter.com/meetliby/status/1698601672568901723?s=20

![image](https://github.com/ast-grep/ast-grep/assets/2883231/a7471569-1adb-43fd-84c3-73846650e459)

**Comment by HerringtonDarkholme** [comment]
C example and JS example
https://twitter.com/DasSurma/status/1706086320051794217

**Comment by HerringtonDarkholme** [comment]
no inline await in promise all array

https://twitter.com/alvarlagerlof/status/1720182566135779582

https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6ImphdmFzY3JpcHQiLCJxdWVyeSI6ImNvbnNvbGUubG9nKCRNQVRDSCkiLCJyZXdyaXRlIjoibG9nZ2VyLmxvZygkTUFUQ0gpIiwiY29uZmlnIjoiaWQ6IG5vLWF3YWl0LWluLXByb21pc2UtYWxsXG5zZXZlcml0eTogZXJyb3Jcbmxhbmd1YWdlOiBKYXZhU2NyaXB0XG5tZXNzYWdlOiBObyBhd2FpdCBpbiBQcm9taXNlLmFsbFxucnVsZTpcbiAgcGF0dGVybjogYXdhaXQgJEFcbiAgaW5zaWRlOlxuICAgIHBhdHRlcm46IFByb21pc2UuYWxsKCQpXG4gICAgc3RvcEJ5OlxuICAgICAgbm90OiB7IGFueTogW3traW5kOiBhcnJheX0sIHtraW5kOiBhcmd1bWVudHN9XSB9XG5maXg6ICRBIiwic291cmNlIjoiY29uc3QgW2ZvbywgYmFyXSA9IGF3YWl0IFByb21pc2UuYWxsKFtcbiAgYXdhaXQgZ2V0Rm9vKCksXG4gIGdldEJhcigpLFxuICAoYXN5bmMgKCkgPT4geyBhd2FpdCBnZXRCYXooKX0pKCksXG5dKSJ9

**Comment by HerringtonDarkholme** [comment]
console.error in catch block

**Comment by HerringtonDarkholme** [comment]
Migrate openai python library
https://x.com/hd_nvim/status/1721802245770297642

**Comment by HerringtonDarkholme** [comment]
Rewrite import/export to export
https://gist.github.com/zthxxx/075d5ca0ffa725c0feb98049619ad663

**Comment by HerringtonDarkholme** [comment]
add color prop if there's no existing color or variant prop.

https://x.com/me_jd_solanki/status/1734463785224618220?s=20

**Comment by HerringtonDarkholme** [comment]
https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6InBocCIsInF1ZXJ5IjoiYXN0LWdyZXAgJCQkQVJHUyAtLWlubGluZS1ydWxlcyAkUlVMRSIsInJld3JpdGUiOiJzZyAkJCRBUkdTIC0taW5saW5lLXJ1bGVzICRSVUxFIiwiY29uZmlnIjoicnVsZTpcbiAga2luZDogY2FzdF9leHByZXNzaW9uXG4gIGhhczpcbiAgICBwYXR0ZXJuOiAkQVxuICBpbnNpZGU6XG4gICAga2luZDogZXhwcmVzc2lvbl9zdGF0ZW1lbnRcbiAgICBzdG9wQnk6IGVuZFxuICAgIGZvbGxvd3M6XG4gICAgICBwYXR0ZXJuOiBcbiAgICAgICAgY29udGV4dDogJzw/cGhwICRBID0gREI6OnJhdygkXyk7J1xuICAgICAgICBzZWxlY3RvcjogZXhwcmVzc2lvbl9zdGF0ZW1lbnRcbiAgICAgIHN0b3BCeTogZW5kXG5maXg6ICRBLT5nZXRWYWx1ZShEQjo6Y29ubmVjdGlvbigpLT5nZXRRdWVyeUdyYW1tYXIoKSkiLCJzb3VyY2UiOiI8P3BocFxuXG51c2UgSWxsdW1pbmF0ZVxcU3VwcG9ydFxcRmFjYWRlc1xcREI7XG4gXG4kZXhwcmVzc2lvbiA9IERCOjpyYXcoJ3NlbGVjdCAxJyk7XG4gXG4kc3RyaW5nID0gKHN0cmluZykkZXhwcmVzc2lvbjtcbiJ9

Migrate Laravel DB expression

**Comment by HerringtonDarkholme** [comment]
Rewrite yoda style

https://x.com/hd_nvim/status/1763023957098393817

**Comment by HerringtonDarkholme** [comment]
rewrite object.asign to object spread
```
id: prefer_object_spread
language: javascript
utils:
  first-obj-literal:
    any:
    - pattern: Object.assign({$$$}, $$$)
    - pattern: Object.assign({$$$})
rule: { matches: first-obj-literal, pattern: $ROOT }
rewriters:
- id: object-assign
  rule: { pattern: Object.assign($$$ARGS), matches: first-obj-literal }
  transform:
    MERGED: { rewrite: { rewriters: [object-assign, plain-object, add_ellipsis], source: $$$ARGS, joinBy: '', } }
  fix: '$MERGED'
- id: plain-object
  rule: { pattern: { context: '({$$$FIELDS})', selector: object } }
  transform:
    EXTRACTED: { replace: { source: $$$FIELDS, replace: '^(.+[^,])$', by: '$1,' } }
  fix: $EXTRACTED
- id: add_ellipsis
  rule: {pattern: $A}
  fix: '...$A, '
transform:
  NORMALIZED: { rewrite: { rewriters: [object-assign], source: $ROOT, } }
fix: '{$NORMALIZED}'
```
https://stackoverflow.com/questions/78051829/can-i-reproduce-eslints-prefer-object-spread-rule-using-ast-grep
