### DISCUSSION TITLE
Converting generator expression to list comprehension in Python

### DISCUSSION THREAD

**Discussion by 93578237** [ast-grep/ast-grep#430] [Q&A] [answered]
Hi, I have a following rule:
```
id: join-generator
message: placeholder
severity: error
language: Python
rule:
  pattern: $GEN
  kind: generator_expression
  follows:
    kind: attribute
    has:
      kind: identifier
      pattern: join
fix: "([$GEN])"
```
The rule fix converts `"".join(i for i in ["1"])` to `"".join([(i for i in ["1"])]`.  (should be  `"".join([i for i in ["1"]]`)
Is it possible to get a generator expression without parentheses?

**Comment by HerringtonDarkholme** [comment, marked as answer]
Looks like it is impossible to do it here...
Python generator is very unique in that parentheses are shared by the generator_expression and call expression.
And it is impossible to make a contextual pattern because `($$$A)` is not interpreted as a generator expression.

I think it might need string manipulation to make it work.

Reference: https://github.com/ast-grep/ast-grep/issues/315

**Reply by HerringtonDarkholme** [reply]
Reference: semgrep also has a hard time about Python comprehension https://github.com/returntocorp/semgrep/issues/4499

**Reply by HerringtonDarkholme** [reply]
Comby cannot get it right as well

https://comby.live/index.html#{%22source%22:%22if%20(width%20%3C=%201280%20&&%20height%20%3C=%20800)%20{\n%20%20%20%20return%201;\n}%22,%22match%22:%22if%20(:[var]%20%3C=%20:[rest])%22,%22rule%22:%22where%20true%22,%22rewrite%22:%22var%20matched:%20:[var]\nrest%20matched:%20:[rest]%22,%22language%22:%22.generic%22,%22substitution_kind%22:%22newline_separated%22,%22id%22:0}

**Comment by HerringtonDarkholme** [comment]
![image](https://github.com/ast-grep/ast-grep/assets/2883231/97b795e0-462e-4dab-8372-debf39d2016a)

![image](https://github.com/ast-grep/ast-grep/assets/2883231/990ff37c-830e-4b93-9e4d-f25848352b07)

**Reply by 93578237** [reply]
what is transform? Can't find in docs

**Reply by 93578237** [reply]
does not work for this
```python
''.join(str(i) for i in range(2))
```

**Reply by HerringtonDarkholme** [reply]
Sorry for the confusion. I just pushed the feature to the main branch and it is not available in public release.

It is too experimental to publish it now and I would like to invite users to try it out. 
You can install the main branch by cloning it and `cargo install`. The doc is here.
https://github.com/ast-grep/ast-grep/issues/436

**Reply by 93578237** [reply]
`error: found a virtual manifest at ... instead of a package manifest`

**Reply by HerringtonDarkholme** [reply]
Command should be
cargo install --path crates/cli 

Also new version 0.6.3 is available on crates.io with transform now.

**Reply by 93578237** [reply]
Tried with 0.6.3, same wrong fix for `''.join(str(i) for i in range(2))` -> `"".join([])`

**Reply by HerringtonDarkholme** [reply]
Looks like the rule is wrong. Would you mind paste the rule? The error reporting is not good now 😔. It needs some time debugging

**Reply by 93578237** [reply]
```
id: join-generator
message: placeholder
severity: error
language: Python
rule:
  kind: generator_expression
  pattern: $A
  follows:
    kind: attribute
    has:
      kind: identifier
      pattern: join
transform:
  NEW:
    substring:
      source: $A
      startChar: 1
      endChar: -1
fix: '([$NEW])'
```
