### DISCUSSION TITLE
Can I use regex groups in the fix?

### DISCUSSION THREAD

**Discussion by Lodin** [ast-grep/ast-grep#477] [Q&A] [answered]
I'm trying to replace a part of the variable name, like `__PART_TO_REPLACE__OtherPart` -> `replacedOtherPart`. Is it possible to do? I tried the following YAML, but it does not seem to work.

```yml
rule:
  pattern: $A
  regex: __PART_TO_REPLACE__(.*)
  kind: identifier
fix:
  replaced$1
```

**Comment by HerringtonDarkholme** [comment, marked as answer]
Thanks for trying out ast-grep! 

Using regex group directly in `fix` is not possible. Because we can have multiple `regex` sub-rules in one YAML. It is not clear which group `$1` refers to.

But ast-grep does have a (experimental) workaround.

`transform` is used to manipulate string in a matched variable. Refer to https://github.com/ast-grep/ast-grep/issues/436#issuecomment-1583078804 for more explanation.

```yaml
rule:
  pattern: $A
  regex: __PART_TO_REPLACE__(.*)
  kind: identifier
transform:
  CHANGED:
    replace:
      source: $A
      replace: __PART_TO_REPLACE__(.*)
      by: 'replaced$1'
fix:
  $CHANGED
```

https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6ImphdmFzY3JpcHQiLCJxdWVyeSI6ImNvbnNvbGUubG9nKCRNQVRDSCkiLCJyZXdyaXRlIjoibG9nZ2VyLmxvZygkTUFUQ0gpIiwiY29uZmlnIjoicnVsZTpcbiAgcGF0dGVybjogJEFcbiAgcmVnZXg6IF9fUEFSVF9UT19SRVBMQUNFX18oLiopXG4gIGtpbmQ6IGlkZW50aWZpZXJcbnRyYW5zZm9ybTpcbiAgQ0hBTkdFRDpcbiAgICByZXBsYWNlOlxuICAgICAgc291cmNlOiAkQVxuICAgICAgcmVwbGFjZTogX19QQVJUX1RPX1JFUExBQ0VfXyguKilcbiAgICAgIGJ5OiAncmVwbGFjZWQkMSdcbmZpeDpcbiAgJENIQU5HRUQiLCJzb3VyY2UiOiJ2YXIgX19QQVJUX1RPX1JFUExBQ0VfX2ZvbyA9IDEyMyJ9
