### DISCUSSION TITLE
How would you match jsx returning expressions only?

### DISCUSSION THREAD

**Discussion by skoch13** [ast-grep/ast-grep#654] [Q&A] [answered]
Thank you for the great tool! Imagine we have the following:

```
const FirstComponent = (a) => {
  return <div>123</div>
}

const SecoundComponent = () => (<div>123</div>);

const notAComponent = () => {};
```

What would be the YAML configuration here to match only the components?
Thank you in advance

**Comment by HerringtonDarkholme** [comment, marked as answer]
Hi! Thanks for trying ast-grep.
Matching JSX element in return position isn't trivial! Even eslint-plugin-react uses some heuristics to approximate the matching algorithm.

In ast-grep, you can use the advanced `utils` rule. https://ast-grep.github.io/guide/rule-config/utility-rule.html

I have broken down the rule into self-explanatory sub util rules.

```yaml
utils:
  isFunc:
    any:
      - kind: arrow_function
      - kind: function
      - kind: function_declaration
  isJSX:
    any:
      - kind: jsx_element
      - kind: jsx_fragment
      - kind: parenthesized_expression  # if jsx inside ()
        has:
          matches: isJSX
  hasJSXReturn:
    any:
      - matches: isJSX  # () => <></>
      - kind: statement_block # () => { return <></> }
        has:
          kind: return_statement
          has:
            matches: hasJSXReturn
          stopBy: end
rule:
  matches: isFunc
  has:
    field: body
    matches: hasJSXReturn
```


[See the playground in action](https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6ImphdmFzY3JpcHQiLCJxdWVyeSI6ImNvbnNvbGUubG9nKCRNQVRDSCkiLCJyZXdyaXRlIjoibG9nZ2VyLmxvZygkTUFUQ0gpIiwiY29uZmlnIjoidXRpbHM6XG4gIGlzRnVuYzpcbiAgICBhbnk6XG4gICAgICAtIGtpbmQ6IGFycm93X2Z1bmN0aW9uXG4gICAgICAtIGtpbmQ6IGZ1bmN0aW9uXG4gICAgICAtIGtpbmQ6IGZ1bmN0aW9uX2RlY2xhcmF0aW9uXG4gIGlzSlNYOlxuICAgIGFueTpcbiAgICAgIC0ga2luZDoganN4X2VsZW1lbnRcbiAgICAgIC0ga2luZDoganN4X2ZyYWdtZW50XG4gICAgICAtIGtpbmQ6IHBhcmVudGhlc2l6ZWRfZXhwcmVzc2lvblxuICAgICAgICBoYXM6XG4gICAgICAgICAgbWF0Y2hlczogaXNKU1hcbiAgaGFzSlNYUmV0dXJuOlxuICAgIGFueTpcbiAgICAgIC0gbWF0Y2hlczogaXNKU1hcbiAgICAgIC0ga2luZDogc3RhdGVtZW50X2Jsb2NrXG4gICAgICAgIGhhczpcbiAgICAgICAgICBraW5kOiByZXR1cm5fc3RhdGVtZW50XG4gICAgICAgICAgaGFzOlxuICAgICAgICAgICAgbWF0Y2hlczogaGFzSlNYUmV0dXJuXG4gICAgICAgICAgc3RvcEJ5OiBlbmRcbnJ1bGU6XG4gIG1hdGNoZXM6IGlzRnVuY1xuICBoYXM6XG4gICAgZmllbGQ6IGJvZHlcbiAgICBtYXRjaGVzOiBoYXNKU1hSZXR1cm4iLCJzb3VyY2UiOiJjb25zdCBGaXJzdENvbXBvbmVudCA9IChhKSA9PiB7XG4gIHJldHVybiA8ZGl2PjEyMzwvZGl2PlxufVxuXG5jb25zdCBTZWNvdW5kQ29tcG9uZW50ID0gKCkgPT4gKDxkaXY+MTIzPC9kaXY+KTtcblxuY29uc3Qgbm90QUNvbXBvbmVudCA9ICgpID0+IHt9O1xuXG5jb25zdCBNID0gKCkgPT4gPGRpdj48L2Rpdj5cblxuZnVuY3Rpb24gdGVzdCgpIHtcblxufVxuXG5jb25zdCB0ZXN0ID0gZnVuY3Rpb24gdGV0ICh7Ym9vbH0pIHtcbiAgaWYgKGJvb2wpIHtcbiAgICByZXR1cm4gPGRpdj4xMjM8L2Rpdj5cbiAgfSBlbHNlIHtcbiAgICByZXR1cm4gPD4xMjM8Lz5cbiAgfVxufSJ9)

Hope this help!
