### DISCUSSION TITLE
Match pair including ","

### DISCUSSION THREAD

**Discussion by boidolr** [ast-grep/ast-grep#746] [Q&A] [answered]
I am trying to remove an entry with a certain key in dictionaries. While matching the pair works, this leaves the trailing (or preceding) ",", leading to invalid code. Is there a way to match both the pair and the ","?
I feel there should be a way to target the preceding and target pairs, and replace them with the unrelated pair, but did not manage to set that up yet. Any help is appreciated.

Example:

```python
obj = {
  "unrelated":  val,
  "target": "something",
  "also": "unrelated"
}
```
Matches pair, not including ",":
```yaml
language: python
rule:
  kind: pair
  has:
    field: key
    regex: "target"
fix: ""
```
Does not match at all:
```yaml
language: python
rule:
  pattern: "$A: $B, $C: $D"
constraints:
  C:
    regex: "target"
fix: "$A: $B"
```

Playground link: [here](https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6InB5dGhvbiIsInF1ZXJ5IjoiY29uc29sZS5sb2coJE1BVENIKSIsInJld3JpdGUiOiJsb2dnZXIubG9nKCRNQVRDSCkiLCJjb25maWciOiJsYW5ndWFnZTogcHl0aG9uXG5ydWxlOlxuICBraW5kOiBwYWlyXG4gIGhhczpcbiAgICBmaWVsZDoga2V5XG4gICAgcmVnZXg6IFwidGFyZ2V0XCJcbmZpeDogXCJcIlxuIyBydWxlOlxuIyAgIHBhdHRlcm46IFwiJEE6ICRCLCAkQzogJERcIlxuIyBjb25zdHJhaW50czpcbiMgICBDOlxuIyAgICAgcmVnZXg6IFwidGFyZ2V0XCJcbiMgZml4OiBcIiRBOiAkQlwiXG4iLCJzb3VyY2UiOiJvYmogPSB7XG4gIFwidW5yZWxhdGVkXCI6ICB2YWwsXG4gIFwidGFyZ2V0XCI6IFwic29tZXRoaW5nXCIsXG4gIFwiYWxzb1wiOiBcInVucmVsYXRlZFwiXG59In0=)
