### DISCUSSION TITLE
Ordering woes when matching siblings with varargs

### DISCUSSION THREAD

**Discussion by aisamu** [ast-grep/ast-grep#807] [Q&A]
I'm having some trouble writing a rule that proposes "hoisting" expressions to be shared via a common ancestor.

Individually, the pieces work correctly. When assembled into the final rule, an ordering issue pops up.

## Goal

The target language is Clojure, a Lisp.

We want to find expressions that contain two equivalent accessors (i.e. same property, same target) and propose lifting them to a containing expression. This way, if the lookup is expensive, we do it only once and share the result.

For example, the following code:

```clojure
(def person (hash-map ,,,))

(do
  (something (get person :first-name))
  ,,,
  (do
    (something-else (get person :first-name))))
```

Could be rewritten as:

```clojure
(def person (hash-map ,,,))

(let [name (get person :first-name)]
  (something name)
  ,,,
  (do
    (something-else name)))
```

To make things slightly more interesting, Clojure has two "equivalent" ways to lookup values:

```clojure
(let [person (hash-map ,,,)]
  ;; Both will read the `:name` key from the `person` object
  (get person :name "missing!")
  (:name person "missing!"))
```

## Context

Since `clojure` is not supported out of the box, we must explicitly configure it as a custom language:

```yaml
ruleDirs:
  - ./rules
customLanguages:
  clojure:
    # Emacs already has a compiled parser for clojure!
    libraryPath: /Users/aisamu/.doom.emacs.d/.local/straight/build-29.1/tree-sitter-langs/bin/clojure.dylib
    extensions: [clj, cljs, cljc]
```

### Example file/expression

Unless explicitly noted, all scans will be executed against the following file/excerpt:

```clojure
(let [level 0]
  (let [level 1]
    (let [level 2]
      (:some-key a-map :missing)
      (:some-key a-map)))
  (get a-map :some-key :missing))

(get a-map :some-key :missing)
```

<details><summary> Since this is a Lisp, the resulting tree is comparatively straightforward! </summary>

```shell
source (0, 0) - (8, 0)
  list_lit (0, 0) - (5, 33)
    ( (0, 0) - (0, 1) "("
    sym_lit (0, 1) - (0, 4)
      sym_name (0, 1) - (0, 4) "let"
    vec_lit (0, 5) - (0, 14)
      [ (0, 5) - (0, 6) "["
      sym_lit (0, 6) - (0, 11)
        sym_name (0, 6) - (0, 11) "level"
      num_lit (0, 12) - (0, 13) "0"
      ] (0, 13) - (0, 14) "]"
    list_lit (1, 2) - (4, 25)
      ( (1, 2) - (1, 3) "("
      sym_lit (1, 3) - (1, 6)
        sym_name (1, 3) - (1, 6) "let"
      vec_lit (1, 7) - (1, 16)
        [ (1, 7) - (1, 8) "["
        sym_lit (1, 8) - (1, 13)
          sym_name (1, 8) - (1, 13) "level"
        num_lit (1, 14) - (1, 15) "1"
        ] (1, 15) - (1, 16) "]"
      list_lit (2, 4) - (4, 24)
        ( (2, 4) - (2, 5) "("
        sym_lit (2, 5) - (2, 8)
          sym_name (2, 5) - (2, 8) "let"
        vec_lit (2, 9) - (2, 18)
          [ (2, 9) - (2, 10) "["
          sym_lit (2, 10) - (2, 15)
            sym_name (2, 10) - (2, 15) "level"
          num_lit (2, 16) - (2, 17) "2"
          ] (2, 17) - (2, 18) "]"
        list_lit (3, 6) - (3, 32)
          ( (3, 6) - (3, 7) "("
          kwd_lit (3, 7) - (3, 16)
            : (3, 7) - (3, 8) ":"
            kwd_name (3, 8) - (3, 16) "some-key"
          sym_lit (3, 17) - (3, 22)
            sym_name (3, 17) - (3, 22) "a-map"
          kwd_lit (3, 23) - (3, 31)
            : (3, 23) - (3, 24) ":"
            kwd_name (3, 24) - (3, 31) "missing"
          ) (3, 31) - (3, 32) ")"
        list_lit (4, 6) - (4, 23)
          ( (4, 6) - (4, 7) "("
          kwd_lit (4, 7) - (4, 16)
            : (4, 7) - (4, 8) ":"
            kwd_name (4, 8) - (4, 16) "some-key"
          sym_lit (4, 17) - (4, 22)
            sym_name (4, 17) - (4, 22) "a-map"
          ) (4, 22) - (4, 23) ")"
        ) (4, 23) - (4, 24) ")"
      ) (4, 24) - (4, 25) ")"
    list_lit (5, 2) - (5, 32)
      ( (5, 2) - (5, 3) "("
      sym_lit (5, 3) - (5, 6)
        sym_name (5, 3) - (5, 6) "get"
      sym_lit (5, 7) - (5, 12)
        sym_name (5, 7) - (5, 12) "a-map"
      kwd_lit (5, 13) - (5, 22)
        : (5, 13) - (5, 14) ":"
        kwd_name (5, 14) - (5, 22) "some-key"
      kwd_lit (5, 23) - (5, 31)
        : (5, 23) - (5, 24) ":"
        kwd_name (5, 24) - (5, 31) "missing"
      ) (5, 31) - (5, 32) ")"
    ) (5, 32) - (5, 33) ")"
  list_lit (7, 0) - (7, 30)
    ( (7, 0) - (7, 1) "("
    sym_lit (7, 1) - (7, 4)
      sym_name (7, 1) - (7, 4) "get"
    sym_lit (7, 5) - (7, 10)
      sym_name (7, 5) - (7, 10) "a-map"
    kwd_lit (7, 11) - (7, 20)
      : (7, 11) - (7, 12) ":"
      kwd_name (7, 12) - (7, 20) "some-key"
    kwd_lit (7, 21) - (7, 29)
      : (7, 21) - (7, 22) ":"
      kwd_name (7, 22) - (7, 29) "missing"
    ) (7, 29) - (7, 30) ")"
```

</details>

### Accessor helper

The accessor variants can be represented by the following helper:

```yaml
utils:
  is-accessor:
    any:
      - pattern: "(:$KEY $FROM $$$DEFAULT)"
      - pattern: "(get $FROM :$KEY $$$DEFAULT)"
```

As a sanity check, we can verify that the helper matches all the accessors on the example file:

```yaml
rule:
  kind: list_lit
  matches: is-accessor
```

```
help[sanity-check]: 
  ┌─ ./example.clj:4:7
  │
4 │       (:some-key a-map :missing)
  │       ^^^^^^^^^^^^^^^^^^^^^^^^^^

help[sanity-check]: 
  ┌─ ./example.clj:5:7
  │
5 │       (:some-key a-map)))
  │       ^^^^^^^^^^^^^^^^^

help[sanity-check]: 
  ┌─ ./example.clj:6:3
  │
6 │   (get a-map :some-key :missing))
  │   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

help[sanity-check]: 
  ┌─ ./example.clj:8:1
  │
8 │ (get a-map :some-key :missing)
  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

```

### Hoisting requires a parent

We're currently matching all the accessors, including the last one. But that one has has no parent: since it's already at the top level, there'd be nowhere to hoist it to.

We can address this by restricting our matches to be `inside` another list:

```diff
--- ./rules/sanity-check.yml	2023-12-22 21:11:00
+++ ./rules/sanity-check-inside.yml	2023-12-22 21:11:00
@@ -8,3 +8,6 @@
 rule:
   kind: list_lit
   matches: is-accessor
+  inside:
+    kind: list_lit
+    stopBy: end
```

This works as expected, and the last accessor is no longer matched!

```
help[sanity-check]: 
  ┌─ ./example.clj:4:7
  │  
3 │ ╭     (let [level 2]
4 │ │       (:some-key a-map :missing)
  │ │       ^^^^^^^^^^^^^^^^^^^^^^^^^^
5 │ │       (:some-key a-map)))
  │ ╰────────────────────────'

help[sanity-check]: 
  ┌─ ./example.clj:5:7
  │  
3 │ ╭     (let [level 2]
4 │ │       (:some-key a-map :missing)
5 │ │       (:some-key a-map)))
  │ │       ^^^^^^^^^^^^^^^^^
  │ ╰────────────────────────'

help[sanity-check]: 
  ┌─ ./example.clj:6:3
  │  
1 │ ╭ (let [level 0]
2 │ │   (let [level 1]
3 │ │     (let [level 2]
4 │ │       (:some-key a-map :missing)
5 │ │       (:some-key a-map)))
6 │ │   (get a-map :some-key :missing))
  │ │   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  │ ╰─────────────────────────────────'

```

It also reveals an interesting detail: **ast-grep chooses the closest possible candidate as the container, and only that**. `(:some-key a-map)` is contained by levels 0, 1, and 2, but only 2 was presented.

### Matching same-level siblings

Going back to our goal, what we really care about is finding **two** accessors that share a common ancestor.

The simplest case is one with sibling accessors that are on the same level:

```clojure
(let [level 0]
  (:some-key a-map)
  (println "irrelevant expression between matches")
  (get a-map :some-key)

  (:some-key a-map :missing)
  (println "irrelevant expression between matches")
  (get a-map :some-key :missing))
```

This can be matched by the following rule:

```yaml
id: siblings
language: clojure
utils:
  is-accessor:
    any:
      - pattern: "(:$KEY $FROM $$$DEFAULT)"
      - pattern: "(get $FROM :$KEY $$$DEFAULT)"
rule:
  kind: list_lit
  any:
    - matches: is-accessor
      follows:
        matches: is-accessor
        stopBy: end
    - matches: is-accessor
      precedes:
        matches: is-accessor
        stopBy: end
  inside:
    kind: list_lit
    stopBy: end
```

```
help[siblings]: 
  ┌─ ./example-siblings.clj:4:3
  │  
1 │ ╭ (let [level 0]
2 │ │   (:some-key a-map)
  │ │   -----------------
3 │ │   (println "irrelevant expression between matches")
4 │ │   (get a-map :some-key)
  │ │   ^^^^^^^^^^^^^^^^^^^^^
  · │
7 │ │   (println "irrelevant expression between matches")
8 │ │   (get a-map :some-key :missing))
  │ ╰─────────────────────────────────'

help[siblings]: 
  ┌─ ./example-siblings.clj:8:3
  │  
1 │ ╭ (let [level 0]
2 │ │   (:some-key a-map)
3 │ │   (println "irrelevant expression between matches")
4 │ │   (get a-map :some-key)
5 │ │ 
6 │ │   (:some-key a-map :missing)
  │ │   --------------------------
7 │ │   (println "irrelevant expression between matches")
8 │ │   (get a-map :some-key :missing))
  │ │   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  │ ╰─────────────────────────────────'

```

Even in the face of interfering `println` expressions, we can see that the correct pairs were picked (i.e. not mixing expressions with vs. without defaults)!

Unfortunately, this stop working completely when we reorder the expressions:

```clojure
(let [level 0]
  (:some-key a-map)
  (:some-key a-map :missing)
  (get a-map :some-key)
  (get a-map :some-key :missing))
```

```diff
--- ./example-siblings.clj	2023-12-22 21:11:00
+++ example-siblings-reordered.clj	2023-12-22 21:11:00
@@ -1,8 +1,5 @@
 (let [level 0]
   (:some-key a-map)
-  (println "irrelevant expression between matches")
-  (get a-map :some-key)
-
   (:some-key a-map :missing)
-  (println "irrelevant expression between matches")
+  (get a-map :some-key)
   (get a-map :some-key :missing))
```

```

```

(i.e. **No results returned from a scan.**)

It looks like the rule matches the `$$$DEFAULT`-less selector against one with a default (i.e. with `:missing`), and bails without trying the next one. Is my understanding correct?

1.  Attempt: no varargs

    If we explicitly model the two accessors without varargs, things improve slightly:
    
    ```diff
    --- ./rules/siblings.yml	2023-12-22 21:11:00
    +++ ./rules/siblings-no-varargs.yml	2023-12-22 21:11:00
    @@ -3,8 +3,12 @@
     utils:
       is-accessor:
         any:
    -      - pattern: "(:$KEY $FROM $$$DEFAULT)"
    -      - pattern: "(get $FROM :$KEY $$$DEFAULT)"
    +      - any:
    +        - pattern: "(:$KEY $FROM)"
    +        - pattern: "(get $FROM :$KEY)"
    +      - any:
    +        - pattern: "(:$KEY $FROM $DEFAULT)"
    +        - pattern: "(get $FROM :$KEY $DEFAULT)"
     rule:
       kind: list_lit
       any:
    ```
    
    ```
    help[siblings]: 
      ┌─ ./example-siblings-reordered.clj:4:3
      │  
    1 │ ╭ (let [level 0]
    2 │ │   (:some-key a-map)
      │ │   -----------------
    3 │ │   (:some-key a-map :missing)
    4 │ │   (get a-map :some-key)
      │ │   ^^^^^^^^^^^^^^^^^^^^^
    5 │ │   (get a-map :some-key :missing))
      │ ╰─────────────────────────────────'
    
    ```
    
    We correctly matched one of the pairs! Unfortunately, that was as far as I could get, and there's still one missing.
    
    Any help is greatly appreciated!
    
    By the way, I'm baffled that I got this far **on my first try** - this is a tremendous tool! Thanks for taking the time to write it!

**Comment by HerringtonDarkholme** [comment]
Hi, thanks for the detailed report! I will look at it tomorrow :)

**Comment by HerringtonDarkholme** [comment]
This is my minimal reproduction:


```yml
id: siblings
language: clojure
utils:
  is-accessor:
    pattern: "(:$KEY $FROM $$$DEFAULT)"
rule:
  matches: is-accessor
  # pattern: "(:$KEY $FROM $$$DEFAULT)"
  follows:
    matches: is-accessor
    # pattern: "(:$KEY $FROM $$$DEFAULT)"
    stopBy: end
```

matched against the file

```clojure
(let [level 0]
  (:some-key a-map)
  (:some-key a-map :missing)
  (:some-key a-map)
)
```

If you toggle between `pattern` rule and `matches` rule, you will see different results. 

* `matches` will produce no result
* `pattern` will produce results as expected

**Reply by HerringtonDarkholme** [reply]
And even more curiously, remove the `$$$DEFAULT` from pattern will make `matches` work again.

**Reply by HerringtonDarkholme** [reply]
I can reproduce it with JavaScript.

https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6ImphdmFzY3JpcHQiLCJxdWVyeSI6InZhciAkQSA9ICRCIiwicmV3cml0ZSI6ImZmZmYiLCJjb25maWciOiJpZDogc2libGluZ1xubGFuZ3VhZ2U6IGphdmFzY3JpcHRcbnV0aWxzOlxuICB1dGlscGF0OlxuICAgIHBhdHRlcm46ICckQSgkJCRCKTsnXG5ydWxlOlxuICBtYXRjaGVzOiB1dGlscGF0XG4gIGZvbGxvd3M6XG4gICAgbWF0Y2hlczogdXRpbHBhdFxuICAgIHN0b3BCeTogZW5kIiwic291cmNlIjoiYSgpO1xuYSgxMjMpO1xuYSgpO1xuYSgxMjMpOyJ9

**Reply by HerringtonDarkholme** [reply]
@aisamu This is caused by undefined matching order of rules.

Consider 

```yml
rule:
  matches: utilpat
  follows:
    matches: utilpat
    stopBy: end
```

is effectively

```yml
rule:
  all:
    - follows:
        matches: is-accessor
        stopBy: end
    - matches: is-accessor
```

The program will first match follows rule then matches rule. So there is no matching at all.

**Comment by HerringtonDarkholme** [comment]
As answered in other replies, specifying the rule order by using all can fix the problem

```yml
id: siblings
language: clojure
utils:
  is-accessor:
    any:
      - pattern: "(:$KEY $FROM $$$DEFAULT)"
      - pattern: "(get $FROM :$KEY $$$DEFAULT)"
rule:
  all:
    - kind: list_lit
    - matches: is-accessor
    - any:
        - follows:
            matches: is-accessor
            stopBy: end
        - precedes:
            matches: is-accessor
            stopBy: end
    - inside:
        kind: list_lit
        stopBy: end

```
