### ISSUE TITLE
[bug] `fn $FUNC($$$ARGS) { $$$ }` does not match the function item of Rust

### ISSUE THREAD

**Issue by kdy1** [ast-grep/ast-grep#1056]
# ⏯ Playground Link

[Playground link with relevant code](https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6InJ1c3QiLCJxdWVyeSI6ImZuICRGVU5DKCQkJEFSR1MpIHsgJCQkIH0iLCJyZXdyaXRlIjoiIiwiY29uZmlnIjoiaWQ6IHVwZGF0ZS1mdW5jdGlvbi1wYXJhbWV0ZXJzXG5sYW5ndWFnZTogcnVzdFxucnVsZTpcbiAgcGF0dGVybjogJ2ZuICRGVU5DKCQkJEFSR1MpIHsgJCQkIH0nXG4gICIsInNvdXJjZSI6IiNbdHVyYm9fdGFza3M6OmZ1bmN0aW9uXVxuYXN5bmMgZm4gcmVhZChuYW1lOiBTdHJpbmcpIC0+IFJlc3VsdDxWYzxPcHRpb248U3RyaW5nPj4+IHtcbiAgICBcbn1cbiJ9)

# 💻 Code

Code:

```rust
#[turbo_tasks::function]
async fn read(name: String) -> Result<Vc<Option<String>>> {
    
}
```

Pattern:

```yml
id: update-function-parameters
language: rust
rule:
  pattern: 'fn $FUNC($$$ARGS) { $$$ }'
```

or `pattern = fn $FUNC($$$ARGS) { $$$ }` in the playground

# 🙁 Actual behavior

It didn't match any function.

# 🙂 Expected behavior

It should match all functions

**Comment by HerringtonDarkholme** [comment]
Thanks for the report!

There are two things in the repro:

1. `fn $FUNC($$$ARGS) { $$$ }` does not have a `return` type. So it does not match the `fn read(name: String) -> Result<Vc<Option<String>>>` because the latter has a return type. This is _expected_. 

I recommend using `any` to combine these two cases.
```yaml
id: update-function-parameters
language: rust
rule:
  any:
  - pattern: 'fn $FUNC($$$ARGS) { $$$ }'
  - pattern: 'fn $FUNC($$$ARGS) -> $RET { $$$ }'
```

2. However, the above YAML still does not match `async` function.  This is _unexpected_. Because async is not an AST node, the pattern query does not specify the keyword.  Both async and non-async should be matched.

I will investigate the latter case. Meanwhile this is the work around

```YAML
id: update-function-parameters
language: rust
rule:
  kind: function_item
  has:
    kind: parameters
    pattern: $PARAMS
  
```

https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6InJ1c3QiLCJxdWVyeSI6ImZuICRGVU5DKCQkJEFSR1MpIC0+ICRSRVQgeyAgJCQkIH0iLCJyZXdyaXRlIjoiIiwiY29uZmlnIjoiaWQ6IHVwZGF0ZS1mdW5jdGlvbi1wYXJhbWV0ZXJzXG5sYW5ndWFnZTogcnVzdFxucnVsZTpcbiAga2luZDogZnVuY3Rpb25faXRlbVxuICBoYXM6XG4gICAga2luZDogcGFyYW1ldGVyc1xuICAgIHBhdHRlcm46ICRQQVJBTVNcbiAgIiwic291cmNlIjoiI1t0dXJib190YXNrczo6ZnVuY3Rpb25dXG5hc3luYyBmbiByZWFkKG5hbWU6IFN0cmluZykgLT4gUmVzdWx0PFZjPE9wdGlvbjxTdHJpbmc+Pj4ge1xuICAgIFxufVxuIn0=
