### ISSUE TITLE
Allow to use meta variable captured outside of rewrite rule inside the rewriter

### ISSUE THREAD

**Issue by ptorbynskyy** [ast-grep/ast-grep#1072]
# ⭐ Suggestion
I would like to be able to use meta variable that captured outside of rewrite rule inside it.

# 💻 Use Cases
Here is [my case](https://shorturl.at/ktGR9)
I tried to replace spread with set of calls.

Source:
```
createService(
    ...c.resolve("A", "B", "С")
)
```
Goal:
```
createService(
    c.resolve("A"),
    c.resolve("B"),
    c.resolve("C")
)
```

Rule:
```
# YAML Rule is more powerful!
# https://ast-grep.github.io/guide/rule-config.html#rule
rule:
   kind: spread_element
   has: 
      kind: call_expression
      pattern: $NAME.resolve($$$IDENTS)
rewriters:
  - id: rewrite-identifer
    rule:
      pattern: $IDENT
      kind: string
    fix: $NAME.resolve($IDENT)
transform:
  RESOLVES:
    rewrite:
      rewriters: [rewrite-identifer]
      source: $$$IDENTS
      joinBy: "\n"
fix: $RESOLVES
```

<img width="1703" alt="image" src="https://github.com/ast-grep/ast-grep/assets/95681814/2b12d431-3873-42d4-91a5-57976d52ed60">

`$NAME` is empty inside the `rewriters`.
I suggest to make external context available. 
 
Additional Links:
 -  [my case](https://shorturl.at/ktGR9)
 - [Discord discussion](https://discord.com/channels/1107749847722889217/1231300626579980389)
