### ISSUE TITLE
[bug] issue in python pattern related to async and await

### ISSUE THREAD

**Issue by ppashakhanloo** [ast-grep/ast-grep#1185]
# ⏯ Playground Link

[Playground link with relevant code](https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6InB5dGhvbiIsInF1ZXJ5IjoiYXN5bmMgZGVmICROQU1FKCRQQVJBTVMpIiwicmV3cml0ZSI6ImRlZiAkTkFNRSgkUEFSQU1TKSIsImNvbmZpZyI6ImlkOiByZW1vdmUtYXN5bmMtZGVmXG5sYW5ndWFnZTogcHl0aG9uXG5ydWxlOlxuICBwYXR0ZXJuOlxuICAgIGNvbnRleHQ6ICdhc3luYyBkZWYgJEZVTkMoJCQkQVJHUyk6ICQkJEJPRFknXG4gICAgc2VsZWN0b3I6IGZ1bmN0aW9uX2RlZmluaXRpb25cbmZpeDogfC1cbiAgZGVmICRGVU5DKCQkJEFSR1MpOlxuICAgICQkJEJPRFlcbi0tLVxuaWQ6IHJlbW92ZS1pbXBvcnRcbmxhbmd1YWdlOiBweXRob25cbnJ1bGU6XG4gIHBhdHRlcm46IGltcG9ydCBhc3luY2lvXG5maXg6ICcnXG4tLS1cbmlkOiBjaGFuZ2UtYXN5bmMtcnVuXG5sYW5ndWFnZTogcHl0aG9uXG5ydWxlOlxuICBwYXR0ZXJuOiBhc3luY2lvLnJ1bigkJCRBUkdTKVxuZml4OiAkJCRBUkdTXG4tLS1cbmlkOiByZW1vdmUtYXdhaXQtY2FsbFxubGFuZ3VhZ2U6IHB5dGhvblxucnVsZTpcbiAgcGF0dGVybjpcbiAgICBzZWxlY3RvcjogYXdhaXRcbiAgICBjb250ZXh0OiAnYXdhaXQgJCQkQ0FMTCdcbmZpeDogJCQkQ0FMTFxuIiwic291cmNlIjoiYXN5bmMgZGVmIG1haW4zKCk6XG4gIGF3YWl0IHNvbWVjYWxsKDEsIDUpXG4ifQ==)

# 💻 Code

Code:

```
async def main3():
  await somecall(1, 5)
```

Pattern:

```yml
id: remove-async-def
language: python
rule:
  pattern:
    context: 'async def $FUNC($$$ARGS): $$$BODY'
    selector: function_definition
fix: |-
  def $FUNC($$$ARGS):
    $$$BODY
---
id: remove-import
language: python
rule:
  pattern: import asyncio
fix: ''
---
id: change-async-run
language: python
rule:
  pattern: asyncio.run($$$ARGS)
fix: $$$ARGS
---
id: remove-await-call
language: python
rule:
  pattern:
    selector: await
    context: 'await $$$CALL'
fix: $$$CALL
```

# 🙁 Actual behavior

```
def main3():
  await somecall(1, 5)
```

# 🙂 Expected behavior
```
def main3():
  somecall(1, 5)
```
