### ISSUE TITLE
[feature] Support utility rules with document separators in same YAML file

### ISSUE THREAD

**Issue by RealLitb** [ast-grep/ast-grep#1219]
# ⭐ Suggestion

I suggest that it would be possible to refer to utility rules that are defined in the same YAML file, but where we use the document separator. See use cases - the given example below says "Rule `dotest-function` is not defined."

# 💻 Use Cases

```
id: dotest-function
language: CPP
rule:
  kind: function_definition
  has:
    kind: function_declarator
    has: 
      kind: qualified_identifier
      regex: ".*::doTest$"
---
id: returnstmt_match
language: CPP
rule:
  kind: return_statement
  inside:
    matches: dotest-function
    stopBy: 
      kind: lambda_expression
fix: "return;"
---
id: returntype_match
language: CPP
rule:
  pattern: bool
  precedes: 
    kind: function_declarator
    inside:
      matches: dotest-function
fix: void
```
