### ISSUE TITLE
[feature] Match comments

### ISSUE THREAD

**Issue by partner-pierre-vande-laar** [ast-grep/ast-grep#1253]
# ⭐ Suggestion

Comments are valuable and should be handled appropriately by a fix / rewrite.
I would like to specify metavariables for comments and use them in the rewrite.

In this proposal, I use `/* $X */` for a mandatory comment
 and `/* $$$X */` for a list of comments (possibly empty).
But alternatives are certainly possible. 

# 💻 Use Cases

For example,
given the rule
```yaml
id: ternary
rule:
  pattern:
if ($C) { /* $$$CBT1 */ $F($$$BEFORE, /* $$$CBT2 */ $VALUE_TRUE /* $$$CAT1 */, $$$AFTER); /* $$$CAT2 */ } else { /* $$$CBF1 */ 
 $F($$$BEFORE, /* $$$CBF2 */ $VALUE_FALSE /* $$$CAFT1 */ , $$$AFTER); /* $$$CAFT2 */ }
fix:
'$f($$$BEFORE, $C ? /* $$$CBT1 */  /* $$$CBT2 */  $VALUE_TRUE /* $$$CAT1 */ /* $$$CAT2 */ : /* $$$CBF1 */  /* $$$CBF2 */ $VALUE_FALSE /* $$$CAF1 */ /* $$$CAF2 */, $$$AFTER);'
```
The following code 
```cpp
   if (i<j) {
    /* i == min(i,j) */
    f(2,i,3);
  } else {
   /* j == min(i,j) */
    f(2,j,3);
  }

   if (i<j) {
    g(i,3,4); /* min == i */
  } else {
    g(j,3,4); /* min == j */
  }

   if (i<j) {
    h(1,2, j /* max == j */,3,4); 
  } else {
    h(1,2, i /* max == i */,3,4);
  }
``` 
should be transformed to
```cpp
 f(2,i<j ? /* i == min(i,j) */ i : /* j == min(i,j) */ j,3);
  
g(i<j ? i /* min == i */ : j /* min == j */,3,4);
 
 h(1,2, i<j ? j /* max == j */ : i /* max == i */,3,4);
```

See also https://github.com/TNO/Rejuvenation-Ada/issues/5
