### ISSUE TITLE
[bug] LSP gets "message" with $MATCH references as is

### ISSUE THREAD

**Issue by powerman** [ast-grep/ast-grep#1271]
# 💻 Code

The actual rule and code are probably not important here.

Code:

```lua
X = 0
Y = X + 0
```

Pattern:

```yml
id: example-math-noop
message: Change to $A. Do not +0 or -0 because it's useless.
severity: info # error, warning, info, hint
language: Lua
rule:
  any:
    - pattern:
        selector: binary_expression
        context: '$_ = $A + 0'
    - pattern:
        selector: binary_expression
        context: '$_ = $A - 0'
# fix: $A
note: |
  Math operation without any effect may be a sign of a bug/typo.
  If it's not a bug then it's recommended to simplify an expression as $A.
```

# 🙁 Actual behavior

Neovim shows LSP diagnostics message as is:
![изображение](https://github.com/ast-grep/ast-grep/assets/1354301/89ea883c-2807-4b33-9bc6-808041d10a4e)

sg shows message with `$A` replaced with match content (as it should be, according to the docs):
```
$ sg scan
note[example-math-noop]: Change to X. Do not +0 or -0 because it's useless.
  ┌─ ./init.lua:6:5
  │
6 │ Y = X + 0
  │     ^^^^^
  │
  = Math operation without any effect may be a sign of a bug/typo.
    If it's not a bug then it's recommended to simplify an expression as $A.
```

# 🙂 Expected behavior

Neovim should show same message: `Change to X. Do not +0 or -0 because it's useless.`.
