### ISSUE TITLE
[bug] LSP does not work when rule has `files:`

### ISSUE THREAD

**Issue by powerman** [ast-grep/ast-grep#1272]
# 💻 Code

Code:

File: `./lua/plugins/init.lua`
```lua
-- [[ Install plugins without complicated configuration ]]
--
--  Use `opts = {}` to force a plugin to be loaded. This is equivalent to:
--    require('Comment').setup({})
return {
    'tpope/vim-sleuth', -- Detect tabstop and shiftwidth automatically.
}
```

Pattern:

```yml
# yaml-language-server: $schema=https://raw.githubusercontent.com/ast-grep/ast-grep/main/schemas/rule.json

id: lazy-plugin-type
message: Add `@type LazySpec` for plugin spec.
severity: hint # error, warning, info, hint
language: Lua
files:
  - './lua/plugins/init.lua'
rule:
  pattern: return { $$$ }
  not:
    follows:
      kind: comment
      regex: '^---@type LazySpec$'

note: |
  Add type annotation for Lazy plugin spec:

    ---@type LazySpec
    return {
```

# 🙁 Actual behavior

CLI works as expected:
![изображение](https://github.com/ast-grep/ast-grep/assets/1354301/d7495317-b821-411f-a313-95432ed83836)
but LSP in `nvim ./lua/plugins/init.lua` does not work:
![изображение](https://github.com/ast-grep/ast-grep/assets/1354301/f6158ac0-29e5-4dcf-90e5-28eeaf72cf4e)

If I remove `files:` section from yml then LSP works too:
![изображение](https://github.com/ast-grep/ast-grep/assets/1354301/76bebe84-26d0-4d15-878e-981da919825c)

# 🙂 Expected behavior

LSP should support `files:` (and `ignores:`) and works the same as the CLI.
