### ISSUE TITLE
[bug] qualified_identifier match in C++ doesn't seem to work?

### ISSUE THREAD

**Issue by arvid-norlander** [ast-grep/ast-grep#1276]
# ⏯ Playground Link

[Playground link with relevant code](https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6ImNwcCIsInF1ZXJ5IjoibV9zcE1hbmFnZXJJbml0IiwicmV3cml0ZSI6Im1fbWFuYWdlckluaXQiLCJjb25maWciOiIjIGFzdC1ncmVwIHJ1bGVcbmlkOiBzaGFyZWRfcHRyXG5sYW5ndWFnZTogY3BwXG5ydWxlOlxuICBwYXR0ZXJuOiBib29zdDo6c2hhcmVkX3B0cjwkVD5cbiAga2luZDogcXVhbGlmaWVkX2lkZW50aWZpZXJcblxuZml4OiAnc3RkOjpzaGFyZWRfcHRyPCRUPidcbiIsInNvdXJjZSI6ImJvb3N0OjpzaGFyZWRfcHRyPFNvbWVUeXBlPElubmVyPj4gc29tZXRoaW5nID0gYm9vc3Q6Om1ha2Vfc2hhcmVkPFNvbWVUeXBlPElubmVyPj4oc29tZSwgYXJncyk7In0=)

# 💻 Code

Code:

```
boost::shared_ptr<SomeType<Inner>> something = boost::make_shared<SomeType<Inner>>(some, args);
```

Pattern:

```yml
# ast-grep rule
id: shared_ptr
language: cpp
rule:
  pattern: boost::shared_ptr<$T>
  kind: qualified_identifier

fix: 'std::shared_ptr<$T>'
```

# 🙁 Actual behavior

Rule doesn't match, even though according to the syntax tree on the playground qualified_identifier should be the right level to match this on. Even more strange: removing the kind doesn't help.

UPDATE: Even more strangely, ast-grep on the command line claims `qualified_identifier` isn't even a valid kind. But removing the kind doesn't make it work there either!

# 🙂 Expected behavior

Rule matches
