### ISSUE TITLE
[bug] ast-grep messes up newlines with C/C++ include directives

### ISSUE THREAD

**Issue by arvid-norlander** [ast-grep/ast-grep#1277]
# ⏯ Playground Link

[Playground link with relevant code](https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6ImNwcCIsInF1ZXJ5IjoibV9zcE1hbmFnZXJJbml0IiwicmV3cml0ZSI6Im1fbWFuYWdlckluaXQiLCJjb25maWciOiIjIGFzdC1ncmVwIHJ1bGVcbmlkOiBpbmNsdWRlc1xubGFuZ3VhZ2U6IGNwcFxucnVsZTpcbiAgcGF0dGVybjogXCIjaW5jbHVkZSA8Ym9vc3QvbWFrZV9zaGFyZWQuaHBwPlwiXG4gIGtpbmQ6IHByZXByb2NfaW5jbHVkZVxuXG5maXg6IFwiI2luY2x1ZGUgPG1lbW9yeT5cIlxuIiwic291cmNlIjoiXG4jaW5jbHVkZSA8Ym9vc3QvbWFrZV9zaGFyZWQuaHBwPlxuI2luY2x1ZGUgPGJvb3N0L3Njb3BlZF9hcnJheS5ocHA+XG4jaW5jbHVkZSA8b3BlbnNzbC9ldnAuaD5cbiNpbmNsdWRlIDxvcGVuc3NsL3JzYS5oPiJ9)

# 💻 Code

Code:

```c++
#include <boost/make_shared.hpp>
#include <boost/scoped_array.hpp>
#include <openssl/evp.h>
#include <openssl/rsa.h>
```

Pattern:

```yml
# ast-grep rule
id: includes
language: cpp
rule:
  pattern: "#include <boost/make_shared.hpp>"
  kind: preproc_include

fix: "#include <memory>"
```

# 🙁 Actual behavior

```diff
-#include <boost/make_shared.hpp>
-#include <boost/scoped_array.hpp>
+#include <memory>#include <boost/scoped_array.hpp>
#include <openssl/evp.h>
#include <openssl/rsa.h>
```

What on earth is going on with the newlines here? 

# 🙂 Expected behavior

```diff
-#include <boost/make_shared.hpp>
+#include <memory>
#include <boost/scoped_array.hpp>
#include <openssl/evp.h>
#include <openssl/rsa.h>
```

This is what I would expect

**Comment by arvid-norlander** [comment]
I found a workaround, though it still doesn't make sense to me why this is needed (as usually ast-grep doesn't seem to gobble up newlines like this):

```yml
# ast-grep rule
id: includes
language: cpp
rule:
  any:
    - pattern: "#include <boost/shared_ptr.hpp>"
    - pattern: "#include <boost/make_shared.hpp>"
  kind: preproc_include

fix: "#include <memory>\n"
```
