### ISSUE TITLE
add embedded language section in custom language setting

### ISSUE THREAD

**Issue by HerringtonDarkholme** [ast-grep/ast-grep#1309]
# Background
We want to support embedded language/injected language in ast-grep. One example is searching JS code in HTML, which is implemented in ast-grep-language crate. We want to extend this to more scenarios. Custom language can also be injected into existing languages like injecting graphQL in JavaScript.

# Design Goal 
1. Specify language injection via ast-grep rule. Content range and language should be specified by meta var.
2. Add ad-hoc queries to existing language like JS/TS/HTML
3. Add queries to custom language like markdown

# Notable Usage Example
* searching CSS in JS https://[styled-components](https://styled-components.com/).com/
* searching Vue in TS/JS https://vue-vine.dev/
* searching GraphQL in TS/JS https://relay.dev/
* searching XPath in Py/Java https://www.selenium.dev/

# Detailed API

The term injection comes from tree-sitter. It means a language can be injected into another language's documents.

## Language Injection Specification
Since a language can be injected into different host languages, we need a list of specifications.
One specification should include the injected language, the host language, the selecting rule of the injected region and the language.
```
languageInjections:
- hostLanguage: HTML
  injectableLanguages: [js, ts, tsx, coffee]
  rule:
     # ast-grep rule
    pattern: <script lang=$LANG>$CONTENT</script>
  language: $A
```
