### ISSUE TITLE
[bug] LSP propose code action "Fix with ast-grep" on every line

### ISSUE THREAD

**Issue by powerman** [ast-grep/ast-grep#1327]
# 🙁 Actual behavior

I'm using Neovim, but this issue may be actual for any IDE.
The problem is ast-grep LSP propose code action "Fix with ast-grep" on every line of any file (of supported by ast-grep file types). This happens without any rules, all we need to trigger this behaviour is to setup ast-grep.

```
$ mkdir ~/tmp/ast-grep-lsp-bug
$ cd ~tmp/ast-grep-lsp-bug
$ sg new
No sgconfig.yml found. Creating a new ast-grep project...
> Where do you want to have your rules? rules
> Do you want to create rule tests? Yes
> Where do you want to have your tests? rule-tests
> Do you want to create folder for utility rules? Yes
> Where do you want to have your utilities? utils
Your new ast-grep project has been created!
$ vi tmp.html
:lua vim.lsp.buf.code_action()
```
![изображение](https://github.com/user-attachments/assets/5efcc269-fa41-4822-a24d-3ccd5acfd580)

Minimal Neovim config to reproduce probably won't actually be "minimal" and I've no idea do you use Neovim at all, so probably LSP logs will be more useful for debugging this issue:
[lsp.log](https://github.com/user-attachments/files/16266586/lsp.log)

# 🙂 Expected behavior

LSP code action should be provided only for lines where ast-grep has detected some issues.

**Comment by HerringtonDarkholme** [comment]
Thanks for the report, I will fix it soon.

**Comment by powerman** [comment]
I've just tested latest master. While this issue is fixed, there are few related ones.

Just for the reference, here is rule I use (while working on Neovim config):
```yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/ast-grep/ast-grep/main/schemas/rule.json

id: lazy-plugin-type
message: Add `@type LazySpec` for plugin spec.
severity: hint # error, warning, info, hint
language: Lua
files:
  - './lua/plugins/*.lua'

rule:
  pattern: $SPEC
  all:
    - pattern: return { $$$ }
    - not:
        follows:
          kind: comment
          regex: '^---@type LazySpec$'
    - not:
        inside:
          kind: block
          stopBy: end

fix: |-
  ---@type LazySpec
  $SPEC

note: |-
  Add type annotation for Lazy plugin spec:

    ---@type LazySpec
    return {

  You may also need to add this somewhere above:

    ---@module 'lazy'
```

Here is what's going on when I open file in Neovim:
![изображение](https://github.com/user-attachments/assets/903ea126-d6e8-49fd-8be4-e147268c7742)

As you can see, diagnostic message is shown on wrong line (I've an autocmd which triggers showing diagnostics for a line under cursor, so this message is for cursor's line, not a line with `return`). It turns out this diagnostic message is shown on every line inside that `return{…}` block. Sure, the whole block matches a pattern, but diagnostic is reported on concrete line (first one, with `return` itself) so probably code action should also be available only on that line. Not sure is this a bug on intended behaviour - both cases makes some sense.

Next, it looks like there is some race.
Sometimes when I ask for code action on this line (inside return block) I got this (and Fix action **does not work**):
![изображение](https://github.com/user-attachments/assets/45216458-c9f6-44a8-8875-08bc460da84f)
Sometimes in exactly same case (start Neovim, wait a bit until `luals` loads workspace, request for available code actions) I got this (and Fix action **does work**):
![изображение](https://github.com/user-attachments/assets/b96f901e-3352-4189-8e7f-5d9378753d2f)

The last and least important issue is name of code action - it probably should be `Fix "lazy-plugin-type" with ast-grep` instead of ```Fix `Some(String("lazy-plugin-type"))` with ast-grep```.
