### ISSUE TITLE
[feature] using meta vars inside "message" field of rules after meta var transformation

### ISSUE THREAD

**Issue by AraCoders** [ast-grep/ast-grep#1366]
First of all, thanks for the awesome and incredible tool, i really appreciate your work <3
# ⭐ Suggestion

in each YAML rule there's a message field, which is displayed if you run the tool like this:
ast-grep scan --report-style short --rule ./abc.yaml ./sourcecode/
i use this regularly to extract info from my codebase 
 if i used any rule it will work normally and the meta var gets displayed normally. 
However, when i tried today the "transform" option, to change the meta var using regex, i noticed that only the "fix" option work, (i.e. you can rewrite code normally), however if you tried to use the new meta var after transform in the "message" field you will get empty message.

```yaml
id: test-rule
language: js

rule:
  kind: string
  pattern: $ARG

#doing any transformation
transform:
  TEST:
    replace:
      replace: 'a'
      by: 'b'
      source: $ARG

message: $TEST
```

# 💻 Use Cases

extracting specific info from source code using the rules
