### ISSUE TITLE
[feature] Enable `field` in `any` and `all` when those are in `inside` or `has`

### ISSUE THREAD

**Issue by etiennebacher** [ast-grep/ast-grep#1383]
# ⭐ Suggestion

In the docs, it is written that "In ast-grep, field can be specified in two relational rules: has and inside". Sometimes it would be useful to use `field` in an `any` that is itself in `inside` for instance:
```
rule:
  kind: string
  inside:
    any:
      - kind: pair
        field: key
      - kind: identifier # random stuff
```
Currently, this doesn't work (https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6ImphdmFzY3JpcHQiLCJxdWVyeSI6ImNvbnNvbGUubG9nKCRNQVRDSCkiLCJyZXdyaXRlIjoibG9nZ2VyLmxvZygkTUFUQ0gpIiwic3RyaWN0bmVzcyI6InNtYXJ0Iiwic2VsZWN0b3IiOiIiLCJjb25maWciOiJydWxlOlxuICBraW5kOiBzdHJpbmdcbiAgaW5zaWRlOlxuICAgIGFueTpcbiAgICAgIC0ga2luZDogcGFpclxuICAgICAgICBmaWVsZDoga2V5XG4gICAgICAtIGtpbmQ6IGlkZW50aWZpZXJcbiAgICAgICAgIiwic291cmNlIjoidmFyIGEgPSB7XG4gICdrZXknOiAndmFsdWUnXG59In0=)

# 💻 Use Cases

A workaround would be to invert the `inside` and `any`:
```
rule:
  kind: string
  any:
    - inside: {kind: pair, field: key}
    - inside: {kind: identifier}
```
but this can conflict with other rules passed in a "top-level" `any`. For readability, I think it's also better to keep the `inside > any > rule` order rather than the `any > inside > rule`.
