### ISSUE TITLE
[bug] Constraints are not respected in nested/not patterns

### ISSUE THREAD

**Issue by kam193** [ast-grep/ast-grep#1401]
# ⏯ Playground Link

[Playground link with relevant code](https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6InB5dGhvbiIsInF1ZXJ5IjoiY29uc29sZS5sb2coJE1BVENIKSIsInJld3JpdGUiOiJsb2dnZXIubG9nKCRNQVRDSCkiLCJzdHJpY3RuZXNzIjoic21hcnQiLCJzZWxlY3RvciI6IiIsImNvbmZpZyI6ImlkOiBweXRob24tc3RhdGljLWV4dHJhY3QtZXZhbFxubWVzc2FnZTogRXh0cmFjdCBjb2RlIGV4ZWN1dGVkIGJ5IGV2YWxcbmxhbmd1YWdlOiBQeXRob25cbnJ1bGU6XG4gIGFsbDpcbiAgICAtIHBhdHRlcm46IGV2YWwoJERBVEEpXG4gICAgLSBub3Q6XG4gICAgICAgIHBhdHRlcm46IGV2YWwoJEVYRUMpXG4gICAgICAgICMgaGFzOlxuICAgICAgICAjICAgc3RvcEJ5OiBlbmRcbiAgICAgICAgIyAgIHJlZ2V4OiBcIihbYidcXFwiXSspZXhlYyhbYidcXFwiXSspXCJcbiAgICAgICAgIyAgIGtpbmQ6IHN0cmluZ1xuXG5jb25zdHJhaW50czpcbiAgREFUQTpcbiAgICBraW5kOiBzdHJpbmdcbiAgIyBJZiByZXBsYWNlIHRoaXMgY29uc3RyYWludCB3aXRoIHRoZSBjb21tZW50ZWQgXCJoYXNcIiBwYXR0ZXJuLCBpdCB3b3Jrc1xuICBFWEVDOlxuICAgIHJlZ2V4OiBcIihbYidcXFwiXSspZXhlYyhbYidcXFwiXSspXCJcbiAgICBraW5kOiBzdHJpbmdcblxuZml4OiAkREFUQVxuIiwic291cmNlIjoiIyBUaG9zZSBzaG91bGQgYmUgY2F1Z2h0XG5ldmFsKCdleGVjKGFhYWFhYWEpJylcbmV2YWwoXCJhYWFhXCIpXG5cbiMgVGhvc2Ugbm90XG5ldmFsKGInZXhlYycpXG5ldmFsKCcnJ2V4ZWMnJycpIn0=)

# 💻 Code

Code:

```
# Those should be caught
eval('exec(aaaaaaa)')
eval("aaaa")

# Those not
eval(b'exec')
eval('''exec''')
```

Pattern:

```yml
id: python-static-extract-eval
message: Extract code executed by eval
language: Python
rule:
  all:
    - pattern: eval($DATA)
    - not:
        pattern: eval($EXEC)
        # has:
        #   stopBy: end
        #   regex: "([b'\"]+)exec([b'\"]+)"
        #   kind: string

constraints:
  DATA:
    kind: string
  # If replace this constraint with the commented "has" pattern, it works
  EXEC:
    regex: "([b'\"]+)exec([b'\"]+)"
    kind: string

fix: $DATA
```

# 🙁 Actual behavior

The rule does not catch anything, I have tried a few variants of the `EXEC` constraint. However, if I replace EXEC with the commented `has` pattern, the behaviour is as I expect. I think that constraints are not respected in nested (or just "not") patterns, or the evaluation of them happens too late (after a node is rejected).

# 🙂 Expected behavior

The `EXEC` constraint limits which nodes are rejected, and the rule catches the first two examples, but not the last two.
