### ISSUE TITLE
[bug] Python replacement indentation wrong in indented class

### ISSUE THREAD

**Issue by pankajp** [ast-grep/ast-grep#1405]
# ⏯ Playground Link

[Playground link with relevant code](https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6InB5dGhvbiIsInF1ZXJ5IjoiY2xhc3MgJCQkQ0JTOlxyXG4gICAgJycnJERTJycnXHJcbiAgICAkJCRDQlxyXG4iLCJyZXdyaXRlIjoiY2xhc3MgJCQkQ0JTOlxyXG4gICAgXCJcIlwiJERTXCJcIlwiXHJcbiAgICBiYXRjaF9tb2RlID0gVHJ1ZVxyXG4gICAgJCQkQ0IiLCJzdHJpY3RuZXNzIjoic21hcnQiLCJzZWxlY3RvciI6IkVSUk9SIiwiY29uZmlnIjoiaWQ6IGJhdGNoLW1vZGUtcGF0dGVyblxubWVzc2FnZTogQ2xhc3MgXCIkQ05cIiBjYW4gYmUgYmF0Y2ggbW9kZSBwYXR0ZXJuXG5zZXZlcml0eTogaW5mb1xuIyBBZGQgYmF0Y2hfbW9kZT1UcnVlIGFzIGEgY2xhc3MgdmFyaWFibGUgKGFmdGVyIGFueSBkb2NzdHJpbmdzKVxucnVsZTpcbiAga2luZDogY2xhc3NfZGVmaW5pdGlvblxuICBwYXR0ZXJuOiB8LVxuICAgIGNsYXNzICRDTigkJCRDQlMpOlxuICAgICAgJCQkQ0JTMVxudXRpbHM6XG4gIGlzLWRvY3N0cmluZzpcbiAgICBraW5kOiBleHByZXNzaW9uX3N0YXRlbWVudFxuICAgIGhhczpcbiAgICAgIGtpbmQ6IHN0cmluZ1xuICAgIG5vdDpcbiAgICAgIGhhczpcbiAgICAgICAgbnRoQ2hpbGQ6IDJcbiAgICBpbnNpZGU6XG4gICAgICBraW5kOiBibG9ja1xuICAgICAgaW5zaWRlOlxuICAgICAgICBhbnk6XG4gICAgICAgICAgLSBraW5kOiBjbGFzc19kZWZpbml0aW9uXG4gICAgICAgICAgLSBraW5kOiBmdW5jdGlvbl9kZWZpbml0aW9uXG4gICAgbnRoQ2hpbGQ6IDFcbnRyYW5zZm9ybTpcbiAgQ0JTMVI6XG4gICAgcmV3cml0ZTpcbiAgICAgIHJld3JpdGVyczpcbiAgICAgICAgLSBhZGRfYmF0Y2hfbW9kZV9ub19kb2NzdHJpbmdcbiAgICAgICAgLSBhZGRfYmF0Y2hfbW9kZV93aXRoX2RvY3N0cmluZ1xuICAgICAgc291cmNlOiAkJCRDQlMxXG5yZXdyaXRlcnM6XG4gIC0gaWQ6IGFkZF9iYXRjaF9tb2RlX25vX2RvY3N0cmluZ1xuICAgIHJ1bGU6XG4gICAgICBwYXR0ZXJuOiAkQVxuICAgICAgaW5zaWRlOlxuICAgICAgICBpbnNpZGU6XG4gICAgICAgICAga2luZDogY2xhc3NfZGVmaW5pdGlvblxuICAgICAgbm90OlxuICAgICAgICBtYXRjaGVzOiBpcy1kb2NzdHJpbmdcbiAgICAgIG50aENoaWxkOiAxXG4gICAgZml4OiB8LVxuICAgICAgYmF0Y2hfbW9kZSA9IFRydWVcbiAgICAgICRBXG4gIC0gaWQ6IGFkZF9iYXRjaF9tb2RlX3dpdGhfZG9jc3RyaW5nXG4gICAgcnVsZTpcbiAgICAgIHBhdHRlcm46ICRBXG4gICAgICBpbnNpZGU6XG4gICAgICAgIGluc2lkZTpcbiAgICAgICAgICBraW5kOiBjbGFzc19kZWZpbml0aW9uXG4gICAgICBtYXRjaGVzOiBpcy1kb2NzdHJpbmdcbiAgICBmaXg6IHwtXG4gICAgICAgICRBXG4gICAgICAgIGJhdGNoX21vZGUgPSBUcnVlXG5maXg6IHwtXG4gIGNsYXNzICRDTigkJCRDQlMpOlxuICAgICAgJENCUzFSXG4iLCJzb3VyY2UiOiJcbmNsYXNzIEEob2JqZWN0KTpcbiAgICAjIGNvbW1lbnRcbiAgICBkZWYgcmVwbGFjZShzZWxmLCAqYXJncywgKiprd2FyZ3MpOlxuICAgICAgICBwcmludChzZWxmYSlcblxuY2xhc3MgQyhvYmplY3QpOlxuICAgICcnJyBkb2Mgc3RyaW5nICcnJ1xuICAgIGRlZiByZXBsYWNlKHNlbGYsICphcmdzLCAqKmt3YXJncyk6XG4gICAgICAgIHByaW50KHNlbGZhKVxuXG5pZiBzb21ldGhpbmc6XG4gICAgY2xhc3MgQihBKTpcbiAgICAgICAgXCJcIlwiIGNsYXNzIGRvY3N0cmluZyBcIlwiXCJcbiAgICAgICAgZGVmIHJlcGxhY2Uoc2VsZiwgKmFyZ3MsICoqa3dhcmdzKTpcbiAgICAgICAgICAgIFwiXCJcIiBzZmdzZmQgc2VsZiBcIlwiXCJcbiAgICAgICAgICAgIHByaW50KHNlbGYxKVxuZWxzZTpcbiAgICBjbGFzcyBCKEEpOlxuICAgICAgICBkZWYgcmVwbGFjZShzZWxmLCAqYXJncywgKiprd2FyZ3MpOlxuICAgICAgICAgICAgXCJcIlwiIHNmZ3NmZCBzZWxmIFwiXCJcIlxuICAgICAgICAgICAgcHJpbnQoc2VsZjEpXG4ifQ==)

# 💻 Code

Code:

```python
class A(object):
    # comment
    def replace(self, *args, **kwargs):
        print(selfa)

class C(object):
    ''' doc string '''
    def replace(self, *args, **kwargs):
        print(selfa)

if something:
    class B(A):
        """ class docstring """
        def replace(self, *args, **kwargs):
            """ sfgsfd self """
            print(self1)
else:
    class B(A):
        def replace(self, *args, **kwargs):
            """ sfgsfd self """
            print(self1)
```

Pattern:

```yml
id: batch-mode-pattern
message: Class "$CN" can be batch mode pattern
severity: info
# Add batch_mode=True as a class variable (after any docstrings)
rule:
  kind: class_definition
  pattern: |-
    class $CN($$$CBS):
      $$$CBS1
utils:
  is-docstring:
    kind: expression_statement
    has:
      kind: string
    not:
      has:
        nthChild: 2
    inside:
      kind: block
      inside:
        any:
          - kind: class_definition
          - kind: function_definition
    nthChild: 1
transform:
  CBS1R:
    rewrite:
      rewriters:
        - add_batch_mode_no_docstring
        - add_batch_mode_with_docstring
      source: $$$CBS1
rewriters:
  - id: add_batch_mode_no_docstring
    rule:
      pattern: $A
      inside:
        inside:
          kind: class_definition
      not:
        matches: is-docstring
      nthChild: 1
    fix: |-
      batch_mode = True
      $A
  - id: add_batch_mode_with_docstring
    rule:
      pattern: $A
      inside:
        inside:
          kind: class_definition
      matches: is-docstring
    fix: |-
        $A
        batch_mode = True
fix: |-
  class $CN($$$CBS):
      $CBS1R
```

# 🙁 Actual behavior

```python
class A(object):
    # comment
    batch_mode = True
    def replace(self, *args, **kwargs):
        print(selfa)

class C(object):
    ''' doc string '''
    batch_mode = True
    def replace(self, *args, **kwargs):
        print(selfa)

if something:
    class B(A):
        """ class docstring """
            batch_mode = True
            def replace(self, *args, **kwargs):
                """ sfgsfd self """
                print(self1)
else:
    class B(A):
        batch_mode = True
            def replace(self, *args, **kwargs):
                """ sfgsfd self """
                print(self1)
```

Indentation of 2nd and subsequent lines is incorrect in the indented classes within `if something` and `else`

# 🙂 Expected behavior

```python
class A(object):
    # comment
    batch_mode = True
    def replace(self, *args, **kwargs):
        print(selfa)

class C(object):
    ''' doc string '''
    batch_mode = True
    def replace(self, *args, **kwargs):
        print(selfa)

if something:
    class B(A):
        """ class docstring """
        batch_mode = True
        def replace(self, *args, **kwargs):
            """ sfgsfd self """
            print(self1)
else:
    class B(A):
        batch_mode = True
        def replace(self, *args, **kwargs):
            """ sfgsfd self """
            print(self1)
```

**Comment by HerringtonDarkholme** [comment]
sadly ast-grep does not support this use case.

the problem is that the meta variable captures $A captures like this

```
def test():
        pass # note this indentation is 8 instead of 4
```
The fix string 
```
BATCH = True
$A
```

will preserve the 8 whitespace.

**Comment by StevenLove** [comment]
Check out [this message thread](https://discord.com/channels/1107749847722889217/1248583758291144765) from the ast-grep Discord for some additional info trying to work around indentation issues. @HerringtonDarkholme does this issue imply that ast-grep has a serious limitation when it comes to writing rules for Python?

**Comment by HerringtonDarkholme** [comment]
@StevenLove I feel the problem may be caused by wrong indentation in `rewrite`. If the fix above is applied without using rewrite, that is, rewriting directly in the `fix`, the indentation works fine.

I will investigate more in this issue and hopefully it can be fixed. Meanwhile, the indentation issue can imply that `rewriter` may not work well with Python atm.

**Comment by HerringtonDarkholme** [comment]
Minimal reproduction:

```py
if something:
    class B(A):
        def replace(self, *args, **kwargs):
            print(self1)
```

```yml
id: batch-mode-pattern
language: python
rule:
  kind: class_definition
  pattern: |-
    class $CN($$$CBS):
      $A
fix: |-
  class $CN($$$CBS):
      test = 123
      $A
```

**Comment by StevenLove** [comment]
Here is a [playground link](https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6InB5dGhvbiIsInF1ZXJ5IjoiY2xhc3MgJCQkQ0JTOlxyXG4gICAgJycnJERTJycnXHJcbiAgICAkJCRDQlxyXG4iLCJyZXdyaXRlIjoiY2xhc3MgJCQkQ0JTOlxyXG4gICAgXCJcIlwiJERTXCJcIlwiXHJcbiAgICBiYXRjaF9tb2RlID0gVHJ1ZVxyXG4gICAgJCQkQ0IiLCJzdHJpY3RuZXNzIjoic21hcnQiLCJzZWxlY3RvciI6IkVSUk9SIiwiY29uZmlnIjoiIyBNb2RpZnkgbGluZSAyMCB0byBzZWUgdGhlIGVmZmVjdFxuaWQ6IGRlbW9uc3RyYXRlLXJld3JpdGVyLWluZGVudGF0aW9uXG5sYW5ndWFnZTogcHl0aG9uXG5ydWxlOlxuICBraW5kOiBjbGFzc19kZWZpbml0aW9uXG4gIHBhdHRlcm46IHwtXG4gICAgY2xhc3MgJENOKCQkJENCUyk6XG4gICAgICAkQVxuXG50cmFuc2Zvcm06XG4gIEFSOlxuICAgIHJld3JpdGU6XG4gICAgICByZXdyaXRlcnM6XG4gICAgICAgIC0gZG9ub3RoaW5nXG4gICAgICBzb3VyY2U6ICRBXG5cbmZpeDogfC1cbiAgY2xhc3MgJENOKCQkJENCUyk6XG4gICAgICB0ZXN0ID0gMTIzXG4gICAgICAkQVxuIyAgICAgIF4gY2hhbmdlIHRoaXMgJEEgdG8gJEFSIHRvIGFwcGx5IGEgZG8tbm90aGluZyByZXdyaXRlclxuIyBhbmQgc2VlIHRoYXQgdGhlIGluZGVudGF0aW9uIGxldmVsIGNoYW5nZXMgaW4gdGhlIGRpZmZcblxucmV3cml0ZXJzOlxuICAtIGlkOiBkb25vdGhpbmdcbiAgICBydWxlOlxuICAgICAgcGF0dGVybjogJFpcbiAgICBmaXg6ICRaIiwic291cmNlIjoiaWYgc29tZXRoaW5nOlxuICAgIGNsYXNzIEIoQSk6XG4gICAgICAgIGRlZiByZXBsYWNlKHNlbGYsICphcmdzLCAqKmt3YXJncyk6XG4gICAgICAgICAgICBwcmludChzZWxmMSkifQ==) that shows how adding a rewriter changes indentation even if the rewriter is doing nothing.

**Comment by HerringtonDarkholme** [comment]
I have a even simpler reproduction:

```yml
id: demonstrate-transform-indentation
language: python
rule: { pattern: $A, kind: function_definition }
transform:
  AR: { substring: { source: $A } }
fix: $A
```

https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6InB5dGhvbiIsInF1ZXJ5IjoiY2xhc3MgJCQkQ0JTOlxyXG4gICAgJycnJERTJycnXHJcbiAgICAkJCRDQlxyXG4iLCJyZXdyaXRlIjoiY2xhc3MgJCQkQ0JTOlxyXG4gICAgXCJcIlwiJERTXCJcIlwiXHJcbiAgICBiYXRjaF9tb2RlID0gVHJ1ZVxyXG4gICAgJCQkQ0IiLCJzdHJpY3RuZXNzIjoic21hcnQiLCJzZWxlY3RvciI6IkVSUk9SIiwiY29uZmlnIjoiaWQ6IGRlbW9uc3RyYXRlLXRyYW5zZm9ybS1pbmRlbnRhdGlvblxubGFuZ3VhZ2U6IHB5dGhvblxucnVsZTogeyBwYXR0ZXJuOiAkQSwga2luZDogZnVuY3Rpb25fZGVmaW5pdGlvbiB9XG50cmFuc2Zvcm06XG4gIEFSOiB7IHN1YnN0cmluZzogeyBzb3VyY2U6ICRBIH0gfVxuZml4OiAkQSIsInNvdXJjZSI6ImlmIHNvbWV0aGluZzpcbiAgY2xhc3MgQihBKTpcbiAgICBkZWYgcmVwbGFjZShzZWxmLCAqYXJncywgKiprd2FyZ3MpOlxuICAgICAgcHJpbnQoc2VsZjEpIn0=
