### ISSUE TITLE
[bug] 0.27.0:`sg scan` cause panic on GitHub ubuntu-latest

### ISSUE THREAD

**Issue by azu** [ast-grep/ast-grep#1456]
# Redproduce

I've written following workflow file and it throw an error.

```yaml
name: Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download ast-grep
        run: |
          curl "https://github.com/ast-grep/ast-grep/releases/download/0.27.0/app-x86_64-unknown-linux-gnu.zip" -L -o ast-grep.zip
          unzip ast-grep.zip
          ls -al
          chmod +x ast-grep
          chmod +x sg
          ls -al
          ./ast-grep --version
          ./sg --version # --version is work
      - name: scan 
        run: |
          ./ast-grep scan .github/workflows/ # throw error
```

Reproduce repository:

- https://github.com/azu/ast-grep-githubaction-x86

# 🙁 Actual behavior

`ast-grep scan` command cause panic:

```
./ast-grep scan .github/workflows/
thread 'main' panicked at crates/cli/src/config.rs:115:8:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

- Log: https://github.com/azu/ast-grep-githubaction-x86/actions/runs/10758012627/job/29832759318

# 🙂 Expected behavior

No panic.

## Notes

- ast-grep: 0.27.0
- macOS arm64(Apple silicon): No problem
- ubuntu aarch64: No problem
