### ISSUE TITLE
Output of all suitable cases

### ISSUE THREAD

**Issue by RoketFlame** [ast-grep/ast-grep#1518]
# ⭐ Suggestion

Sometimes you have to go through all possible variants for a metavariable to find the right one. This is the case in large rules where there are many restrictions on metavariable. Here we are talking about using more than one metavariable in a rule, i.e. `match` will indeed find all matching variants, but if a metavariable is declared for some element inside, only that element will be printed (even if there are actually many matching elements).

Translated with DeepL.com (free version)

# 💻 Use Cases

I have a function and I need to loop through all possible pairs of arguments in it. I can write rule like this:
```yaml
id: pair-of-arguments
language: python
utils:

  is-first-arg:
    kind: typed_parameter
    all:
      - has:
          kind: identifier
          pattern: $FIRST
      - has:
          kind: type
          pattern: $FIRST_TYPE

  is-second-arg:
    kind: typed_parameter
    all:
      - has:
          kind: identifier
          pattern: $SECOND
          not:
            pattern: $FIRST
      - has:
          kind: type
          pattern: $SECOND_TYPE
                
rule:
  matches: is-first-arg
  inside:
    kind: function_definition
    stopBy: end
    has:
      matches: is-second-arg
      stopBy: end
```
But is doesn't work, because `is-second-arg` catches firt relevant case and stops. [Playground](https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6InB5dGhvbiIsInF1ZXJ5IjoiY29uc29sZS5sb2coJE1BVENIKSIsInJld3JpdGUiOiJsb2dnZXIubG9nKCRNQVRDSCkiLCJzdHJpY3RuZXNzIjoic21hcnQiLCJzZWxlY3RvciI6IiIsImNvbmZpZyI6ImlkOiBwYWlyLW9mLWFyZ3VtZW50c1xubGFuZ3VhZ2U6IHB5dGhvblxudXRpbHM6XG5cbiAgaXMtZmlyc3QtYXJnOlxuICAgIGtpbmQ6IHR5cGVkX3BhcmFtZXRlclxuICAgIGFsbDpcbiAgICAgIC0gaGFzOlxuICAgICAgICAgIGtpbmQ6IGlkZW50aWZpZXJcbiAgICAgICAgICBwYXR0ZXJuOiAkRklSU1RcbiAgICAgIC0gaGFzOlxuICAgICAgICAgIGtpbmQ6IHR5cGVcbiAgICAgICAgICBwYXR0ZXJuOiAkRklSU1RfVFlQRVxuXG4gIGlzLXNlY29uZC1hcmc6XG4gICAga2luZDogdHlwZWRfcGFyYW1ldGVyXG4gICAgYWxsOlxuICAgICAgLSBoYXM6XG4gICAgICAgICAga2luZDogaWRlbnRpZmllclxuICAgICAgICAgIHBhdHRlcm46ICRTRUNPTkRcbiAgICAgICAgICBub3Q6XG4gICAgICAgICAgICBwYXR0ZXJuOiAkRklSU1RcbiAgICAgIC0gaGFzOlxuICAgICAgICAgIGtpbmQ6IHR5cGVcbiAgICAgICAgICBwYXR0ZXJuOiAkU0VDT05EX1RZUEVcbiAgICAgICAgICAgICAgICBcbnJ1bGU6XG4gIG1hdGNoZXM6IGlzLWZpcnN0LWFyZ1xuICBpbnNpZGU6XG4gICAga2luZDogZnVuY3Rpb25fZGVmaW5pdGlvblxuICAgIHN0b3BCeTogZW5kXG4gICAgaGFzOlxuICAgICAgbWF0Y2hlczogaXMtc2Vjb25kLWFyZ1xuICAgICAgc3RvcEJ5OiBlbmRcblxuXG5cblxuXG4iLCJzb3VyY2UiOiJkZWYgZm9vKGJhcjogQmFyLCBmYWE6IEZhYSwgYmF6OiBCYXopOlxuICAgIC4uLiJ9) with example.
