### ISSUE TITLE
[bug] Unable to suppress errors for rule based on Python module kind

### ISSUE THREAD

**Issue by seamuswn** [ast-grep/ast-grep#1541]
### Please read the FAQ for the bug you encountered.

- [X] I have read the existing FAQ

### ⏯ Playground Link

https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6InB5dGhvbiIsInF1ZXJ5IjoiY29uc29sZS5sb2coJE1BVENIKSIsInJld3JpdGUiOiJsb2dnZXIubG9nKCRNQVRDSCkiLCJzdHJpY3RuZXNzIjoic21hcnQiLCJzZWxlY3RvciI6IiIsImNvbmZpZyI6Ii0tLVxuaWQ6IGVtcHR5X2luaXRfZmlsZXNcbmxhbmd1YWdlOiBQeXRob25cbnNldmVyaXR5OiBlcnJvclxubWVzc2FnZTogfFxuICBgX19pbml0X18ucHlgIGZpbGVzIHNob3VsZCBiZSBlbXB0eSBhc2lkZSBmcm9tIGltcG9ydHNcblxucnVsZTpcbiAga2luZDogbW9kdWxlXG4gIGhhczpcbiAgICBub3Q6XG4gICAgICBhbnk6XG4gICAgICAgIC0ga2luZDogaW1wb3J0X2Zyb21fc3RhdGVtZW50XG4gICAgICAgIC0ga2luZDogaW1wb3J0X3N0YXRlbWVudFxuXG5maWxlczpcbiAgLSAnKiovX19pbml0X18ucHknXG4iLCJzb3VyY2UiOiIjIGFzdC1ncmVwLWlnbm9yZTogZW1wdHlfaW5pdF9maWxlc1xuZnJvbSBmb28gaW1wb3J0IGJhclxuaW1wb3J0IGZvb1xuXG5mb28gPSBiYXIifQ==

### 💻 Code

```
---
id: empty_init_files
language: Python
severity: error
message: |
  `__init__.py` files should be empty aside from imports

rule:
  kind: module
  has:
    not:
      any:
        - kind: import_from_statement
        - kind: import_statement

files:
 - '**/__init__.py'

```

### 🙁 Actual behavior

With rule above, and `# ast-grep-ignore: empty_init_files` as first line in the module, ast-grep complains about `/my/path/__init__.py:1:1: error[empty_init_files]: `__init__.py` files should be empty aside from imports` but also `/my/path/__init__.py:1:1: help[unused-suppression]: Unused '@ast-grep-ignore' directive.`

### 🙂 Expected behavior

Placing module suppression on very first line should result in this rule being ignored and ast-grep scan passing.
