### ISSUE TITLE
[feature] LSP server integration

### ISSUE THREAD

**Issue by RoketFlame** [ast-grep/ast-grep#1581]
# ⭐ Suggestion

It would be really cool to use LSP server methods to write rules (specifically go to definition).

# 💻 Use Cases

Sometimes you need to write a rule that is contiguous for multiple files. For example
`animal.py`
```python
class Animal:
    name: str
```
`dog.py`
```python
class Dog(Animal):
    def bark(self) -> str:
        return "Wuf!"
```
`main.py`
```python
from dog import Dog

def zoo(dog: Dog):
    print(dog.bark())
```

`is-named-class.yml`
```yaml
id: named-class
language: python

rule:
  kind: function_definition
  has:
    kind: parameters
    has:
      kind: typed_parameter
      has:
        field: type
        pattern: $TYPE
  inside:
    kind: module
    has:
      kind: class_definition
      all:
        - has:
            field: name
            pattern: $TYPE
        - has:
            field: body
            has:
              kind: expression_statement
              regex: ^name
```
Ast-grep doesn't match any nodes, but actually it is! (If we look inside the import)
If we join all `.py` files into one and rewrite `def zoo(dog: Dog) -> def zoo(dog: Animal)` (it's wrong, but it just for demonstration), then ast-grep matches function definition.

There is a way to get data from the whole project through the LSP server, but I don't know how implementable it is. Maybe ast-grep is not suitable for this task, but I don't know any other alternatives that can match ast-grep in terms of speed and functionality.
