### ISSUE TITLE
[bug] Multi Meta Variable do not work as expected

### ISSUE THREAD

**Issue by robertofd1995** [ast-grep/ast-grep#1583]
### Please read the FAQ for the bug you encountered.

- [X] I have read the existing FAQ

### ⏯ Playground Link

https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6InB5dGhvbiIsInF1ZXJ5IjoiY2xhc3MgJENMQVNTX05BTUUoT3BlcmF0aW9uT3V0cHV0KToge0ZpZWxkKC4uLiwgdGl0bGU9JFRJVExFKX0iLCJyZXdyaXRlIjoiRmllbGQoLi4uLCBzZXJpYWxpemVyX2FsaWFzPSRUSVRMRSkiLCJzdHJpY3RuZXNzIjoic21hcnQiLCJzZWxlY3RvciI6IiIsImNvbmZpZyI6IiMgeWFtbC1sYW5ndWFnZS1zZXJ2ZXI6ICRzY2hlbWE9aHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL2FzdC1ncmVwL2FzdC1ncmVwL21haW4vc2NoZW1hcy9ydWxlLmpzb25cblxuaWQ6IHRlc3QtZG9lcy1ub3Qtd29ya1xubWVzc2FnZTogJCQkIEV4cHJlc3Npb24gZG9lcyBOT1Qgd29ya3MgZmluZSBpZiBpdCBoYXMgbW9yZSB0aGFuIDEgY2hhclxubGFuZ3VhZ2U6IHB5dGhvblxuc2V2ZXJpdHk6IHdhcm5pbmdcbnJ1bGU6XG4gICAgcGF0dGVybjogRmllbGQoJCQkUFJFIHRpdGxlPSRUSVRMRSAkJCRQT1MpXG5maXg6IEZpZWxkKCQkJFBSRSBzZXJpYWxpemVyX2FsaWFzPSRUSVRMRSAkJCRQT1MpIiwic291cmNlIjoiY2xhc3MgQWRkZWRSb3coT3BlcmF0aW9uT3V0cHV0KTpcbiAgICByb3dfbnVtYmVyOiBpbnQgPSBGaWVsZCguLi4sIHRpdGxlPVwiUm93IG51bWJlclwiKVxuICAgIHJvd192YWx1ZXM6IGRpY3QgPSBGaWVsZCguLi4sIHRpdGxlPVwiUm93IHZhbHVlc1wiLCBleHRyYT1cImFzZFwiKVxuXG5yb3dfdmFsdWVzOiBkaWN0ID0gRmllbGQoLi4uLCB0aXRsZT1cIlJvdyB2YWx1ZXNcIiwgZXh0cmE9XCJhc2RcIikifQ==

### 💻 Code

For example this [pattern in playground](https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6InB5dGhvbiIsInF1ZXJ5IjoiY2xhc3MgJENMQVNTX05BTUUoT3BlcmF0aW9uT3V0cHV0KToge0ZpZWxkKC4uLiwgdGl0bGU9JFRJVExFKX0iLCJyZXdyaXRlIjoiRmllbGQoLi4uLCBzZXJpYWxpemVyX2FsaWFzPSRUSVRMRSkiLCJzdHJpY3RuZXNzIjoic21hcnQiLCJzZWxlY3RvciI6IiIsImNvbmZpZyI6IiMgeWFtbC1sYW5ndWFnZS1zZXJ2ZXI6ICRzY2hlbWE9aHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL2FzdC1ncmVwL2FzdC1ncmVwL21haW4vc2NoZW1hcy9ydWxlLmpzb25cblxuaWQ6IHRlc3QtZG9lcy1ub3Qtd29ya1xubWVzc2FnZTogJCQkIEV4cHJlc3Npb24gZG9lcyBOT1Qgd29ya3MgZmluZSBpZiBpdCBoYXMgbW9yZSB0aGFuIDIgY2hhclxubGFuZ3VhZ2U6IHB5dGhvblxuc2V2ZXJpdHk6IHdhcm5pbmdcbnJ1bGU6XG4gICAgcGF0dGVybjogRmllbGQoJCQkUFIgdGl0bGU9JFRJVExFICQkJFBPKVxuZml4OiBGaWVsZCgkJCRQUiBzZXJpYWxpemVyX2FsaWFzPSRUSVRMRSAkJCRQTykiLCJzb3VyY2UiOiJjbGFzcyBBZGRlZFJvdyhPcGVyYXRpb25PdXRwdXQpOlxuICAgIHJvd19udW1iZXI6IGludCA9IEZpZWxkKC4uLiwgdGl0bGU9XCJSb3cgbnVtYmVyXCIpXG4gICAgcm93X3ZhbHVlczogZGljdCA9IEZpZWxkKC4uLiwgdGl0bGU9XCJSb3cgdmFsdWVzXCIsIGV4dHJhPVwiYXNkXCIpXG5cbnJvd192YWx1ZXM6IGRpY3QgPSBGaWVsZCguLi4sIHRpdGxlPVwiUm93IHZhbHVlc1wiLCBleHRyYT1cImFzZFwiKSJ9) works

```YAML
id: test-does-work
message: $$$ Expression DOES works fine if it has less than 2 char
language: python
severity: warning
rule:
    pattern: Field($$$PR title=$TITLE $$$PO)
fix: Field($$$PR serializer_alias=$TITLE $$$PO)
```

But if the multi meta variable has more than 1-2 characters, it stops working (See pattern in playground [here](https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6InB5dGhvbiIsInF1ZXJ5IjoiY2xhc3MgJENMQVNTX05BTUUoT3BlcmF0aW9uT3V0cHV0KToge0ZpZWxkKC4uLiwgdGl0bGU9JFRJVExFKX0iLCJyZXdyaXRlIjoiRmllbGQoLi4uLCBzZXJpYWxpemVyX2FsaWFzPSRUSVRMRSkiLCJzdHJpY3RuZXNzIjoic21hcnQiLCJzZWxlY3RvciI6IiIsImNvbmZpZyI6IiMgeWFtbC1sYW5ndWFnZS1zZXJ2ZXI6ICRzY2hlbWE9aHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL2FzdC1ncmVwL2FzdC1ncmVwL21haW4vc2NoZW1hcy9ydWxlLmpzb25cblxuaWQ6IHRlc3QtZG9lcy1ub3Qtd29ya1xubWVzc2FnZTogJCQkIEV4cHJlc3Npb24gZG9lcyBOT1Qgd29ya3MgZmluZSBpZiBpdCBoYXMgbW9yZSB0aGFuIDEgY2hhclxubGFuZ3VhZ2U6IHB5dGhvblxuc2V2ZXJpdHk6IHdhcm5pbmdcbnJ1bGU6XG4gICAgcGF0dGVybjogRmllbGQoJCQkUFJFIHRpdGxlPSRUSVRMRSAkJCRQT1MpXG5maXg6IEZpZWxkKCQkJFBSRSBzZXJpYWxpemVyX2FsaWFzPSRUSVRMRSAkJCRQT1MpIiwic291cmNlIjoiY2xhc3MgQWRkZWRSb3coT3BlcmF0aW9uT3V0cHV0KTpcbiAgICByb3dfbnVtYmVyOiBpbnQgPSBGaWVsZCguLi4sIHRpdGxlPVwiUm93IG51bWJlclwiKVxuICAgIHJvd192YWx1ZXM6IGRpY3QgPSBGaWVsZCguLi4sIHRpdGxlPVwiUm93IHZhbHVlc1wiLCBleHRyYT1cImFzZFwiKVxuXG5yb3dfdmFsdWVzOiBkaWN0ID0gRmllbGQoLi4uLCB0aXRsZT1cIlJvdyB2YWx1ZXNcIiwgZXh0cmE9XCJhc2RcIikifQ==) )

```YAML
# yaml-language-server: $schema=https://raw.githubusercontent.com/ast-grep/ast-grep/main/schemas/rule.json

id: test-does-not-work
message: $$$ Expression DOES NOT works fine if it has more than 1-2 char
language: python
severity: warning
rule:
    pattern: Field($$$PRE title=$TITLE $$$POS)
fix: Field($$$PRE serializer_alias=$TITLE $$$POS)
```

### 🙁 Actual behavior

If I have a Multi Meta Variable with a name longer than 2 characters the pattern is NOT working

### 🙂 Expected behavior

If I have a Multi Meta Variable with a name longer than 2 characters the pattern is working

### Additional information about the issue

I am having this issue both in playground and also if I execute it locally using the CLI

**Comment by HerringtonDarkholme** [comment]
https://ast-grep.github.io/advanced/faq.html#my-rule-does-not-work-why
<img width="781" alt="image" src="https://github.com/user-attachments/assets/37b148f6-ae6c-4f20-92af-6834c1e94a86">

The pattern is invalid code
<img width="541" alt="image" src="https://github.com/user-attachments/assets/5cd322ed-034d-45f0-ba5f-65e77301e20b">

https://ast-grep.github.io/advanced/pattern-parse.html#pattern-is-ast-based

<img width="726" alt="image" src="https://github.com/user-attachments/assets/6a47a8d0-1dab-41e7-a516-8976a33c2064">

You may also ask why other invalid code snippet works.

<img width="641" alt="image" src="https://github.com/user-attachments/assets/caa3ba69-fae3-4ae4-be55-b57b024e7ce1">

**Comment by HerringtonDarkholme** [comment]
You can use this one

https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6InB5dGhvbiIsInF1ZXJ5IjoiY2xhc3MgJENMQVNTX05BTUUoT3BlcmF0aW9uT3V0cHV0KToge0ZpZWxkKC4uLiwgdGl0bGU9JFRJVExFKX0iLCJyZXdyaXRlIjoiRmllbGQoLi4uLCBzZXJpYWxpemVyX2FsaWFzPSRUSVRMRSkiLCJzdHJpY3RuZXNzIjoic21hcnQiLCJzZWxlY3RvciI6IiIsImNvbmZpZyI6IiMgeWFtbC1sYW5ndWFnZS1zZXJ2ZXI6ICRzY2hlbWE9aHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL2FzdC1ncmVwL2FzdC1ncmVwL21haW4vc2NoZW1hcy9ydWxlLmpzb25cblxuaWQ6IHRlc3QtZG9lcy1ub3Qtd29ya1xubGFuZ3VhZ2U6IHB5dGhvblxuc2V2ZXJpdHk6IHdhcm5pbmdcbnJ1bGU6XG4gICAgcGF0dGVybjogXG4gICAgICBjb250ZXh0OiBGaWVsZCh0aXRsZT0kVElUTEUpXG4gICAgICBzZWxlY3Rvcjoga2V5d29yZF9hcmd1bWVudFxuZml4OiBzZXJpYWxpemVyX2FsaWFzPSRUSVRMRSIsInNvdXJjZSI6ImNsYXNzIEFkZGVkUm93KE9wZXJhdGlvbk91dHB1dCk6XG4gICAgcm93X251bWJlcjogaW50ID0gRmllbGQoLi4uLCB0aXRsZT1cIlJvdyBudW1iZXJcIilcbiAgICByb3dfdmFsdWVzOiBkaWN0ID0gRmllbGQoLi4uLCB0aXRsZT1cIlJvdyB2YWx1ZXNcIiwgZXh0cmE9XCJhc2RcIilcblxucm93X3ZhbHVlczogZGljdCA9IEZpZWxkKC4uLiwgdGl0bGU9XCJSb3cgdmFsdWVzXCIsIGV4dHJhPVwiYXNkXCIpIn0=

```yml
id: test-does-not-work
language: python
severity: warning
rule:
    pattern: 
      context: Field(title=$TITLE)
      selector: keyword_argument
fix: serializer_alias=$TITLE
```
