### ISSUE TITLE
[ Question ] Search JS template literal with variable interpolation

### ISSUE THREAD

**Issue by ShenQingchuan** [ast-grep/ast-grep#161]
Hi ! All hail the author of ast-grep ! Today I've finished reading the latest docs of ast-grep, but didn't found any pattern solution to search a JS template literal with variable interpolation. 

> My requirement is to search all the dependencies source code to find the "dynamic import" and add them to Vite's `optimizeDeps` to pre-bundle before Vite starts pre-bundling to avoid "Found new deps, re-run pre-bundle". So I'm wondering how I can search for all the dynamic import with speed and efficiency, then I found `ast-grep`!

Is there any pattern as my answer ? Thanks a lot ! ~

**Comment by HerringtonDarkholme** [comment]
Hi Qingchuan, would you mind give an example of input, and your desired output? Thanks

**Comment by HerringtonDarkholme** [comment]
https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6ImphdmFzY3JpcHQiLCJxdWVyeSI6ImltcG9ydCgkQSkiLCJjb25maWciOiIjIENvbmZpZ3VyZSBSdWxlIGluIFlBTUxcbnJ1bGU6XG4gIGFsbDpcbiAgICAtIHBhdHRlcm46ICRBXG4gICAgLSBraW5kOiB0ZW1wbGF0ZV9zdWJzdGl0dXRpb25cbiAgICAtIGluc2lkZTpcbiAgICAgICAgcGF0dGVybjogaW1wb3J0KCQpXG5jb25zdHJhaW50czpcbiAgIyBNRVRBX1ZBUjogcGF0dGVybiIsInNvdXJjZSI6ImNvbnN0IGEgPSBpbXBvcnQoYC4vdGVzdC8ke3Rlc3QgKyAxfWApIn0=

<img width="965" alt="image" src="https://user-images.githubusercontent.com/2883231/210964722-5602f3ce-68a9-48c5-a46d-050f2a30fe7f.png">

**Comment by ShenQingchuan** [comment]
> Hi Qingchuan, would you mind give an example of input, and your desired output? Thanks

Let me describe my usage situation more clearly. 

> I'm working with a big code base, and we're using Vite as builder tool. As we know, Vite 3 can pre-bundle those dependencies that our source code imported before passing codes to Rollup to do transforming. But the pre-bundle is on-demand and can't not detect dynamic import with variables, e.g. `import(`lib-name/${variables}`)`.
> The only way to optimize is add the package `'lib-name'` to `optimizeDeps` manually.
> 
> So I'm going to find all the dynamic import to get those "lost" packages

I've already seen the example you gave above, Thanks a lot !

But I still got some questions of using it in JS/TS 

1. How can I use it as a library or an external tool ? The main purpose is to get its output, you know I want those result at found

2. Maybe more ... but I must know the first question's answer to move on 😂 

#### Example

Here're some source codes written by ourselves below:

```ts
// ...
  import(`@org/widgets/i18n/locales/${config.locale}`)
// ...
```

All I want is to get the `@org/widgets/i18n/locales`...

> and then I'll looking for internal codes to search deeper import/deps by myself later ...

**Comment by ShenQingchuan** [comment]
> https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6ImphdmFzY3JpcHQiLCJxdWVyeSI6ImltcG9ydCgkQSkiLCJjb25maWciOiIjIENvbmZpZ3VyZSBSdWxlIGluIFlBTUxcbnJ1bGU6XG4gIGFsbDpcbiAgICAtIHBhdHRlcm46ICRBXG4gICAgLSBraW5kOiB0ZW1wbGF0ZV9zdWJzdGl0dXRpb25cbiAgICAtIGluc2lkZTpcbiAgICAgICAgcGF0dGVybjogaW1wb3J0KCQpXG5jb25zdHJhaW50czpcbiAgIyBNRVRBX1ZBUjogcGF0dGVybiIsInNvdXJjZSI6ImNvbnN0IGEgPSBpbXBvcnQoYC4vdGVzdC8ke3Rlc3QgKyAxfWApIn0=
> 
> <img alt="image" width="965" src="https://user-images.githubusercontent.com/2883231/210964722-5602f3ce-68a9-48c5-a46d-050f2a30fe7f.png">

Can I use this kind of config as inline options/flags that passed to `sg` CLI ?

That's my first thought when I thought about the question 1 above 😂

**Comment by HerringtonDarkholme** [comment]
For now you can use ast-grep-napi to use the it in JavaScript.
https://github.com/ast-grep/ast-grep/tree/main/crates/napi

```
rule:
  all:
    - pattern: $A
    - kind: template_string
    - inside:
        pattern: import($A)
```

**Comment by HerringtonDarkholme** [comment]
You can see some example usage in https://github.com/ast-grep/ast-grep/blob/main/crates/napi/__test__/index.spec.ts#L55

**Comment by ShenQingchuan** [comment]
> For now you can use ast-grep-napi to use the it in JavaScript. https://github.com/ast-grep/ast-grep/tree/main/crates/napi
> 
> ```
> rule:
>   all:
>     - pattern: $A
>     - kind: template_string
>     - inside:
>         pattern: import($A)
> ```
> 
> here is some example in the wild. https://github.com/modern-js-dev/libuild/blob/54f96b88eaf8bc5b1ef80d56e2c6c66e1fe47288/packages/libuild/src/plugins/redirect.ts#L182

Awesome!
Let me try to read those examples and learn something !~

THANKS A LOT !!

海老师，你！是我的神！

> I see modern.js ! Maybe I could find some workmates to ask(PY) for more details （坏笑

**Comment by ShenQingchuan** [comment]
@HerringtonDarkholme 

Hi, I've did some test, these're my configs

```yml
# rules/find-dynamic-import-ts.yml
id: find-dynamic-import-ts
message: found dynamic import in ts
severity: info
language: TypeScript
files:
  - "./packages/lark-mail-sdk/**"
  - "./larklets/byted-larklet-mail/**"
  - "./node_modules/**"
rule:
  all:
    - pattern: $A
    - kind: template_string
    - inside:
        pattern: import($A)

# rules/find-dynamic-import-ts.yml
id: find-dynamic-import-js
message: found dynamic import in js
severity: info
language: JavaScript
files:
  - "./packages/lark-mail-sdk/**"
  - "./larklets/byted-larklet-mail/**"
  - "./node_modules/**"
rule:
  all:
    - pattern: $A
    - kind: template_string
    - inside:
        pattern: import($A)
```

But it seems it skipped scanning `node_modules` because I did find some pattern matching inside `node_modules`, is that a known issue ?
