### ISSUE TITLE
[feature] Match "the same" nthChild

### ISSUE THREAD

**Issue by kam193** [ast-grep/ast-grep#1633]
# ⭐ Suggestion

The `nthChild` has currently great support for matching based on an expression or an exact number, but there is no possibility to correlate the value in different places. In a typical pattern, I can use a metavariable to match the same pattern in two places. I'd love to see similar possibility in `nthChildren` to find corresponding elements

# 💻 Use Cases

The example that leads to the issue is the assignment of multiple variables at the same time in Python. It looks like this:

```python
a, b, c = 1, 2, 3
```

The AST looks like:
![obraz](https://github.com/user-attachments/assets/9706465e-4e6b-4cb5-a3d1-31d562cbb4dd)

I want to match every variable and its corresponding value. Currently, I have to (or maybe I missed a better opportunity?) to explicitly set the child number on both sides of the assignment. The rule for three elements looks like:

```yaml
rule:
  kind: identifier
  inside:
    kind: pattern_list
    inside:
      kind: assignment
  any:
      - pattern: $VAR
        nthChild: 1
        inside:
          kind: pattern_list
          inside:
            kind: assignment
            has:
              kind: expression_list
              has:
                nthChild: 1
                pattern: $VALUE
      - pattern: $VAR
        nthChild: 2
        inside:
          kind: pattern_list
          inside:
            kind: assignment
            has:
              kind: expression_list
              has:
                nthChild: 2
                pattern: $VALUE
      - pattern: $VAR
        nthChild: 3
        inside:
          kind: pattern_list
          inside:
            kind: assignment
            has:
              kind: expression_list
              has:
                nthChild: 3
                pattern: $VALUE
```

It's already rather long, but manageable. My problem is, that the code I parse can have many more elements... I have a sample with 180. It leads me to terrible YAMLs like [here](https://github.com/kam193/assemblyline-services/blob/f5becf746ac7e37572c5f5e3a9ab4d235ef688a5/ASTGrep/rules/helpers/python/substitute-static.yml#L41). 

I'd love to make it using a variable, something like:

```yaml
rule:
  kind: identifier
  inside:
    kind: pattern_list
    inside:
      kind: assignment
  any:
      - pattern: $VAR
        nthChild: $I
        inside:
          kind: pattern_list
          inside:
            kind: assignment
            has:
              kind: expression_list
              has:
                nthChild: $I
                pattern: $VALUE
```

to match all possible child number pairs.

Would be great if you could consider extending ASTGrep in this way. I also imagine it may be quite complex and potentially impossible - then I'll stay with my monsters :D

**Comment by HerringtonDarkholme** [comment]
Hi thanks for using ast-grep.

Unfortunately synchronizing matching of two separate nodes is not supported in ast-grep now. 

Using meta-variable in non pattern rule does not generally align with ast-grep's design. 
If it can be used in pattern, it could also be used in `kind` or even `regex`. It is also unclear if `$I` can be used in `transform`. At last, the introduction of new meta-variable usage may make ast-grep rule too complicate to learn.

There are several alternatives to consider:
* Use Python API: https://ast-grep.github.io/guide/api-usage/py-api.html
* Use other tools to generate YAML

**Comment by kam193** [comment]
Thanks for the answer! I understand and as I said, I do expect it could be hard to introduce :)

Just to be clear, whether my idea should use meta variables or another syntax (e.g. just `nthChild: i`) is open.

**Comment by HerringtonDarkholme** [comment]
Thanks for understanding.

> whether my idea should use meta variables or another syntax (e.g. just nthChild: i) is open.

I have also considered using meta variables in nthChild or kind. for example

```yml
  pattern: $VAR
  inside:
    nthChild: $VAR
```

nthChild can reference a meta variable used before. It means that the matched node should have the same `nthChild` position as the reference meta variable. Using this construct can reuse the concept already in ast-grep. The confusing part like evaluation order is not worse than status quo.

However, it is unclear to me how it will be useful and how it can be generalized.
It links two AST nodes by their positions. They have to be at the exactly the same position, which can be too limiting.

If users have more complicated logic, using programmatic API is a more flexible and general solution. 

I think the idea of using meta variables in `nthChild` or `kind` is acceptable. However it has to be useful enough and has enough use cases to pay the abstraction tax.
