### ISSUE TITLE
[bug] LSP doesn't work if `files` is specificed inside a rule

### ISSUE THREAD

**Issue by ahmedelgabri** [ast-grep/ast-grep#1691]
### Please read the FAQ for the bug you encountered.

- [X] I have read the existing FAQ

### ⏯ Playground Link

https://github.com/ahmedelgabri/ast-grep-lsp-bug

### 💻 Code

```yaml
id: no-import
language: javascript
message: Imports from @foo are not allowed
severity: error
files: # <-- LSP doesn't work because of this
  - 'src/**'
rule:
  regex: '^@foo'
  kind: string_fragment
  any:
    - inside:
        stopBy: end
        kind: import_statement
    - inside:
        stopBy: end
        kind: call_expression
        has:
          field: function
          regex: '^import$'
    - inside:
        stopBy: end
        kind: call_expression
        has:
          field: function
          regex: '^require$'
```

### 🙁 Actual behavior

LSP doesn't work when `files` is specified, but `ast-grep scan` works fine. When having multiple rules in a large monorepo, removing `files` and specifying paths manually in each `ast-grep scan` call site doesn't scale well. 

For example, right now all we need to do is: 

```bash
ast-grep scan
```

In order to get Editor LSP support working, we need remove `files` and instead do the following

```bash
ast-grep scan --rule foo.yml ./path/** ./path2/**
ast-grep scan --rule bar.yml ./app/**
ast-grep scan --rule baz.yml ./some-other-path/** ./path/** ./path2/**
# etc…
```

The LSP should be able to handle this.

### 🙂 Expected behavior

The LSP to properly handle the rules which include `files` property.
