### ISSUE TITLE
[feature] `sg scan --update-all` should show output of fixed rules

### ISSUE THREAD

**Issue by liiight** [ast-grep/ast-grep#1708]
# ⭐ Suggestion
Following [this](https://github.com/ast-grep/ast-grep/discussions/1705) discussion, I suggest adding an output to the scenario that   a fix is applied when running `sg scan --update-all` as it currently does not show any output.

In addition, I recommend that the exit code of such operation (running a scan with the `--update-all` flag) will match the same as using it without the flag, i.e NOT return 0 if any fixed were successfully applied (but perhaps this merits a separate issue?)

Using a non-zero exit code is common practice in other popular tools like [eslint](https://eslint.org/docs/latest/use/command-line-interface#exit-codes) or [ruff](https://docs.astral.sh/ruff/linter/#exit-codes)
 
# 💻 Use Cases

- I mainly use `ast-grep` as a pre-commit hook, which show hooks output only on failure (by default)
- The current workaround is use is configuring `ast-grep` in two hooks:
```yaml
      - id: ast-grep
        name: Run ast-grep based tests (Report)
        entry: sg scan
        language: system
        types:
          - python

      - id: ast-grep-fix
        name: Run ast-grep based tests (Fix)
        entry: sg scan -U
        language: system
        types:
          - python
```
This is not ideal but not so bad as `ast-grep` is blazingly fast 😜

Thank you in advance for your time and this amazing tool 🙏
