### ISSUE TITLE
[feature]Matching nodes with some similar names

### ISSUE THREAD

**Issue by fcitwip** [ast-grep/ast-grep#1764]
# ⭐ Suggestion

It is expected to match parts of similar names in the nodes using patterns or regex.

# 💻 Use Cases

when assigning values, it's common to mistakenly assign a value to itself, so I want to write a rule like this
```yaml
rule:
  pattern: $A.$B($A.$C())
constraints:
  B:
    regex: "^set"
  C:
    regex: "^get"
```
![Image](https://github.com/user-attachments/assets/c6b30ed4-6618-4880-9cc9-c07f432ee906)
```java
class A{    
    public void test() {
        test.setTest(test.getTest());
        test.setTttt(test.getTest());
    }
}
```

writing it this way has a bad case, I don't want to match ` test.setTttt(test.getTest());`
