### ISSUE TITLE
[bug] Meta Variables defined in global utilities not found on parse

### ISSUE THREAD

**Issue by wolfgangwalther** [ast-grep/ast-grep#1766]
### Please read the FAQ for the bug you encountered.

- [x] I have read the existing FAQ

### ⏯ Playground Link

none

### 💻 Code

utils/anything.yml:
```
id: anything
language: nix
rule:
  kind: binding
  pattern: $ANYTHING
```

rules/use-anything-broken.yml:
```
id: use-anything
language: nix
rule:
  matches: anything
fix: $ANYTHING
```

rules/use-anything-working.yml:
```
id: use-anything
language: nix
rule:
  matches: anything
fix: $ANYTHING
utils:
  nothing:
    pattern: $ANYTHING
```

### 🙁 Actual behavior

for rules/use-anything-broken.yml:

```
✖ Caused by
╰▻ Fail to parse yaml as Rule.
╰▻ Undefined meta var `ANYTHING` used in `fix`.
```

### 🙂 Expected behavior

No error, same as for rules/use-anything-working.yml.

### Additional information about the issue

Couldn't create a reproducer in the playground, because I don't think I can create global utils there.

Don't mind the `language: nix`, this should be unspecific to any language.

Essentially, global utils can declare Meta Variables - and my working rules show, that they can also be used in regular rules. But an early parsing step seems to block loading the file, if it can't find the Meta Variable's definition in the same file.

Note, that it starts working when I add a completely unrelated rule `nothing`, which also declares this Meta Variable. This gets me past the parse error and after that the variable works fine.
