### ISSUE TITLE
[feature] Ability to only report rule error when rewriter is matched

### ISSUE THREAD

**Issue by soceanainn** [ast-grep/ast-grep#1876]
# ⭐ Suggestion

I want some way to run rewriter rules under `ast-grep scan -U` without generating excess noise. This would require some way of suppressing errors for unfixed values when running transforms (i.e. if transform returns the same value as the matched metavar when fixing, don't log an error).

If I have a bunch of rewriter rules that are more specific than my catch all rule, it generates a lot of noise when running in a large code base even if I mark as severity `hint`. For example in the rule you shared when answering this question: https://github.com/ast-grep/ast-grep/discussions/1566 the rule matches on `kind: type`,
but the rewriters only apply to optional / union types, so if I tried to add that to a codebase it would generate messages for every type annotation in the codebase, even though it's just there to catch and fix some very specific ones.

# 💻 Use Cases

I have a rule where I want to do generic rewrites to add types to specific named arguments in Python. The use case is for pytest fixtures which are 'magic' args you can add to any test so we reuse them across thousands of tests. I have 20 or so rewriters which match the fixture name with the type, so that e.g. `monkeypatch` becomes `monkeypatch: pytest.MonkeyPatch`.

Adding all regex patterns to both rewriter and rule is possible but painful to sync (alternative is to add utils and reference in both places I guess, but then the issue is the regex pattern we match on + the fix we implement for that are stored in separate areas in what is a pretty long YAML file.

**Comment by soceanainn** [comment]
[Playground link is here](https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6InB5dGhvbiIsInF1ZXJ5IjoiY29uc29sZS5sb2coJE1BVENIKSIsInJld3JpdGUiOiJsb2dnZXIubG9nKCRNQVRDSCkiLCJzdHJpY3RuZXNzIjoic21hcnQiLCJzZWxlY3RvciI6IiIsImNvbmZpZyI6Ii0tLVxuaWQ6IGFkZF9maXh0dXJlX3R5cGVzX3Rlc3RzXG5sYW5ndWFnZTogUHl0aG9uXG5tZXNzYWdlOiBBZGQgdHlwZXMgdG8gZml4dHVyZSBhcmd1bWVudHMgaW4gdGVzdHNcbnNldmVyaXR5OiBoaW50XG5cbiMgQWRkIG5ldyByZXdyaXRlciBvYmplY3RzIHRvICdyZXdyaXRlcnMnIHNlY3Rpb24gdGhlbiBhZGQgcmV3cml0ZXIgSUQgdG8gdHJhbnNmb3JtIHNlY3Rpb25cbiMgVGhpcyB3aWxsIGF1dG9tYXRpY2FsbHkgYWRkIHR5cGVzIHRvIHRob3NlIGZpeHR1cmVzIGluIHRlc3RzXG50cmFuc2Zvcm06XG4gIExJVEVSQUw6XG4gICAgcmV3cml0ZTpcbiAgICAgIHJld3JpdGVyczpcbiAgICAgICAgLSBjYXBsb2dcbiAgICAgICAgLSBpdGVtXG4gICAgICAgIC0gbW9ja2VyXG4gICAgICAgIC0gbW9ua2V5cGF0Y2hcbiAgICAgICAgLSByZXF1ZXN0XG4gICAgICBzb3VyY2U6ICRQXG5cbnJld3JpdGVyczpcbiAgLSBpZDogY2FwbG9nXG4gICAgcnVsZTpcbiAgICAgIHJlZ2V4OiAnXmNhcGxvZyQnXG4gICAgZml4OiAnY2FwbG9nOiBweXRlc3QuTG9nQ2FwdHVyZUZpeHR1cmUnXG4gIC0gaWQ6IGl0ZW1cbiAgICBydWxlOlxuICAgICAgcmVnZXg6ICdeaXRlbSQnXG4gICAgZml4OiAnaXRlbTogcHl0ZXN0Lkl0ZW0nXG4gIC0gaWQ6IG1vY2tlclxuICAgIHJ1bGU6XG4gICAgICByZWdleDogJ15tb2NrZXIkJ1xuICAgIGZpeDogJ21vY2tlcjogTW9ja2VyRml4dHVyZSdcbiAgLSBpZDogbW9ua2V5cGF0Y2hcbiAgICBydWxlOlxuICAgICAgcmVnZXg6ICdebW9ua2V5cGF0Y2gkJ1xuICAgIGZpeDogJ21vbmtleXBhdGNoOiBweXRlc3QuTW9ua2V5UGF0Y2gnXG4gIC0gaWQ6IHJlcXVlc3RcbiAgICBydWxlOlxuICAgICAgcmVnZXg6ICdecmVxdWVzdCQnXG4gICAgZml4OiAncmVxdWVzdDogcHl0ZXN0LkZpeHR1cmVSZXF1ZXN0J1xuXG5ydWxlOlxuICBraW5kOiBpZGVudGlmaWVyXG4gIHBhdHRlcm46ICRQXG4gIGluc2lkZTpcbiAgICBraW5kOiBwYXJhbWV0ZXJzXG4gICAgaW5zaWRlOlxuICAgICAga2luZDogZnVuY3Rpb25fZGVmaW5pdGlvblxuICAgICAgaGFzOlxuICAgICAgICBraW5kOiBpZGVudGlmaWVyXG4gICAgICAgIHJlZ2V4OiAnXnRlc3RfLiokJ1xuXG5maXg6ICRMSVRFUkFMXG5cbmZpbGVzOlxuICAtICd0ZXN0cy8qKi90ZXN0XyoucHknXG4iLCJzb3VyY2UiOiJkZWYgdGVzdF9mb28oY2FwbG9nLCBub3RfYV9maXh0dXJlKTpcbiAgcGFzcyJ9)

<details><summary>Rule looks something like this (custom fixtures removed so list is a bit shorter:</summary>

```yaml
---
id: add_fixture_types_tests
language: Python
message: Add types to fixture arguments in tests
severity: hint

# Add new rewriter objects to 'rewriters' section then add rewriter ID to transform section
# This will automatically add types to those fixtures in tests
transform:
  LITERAL:
    rewrite:
      rewriters:
        - caplog
        - item
        - mocker
        - monkeypatch
        - request
      source: $P

rewriters:
  - id: caplog
    rule:
      regex: '^caplog$'
    fix: 'caplog: pytest.LogCaptureFixture'
  - id: item
    rule:
      regex: '^item$'
    fix: 'item: pytest.Item'
  - id: mocker
    rule:
      regex: '^mocker$'
    fix: 'mocker: MockerFixture'
  - id: monkeypatch
    rule:
      regex: '^monkeypatch$'
    fix: 'monkeypatch: pytest.MonkeyPatch'
  - id: request
    rule:
      regex: '^request$'
    fix: 'request: pytest.FixtureRequest'

rule:
  kind: identifier
  pattern: $P
  inside:
    kind: parameters
    inside:
      kind: function_definition
      has:
        kind: identifier
        regex: '^test_.*$'

fix: $LITERAL

files:
  - 'tests/**/test_*.py'
```

</details> 

That rule will match and log a message for all untyped test args, so both caplog and bar in this example:
```python
def test_foo(caplog, bar):
  pass
```

But really I only want to catch and fix the untyped caplog arg

**Comment by HerringtonDarkholme** [comment]
I think the feature should be better modeled as constraints or filtering.

Say you can add this to `constraints`

```yml
constraints:
  LITERAL:
    regex: 'catalog|item|request|monkeypatch'
```
