### ISSUE TITLE
[feature] make relational rule's `until` operator inclusive

### ISSUE THREAD

**Issue by HerringtonDarkholme** [ast-grep/ast-grep#191]
Consider this rule
```
rule:
  kind: assignment_expression
  inside:
    immediate: true
    kind: parenthesized_expression
    inside:
      until:
        not:
          any:
            - kind: parenthesized_expression
            - kind: while_statement
            - kind: do_statement
            - kind: if_statement
            - kind: for_statement
      any:
        - kind: while_statement
        - kind: do_statement
        - kind: if_statement
        - kind: for_statement

```

It can be simplified if until operator is inclusive.
