### ISSUE TITLE
[feature] try unifying APIs for relational rule

### ISSUE THREAD

**Issue by HerringtonDarkholme** [ast-grep/ast-grep#193]
Current
```
inside:
  immediate: boolean
  until: {pattern: xxx}
  pattern: xx
```

Proposed

```
inside:
  pattern: XXXX
  stopsBy: 'neighbor' | 'end' | { pattern: xx }
```

until now is inclusive, but in natural language until is exclusive. Also immediate and until express the similar concept and they conflicts with each other.
