### ISSUE TITLE
[feature] Plugin system

### ISSUE THREAD

**Issue by ribru17** [ast-grep/ast-grep#1963]
# ⭐ Suggestion

It would be super helpful to have some sort of plugin system in ast-grep. There are many different ways to think about this, but it could look like:

- ast-grep defining a trait which plugins must adhere (maybe it takes in serialized value, produces a match result, list of ranges, etc.)
- plugins bild their own object which implements that trait, and compile it to a shared object
- ast-grep users can register this plugin, and ast-grep will then load the shared object in and use it to do custom rules/matching

# 💻 Use Cases

For example, we could hook in an LSP symbols provider to get something like the following:

```yaml
id: find-calls-to-react-components
language: tsx
rule:
  pattern: $COMPONENT($ARGS)
constraint:
  COMPONENT:
    definitionMatches:  # match against a symbol's *definition*
      pattern: function $NAME() { $$$ }
      has:
        # we assume a function that returns JSX is a component
        pattern: return <$X $$$ />
fix: <$COMPONENT ...$ARGS />
```

it could allow us to get semantic information about a symbol, rather than just syntactic information

**Comment by HerringtonDarkholme** [comment]
Related to 

https://github.com/ast-grep/ast-grep/issues/334

https://github.com/ast-grep/ast-grep/issues/433

**Comment by ribru17** [comment]
(Just a note: these are similar requests, but still different from this one, which would allow for arbitrary new features depending on the plugin)

**Comment by HerringtonDarkholme** [comment]
Several implementation questions:
1. how to parse unknown fields?  https://github.com/de-vri-es/serde-ignored-fields/ 
2. how to register custom field schema?
3. how to load plugin? wasm? dylib? or builtin?
4. what data should plugin receive, what outpu

**Comment by ribru17** [comment]
1. Maybe we could do it like `constraint`, allowing arbitrary field names for children, and their values are always a rule?
    ```yaml
    id: find-calls-to-react-components
    language: tsx
    rule:
      pattern: $COMPONENT($ARGS)
    constraint:
      COMPONENT:
        pluginMatchers: # names of plugins, mapped to their rule
          definitionMatches:  # match against a symbol's *definition*
            pattern: function $NAME() { $$$ }
            has:
              # we assume a function that returns JSX is a component
              pattern: return <$X $$$ />
    fix: <$COMPONENT ...$ARGS />
    ```
2. This is basically answered by 1., we can apply the same schema style as we do to `constraint`
3. I was thinking dylib, but wasm is also an interesting idea. I'd need to do more research on how to do this/what would be best, to be honest
4. I think as input, if it just received the SgNode(s) from the previous matched rule (in this example, `COMPONENT` and `ARGS` this would be enough information to do a lot of stuff. E.g. read node's document range to query for the symbol's definition

**Comment by michaelangeloio** [comment]
+1 to this! 

We are building off of ast-grep with a bunch of custom logic (using rust APIs directly) and this could be a great way for us to contribute back. 

Relevant links:
- GitLab Code Parser: https://gitlab.com/groups/gitlab-org/-/epics/17516
- Ruby Parser example with basic data flow tracing: https://gitlab.com/gitlab-org/rust/gitlab-code-parser/-/merge_requests/1
- Knowledge Graph (the larger goal): https://gitlab.com/groups/gitlab-org/-/epics/17514

**Comment by samwightt** [comment]
I really like the idea of having `constraints` being extensible via plugins. There are cases when analyzing Angular code where I need to look at another file in order to tell something about some symbol in the current file. For example, an identifier is a component if in another file there's a class with the same name that has a `@Component()` decorator on it. When analyzing components, we might want to tell whether a certain variable is used in the template of that component or not (defined in a separate file). `constraints` extensibility would I think make it possible to do that stuff really easily.

For loading, part of me leans towards `wasm` cause in CI environments trying to compile a dylib and load it has been tricky already (compiling a treesitter grammar to use as a custom language requires setting things up weirdly). [`extism` is a good library for wasm plugin systems.](https://extism.org/) However, wasm would limit native tool access and might limit integrations with things like language-specific tooling.

**Comment by HerringtonDarkholme** [comment]
> I was thinking dylib, but wasm is also an interesting idea. I'd need to do more research on how to do this/what would be best, to be honest

> I think as input, if it just received the SgNode(s) from the previous matched rule (in this example, COMPONENT and ARGS this would be enough information to do a lot of stuff). E.g. read node's document range to query for the symbol's definition

Question number 3 and number 4 are related. Both wasm/dylib needs a stable ABI. Designing the input/output may impact the decision of choosing the runtime of a plugin.

**Comment by HerringtonDarkholme** [comment]
From #2382 


--------



# ⭐ Suggestion

According to [*Transformation Object*](https://ast-grep.github.io/reference/yaml/transformation.html), `ast-grep` currently supports four types of transformers: `replace`, `substring`, `convert`, `rewrite`.

I want to have another transformer `custom`, which allows us to convert the value of a meta variable using arbitrary UNIX command:

```yaml
transform:
    NEW:
        custom:
            source: $NAME
            command: ["/path/to/command", "arg1", "arg2", "$NAME"]
```

# 💻 Use Cases

While `replace` and `rewrite` already give us much flexibility, `custom` makes it possible to do *anything*.

Possible use-cases are:

- integrate with existing tools whose functionality may or may not be reproduced purely by `ast-grep` but at least with much effort

- (maintainable and easy-to-write) `if` statement

- network calls (e.g. replacing a value with the latest Google Search result)

- apply formatter

- apply `jq` to a hard-coded JSON string

- calculate a complex math expression and replace the value with the result, making the runtime performance of a script better

- get the current datetime

- read env vars

# ⚠️ Security

We may also want to add `--disable-custom-transformer` CLI option (+ `sgconfig.yml` option) to completely disable the use of `custom` for better security.

For example, you can add the option when you apply a rule found on the Internet if you cannot trust the author and have no time to review the rule.
