### ISSUE TITLE
[feature] Support creating custom labels in codespan-reporting via metavariables.

### ISSUE THREAD

**Issue by samwightt** [ast-grep/ast-grep#1977]
# ⭐ Suggestion

It would be nice if `ast-grep` supported adding custom labels to a rule that `codespan-reporting` outputted. Yaml rules could have a `labels` field where the keys are metavariables (like the `constraints` field) and the values let you set the `codespan-reporting` labels.

Here's an example:

```yml
id: missing-component-decorator
message: You're using an Angular lifecycle method, but missing an Angular @Component() decorator.
language: TypeScript
rule:
  pattern:
    context: 'class Hi { $METHOD() { $$$_} }'
    selector: method_definition
  inside:
    pattern: 'class $KLASS $$$_ { $$$_ }'
    stopBy: end
    not:
      has:
        pattern: '@Component($$$_)'
constraints:
  METHOD:
    regex: ngOnInit|ngOnDestroy
labels:
  KLASS:
    kind: primary
    message: "This class is missing the decorator."
  METHOD:
    kind: secondary
    message: "This is an Angular lifecycle method."
```

# 💻 Use Cases

Right now when running `sg scan`, `ast-grep` will highlight all of the nodes matched by a rule. In some cases, this can make lint errors harder to read because more text is included than necessary. 

Additionally, there are some cases when writing rules where I would like to be able to provide a bit more context to the user, similar to how the Rust CLI provides info about type errors. For example, explaining what part of the highlighted code triggered the error could be helpful, or what piece of things are missing. For linter rules I write where there isn't an applicable `fix` rule (where there are multiple options for fixing) this would be very nice.
