### ISSUE TITLE
[feature] Allow fixes to target different parts of the code than matched node.

### ISSUE THREAD

**Issue by samwightt** [ast-grep/ast-grep#1985]
# ⭐ Suggestion

Some rules that I want to write require modifying parts of the file that are not the matched node. Often, I need to match against the `program` and write the `fix` from there. This causes the entire file to turn red in VSCode, which makes it impossible to tell what's wrong.

It would be nice if a `fix` could let you target a different node than the one the rule matches against. This could be done in one of two ways:

1. Add a `source` key to the `fix` object (similar to `transform`'s `source` key) that lets you pass a metavariable to be rewritten.
2. Add a key to the `fix` object (`select` maybe?) that lets you write a rule for what should be rewritten.

Example of the first approach:

```yml
id: async-function-deprecated
message: The `async` function has been renamed to `waitForAsync` and is deprecated. Use `waitForAsync` instead.
severity: error
rule:
  kind: call_expression
  inside:
    kind: program
    pattern: $PROGRAM
    stopBy: end
  pattern: 'async($ARGS)'
fix:
  source: $PROGRAM
  template: 'my fix that spans multiple lines here'
```

Example of second approach:

```yml
id: async-function-deprecated
message: The `async` function has been renamed to `waitForAsync` and is deprecated. Use `waitForAsync` instead.
severity: error
rule:
  kind: call_expression
  pattern: 'async($ARGS)'
fix:
  select:
    kind: program
  template: 'my fix that spans multiple lines here'
```

I'm not sure `select` feels like the right name here. But either of these solves the problem of needing to modify different parts of the code, and makes rewrites significantly more powerful. If this were implemented, users could write rules that modify imports, without having to change anything else about how rewrites are done.

# 💻 Use Cases

A common use case for this is updating imports. Imports are at the top of the file usually and nowhere near the part of the file we need to change. 

Example: Angular has an `async` function that can be used in tests like so:

```ts
import { async } from '@angular/testing';
// ...
beforeEach(async(() => {
  // Magically turns async code into sync code through Zone.js.
}))
```

This function has been deprecated and renamed to `waitForAsync`. I wrote a rule in our repo that banned the usage of the `async` function like this:

```yml
id: async-function-deprecated
message: The `async` function has been renamed to `waitForAsync` and is deprecated. Use `waitForAsync` instead.
severity: error
rule:
  kind: call_expression
  pattern: 'async($ARGS)'
```

However, when I go to add a fix for the rule, I cannot update the import at the top of the file. The `async(() => {})` function node is matched perfectly, but I cannot modify anything outside of it. In order to write a fix for this, I'd have to rewrite the rule so that the target is `kind: program`, capture the entire program in a metavariable, use a rewriter or two to do the renames, etc.
