### ISSUE TITLE
[feature] Enable rules to match across multiple files

### ISSUE THREAD

**Issue by samwightt** [ast-grep/ast-grep#1988]
# ⭐ Suggestion

In some cases it would be nice for `ast-grep` to be able to match rules across multiple files instead of a single one. For example, when writing rules for Angular tests, sometimes we need to know if an identifier is an Angular component or not. The right way to do this is to find the identifier in another file (the component file), check if it's a class_declaration, and then check if that class_declaration has a `@Component($_)` decorator on it.

An initial but very shitty idea for this might look like:

```yml
rule:
  kind: identifier
  pattern: $IDENTIFIER
  otherFile: # This is not a good name lol
    kind: class_declaration
    has: # I'm just writing this out in the GitHub editor so I don't know if this is right.
      kind: identifier
      pattern: $IDENTIFIER
      stopBy: end
```

`otherFile` would signal to `ast-grep` to check if there is some other file where the given pattern matches. Metavariables would work across the `otherFile` boundary.

Obviously this wouldn't be perfect (it's not doing TS module resolution so if there are components that are named the same thing it would mistrigger), but for our purposes it would be pretty nice.

While there _was_ a naming convention for this (end the class name in 'Component', so `ButtonComponent`), the Angular team doesn't recommend doing this anymore. For this Angular-specific use case, the plugin system in #1963 could fulfill the same use case.

## Implementation ideas

Scanning for this could probably be done in the same single pass that `ast-grep` does right now. Each `otherFile` declaration basically creates its own rule that would need to be evaluated on each file, and each file would need the results for this rule stored somewhere. For example, in a hashmap. Then at the end of execution, the metavariables from the 'root' rule are checked against the metavariables stored in some hashmap (we don't care what the file is called for this, just that it exists and some rule matched for it). If there's a value there, the rule matches. Fixes would only be able to be done in one file though. This might also get memory-intensive on larger codebases.

# 💻 Use Cases

See the above example.
