### ISSUE TITLE
[feature] Add 'as' field to rule object.

### ISSUE THREAD

**Issue by samwightt** [ast-grep/ast-grep#1989]
# ⭐ Suggestion

GritQL has a nice thing where you can do:

```
`console.log($var)` as $console
```

The entire ast node matched by the expression will be stuck inside `$console`.

There's cases when writing `ast-grep` rules where I have a pattern already defined as a rule but I really want to also have the thing it matches be stuck inside a metavariable too. Right now I can do it like this but it's unergonomic:

```yml
rule:
  pattern: 'console.log($VAR)'
  any:
    - pattern: $CONSOLE
```

Instead if you could do:

```yml
rule:
  pattern: console.log($VAR)
  as: $CONSOLE
```

It would be a lot nicer. That removes the need for the extra condition.

# 💻 Use Cases

Few cases I guess:

- Sometimes when I'm doing transform rules I need to target a part of the rule that already has a pattern. Slightly nicer shorthand for this.
- `as: $VAR` feels better than `pattern: $VAR` for some reason lol.

(also sorry for the influx of feature requests on the repo lol)
