### ISSUE TITLE
[bug] Local util rules inherit parent scope when global util rules do not.

### ISSUE THREAD

**Issue by samwightt** [ast-grep/ast-grep#1994]
### Please read the FAQ for the bug you encountered.

- [x] I have read the existing FAQ

### ⏯ Playground Link

https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6InR5cGVzY3JpcHQiLCJxdWVyeSI6ImNsYXNzICQkJENCUzpcclxuICAgICcnJyREUycnJ1xyXG4gICAgJCQkQ0JcclxuIiwicmV3cml0ZSI6ImNsYXNzICQkJENCUzpcclxuICAgIFwiXCJcIiREU1wiXCJcIlxyXG4gICAgYmF0Y2hfbW9kZSA9IFRydWVcclxuICAgICQkJENCIiwic3RyaWN0bmVzcyI6InNtYXJ0Iiwic2VsZWN0b3IiOiJFUlJPUiIsImNvbmZpZyI6ImlkOiBuZy1jb21wb25lbnQtY2xhc3Ncbmxhbmd1YWdlOiBUeXBlU2NyaXB0XG51dGlsczpcbiAgbmFtZWQtaW1wb3J0OlxuICAgIGtpbmQ6IGltcG9ydF9zdGF0ZW1lbnRcbiAgICBoYXM6XG4gICAgICBmaWVsZDogc291cmNlXG4gICAgICBoYXM6XG4gICAgICAgIGtpbmQ6IHN0cmluZ19mcmFnbWVudFxuICAgICAgICBwYXR0ZXJuOiAkSU1QT1JUX1NPVVJDRVxuICAgIGFueTpcbiAgICAgIC0gaGFzOlxuICAgICAgICAgIGtpbmQ6IGlkZW50aWZpZXJcbiAgICAgICAgICBzdG9wQnk6IGVuZFxuICAgICAgICAgIGFsbDpcbiAgICAgICAgICAgIC0gcGF0dGVybjogJElNUE9SVF9JREVOVElGSUVSX05BTUVcbiAgICAgICAgICAgIC0gcGF0dGVybjogJElNUE9SVF9JREVOVElGSUVSXG4gICAgICAgICAgaW5zaWRlOlxuICAgICAgICAgICAga2luZDogaW1wb3J0X3NwZWNpZmllclxuICAgICAgICAgICAgZmllbGQ6IG5hbWVcbiAgICAgICAgICAgIG5vdDpcbiAgICAgICAgICAgICAgaGFzOlxuICAgICAgICAgICAgICAgIGZpZWxkOiBhbGlhc1xuICAgICAgICAgICAgICAgIHBhdHRlcm46ICRfXG4gICAgICAtIGhhczpcbiAgICAgICAgICBraW5kOiBpZGVudGlmaWVyXG4gICAgICAgICAgc3RvcEJ5OiBlbmRcbiAgICAgICAgICBwYXR0ZXJuOiAkSU1QT1JUX0lERU5USUZJRVJfTkFNRVxuICAgICAgICAgIGluc2lkZTpcbiAgICAgICAgICAgIGtpbmQ6IGltcG9ydF9zcGVjaWZpZXJcbiAgICAgICAgICAgIGZpZWxkOiBuYW1lXG4gICAgICAgICAgICBoYXM6XG4gICAgICAgICAgICAgIGZpZWxkOiBhbGlhc1xuICAgICAgICAgICAgICBwYXR0ZXJuOiAkSU1QT1JUX0lERU5USUZJRVJcbnJ1bGU6XG4gIGFueTpcbiAgICAtIGtpbmQ6IGNsYXNzX2RlY2xhcmF0aW9uXG4gICAgLSBraW5kOiBleHBvcnRfc3RhdGVtZW50XG4gICAgICBoYXM6IHsga2luZDogY2xhc3NfZGVjbGFyYXRpb24gfVxuICBoYXM6XG4gICAga2luZDogZGVjb3JhdG9yXG4gICAgcGF0dGVybjogJ0AkSU1QT1JUX0lERU5USUZJRVIoJCQkXyknXG4gICAgaW5zaWRlOlxuICAgICAga2luZDogcHJvZ3JhbVxuICAgICAgc3RvcEJ5OiBlbmRcbiAgICAgIGhhczpcbiAgICAgICAgbWF0Y2hlczogbmFtZWQtaW1wb3J0XG4gICAgICAgIHN0b3BCeTogZW5kXG5jb25zdHJhaW50czpcbiAgSU1QT1JUX0lERU5USUZJRVJfTkFNRTpcbiAgICByZWdleDogXkNvbXBvbmVudCRcbiAgSU1QT1JUX1NPVVJDRTpcbiAgICByZWdleDogXkBhbmd1bGFyL2NvcmUkIiwic291cmNlIjoiaW1wb3J0IHsgQ29tcG9uZW50IGFzIFRlc3RpbmcgfSBmcm9tICdAYW5ndWxhci9jb3JlJ1xuXG5AVGVzdGluZygpXG5AV2hhdGV2ZXJcbmV4cG9ydCBkZWZhdWx0IGNsYXNzIEV4YW1wbGVDb21wb25lbnQge1xuICAgIHNvbWV0aGluZyA9IG5ldyBCZWhhdmlvclN1YmplY3QoKTtcblxuICAgIG1ldGhvZCgpIHtcbiAgICAgICAgdGhpcy5hbm90aGVyLnBpcGUoXG4gICAgICAgICAgICB0YWtlVW50aWwodGhpcy5zb21ldGhpbmcpXG4gICAgICAgIClcbiAgICAgICAgdGhpcy51Z2gucGlwZShcbiAgICAgICAgICAgIHRha2VVbnRpbCh4ID0+IHggIT09IDUpXG4gICAgICAgIClcbiAgICB9XG5cbiAgICBuZ09uRGVzdHJveSgpIHtcbiAgICAgICAgdGhpcy5zb21ldGhpbmcuZW1pdCgpO1xuICAgIH1cbn0ifQ==

### 💻 Code

I'm having an issue where local util rule definitions inherit the metavariable scope of their parent rule, but global util rules do not.

I have a rule that I'm trying to write where I want to match whether a specific TS import is imported from a library and is a specific named export. For example, I want to be able to tell whether a decorator is the `Component` decorator from `@angular/core`.

In TS, imports can be the same name (`Component`) or they can be aliased. Syntax looks like this:

```ts
import { Component } from '@angular/core'
import { Component as SomethingElse } from '@angular/core'
```

I have a rule called `named-import` that lets me match against either of these:

```yml
id: named-import
language: TypeScript
rule:
  kind: import_statement
  has:
    field: source
    has:
      kind: string_fragment
      pattern: $IMPORT_SOURCE
  any:
    - has:
        kind: identifier
        stopBy: end
        all:
          - pattern: $IMPORT_IDENTIFIER_NAME
          - pattern: $IMPORT_IDENTIFIER
        inside:
          kind: import_specifier
          field: name
          not:
            has:
              field: alias
              pattern: $_
    - has:
        kind: identifier
        stopBy: end
        pattern: $IMPORT_IDENTIFIER_NAME
        inside:
          kind: import_specifier
          field: name
          has:
            field: alias
            pattern: $IMPORT_IDENTIFIER
```

Then inside of my rule for matching Angular components, I can add constraints to my metavariables and verify that they're the correct names:

```yml
id: ng-component-class
language: TypeScript
rule:
  matches: decorable-class
  has:
    kind: decorator
    pattern: '@$IMPORT_IDENTIFIER($$$_)'
    inside:
      kind: program
      stopBy: end
      has:
        matches: named-import
        stopBy: end
constraints:
  IMPORT_IDENTIFIER_NAME:
    regex: ^Component$
  IMPORT_SOURCE:
    regex: ^@angular/core$
```

This works fine if I add `named-import` as a local util rule under the `utils` key. But if I write it as a global util rule, suddenly I get an error about metavariables not being defined:

<img width="565" alt="Image" src="https://github.com/user-attachments/assets/53b52c08-b9a2-48d6-8dd1-1b40ddbe9f80" />

### 🙁 Actual behavior

I would expect scoping to either be one way or the other for both local and global util rules. Either local and global rules should share the parent metavariable scope, _or_ they should have their own metavariable scope. 

### 🙂 Expected behavior

It seems like a parsing error occurs because we validate that the metavariable has to be defined inside the same file.

**Comment by samwightt** [comment]
It might be good to add a separate feature request similar to #1298, but to allow util rules to have 'exports' or 'returns' or something.

**Comment by HerringtonDarkholme** [comment]
Hi, at the moment global util rule does not inherit scope. This is a intentional design decision because I don't want make finding meta-variable definition across different files.

The solution should be covered by https://github.com/ast-grep/ast-grep/issues/1298#issuecomment-2644208519 

>  allow util rules to have 'exports' or 'returns' 

Exports/returns can be achieved by allowing high-order rules as argument.

**Comment by HerringtonDarkholme** [comment]
For example, 
The util rule

```yml
id: named-import
language: TypeScript
arguments: [ import-source-arg-rule, import-ident-arg-rule ]
rule:
  kind: import_statement
  has:
    field: source
    has:
      kind: string_fragment
      pattern: $IMPORT_SOURCE
```

The components rule

```yaml
id: ng-component-class
language: TypeScript
rule:
  matches: decorable-class
 omitted....:
      has:
        matches: 
          named-import: # use global utils
            import-source-arg-rule: { pattern: $IMPORT_SOURCE }  # arg rule
            import-ident-arg-rule: { pattern: $IMPORT_IDENTIFIER_NAME }
        stopBy: end
constraints:
  IMPORT_IDENTIFIER_NAME:
    regex: ^Component$
  IMPORT_SOURCE:
    regex: ^@angular/core$
```
