### ISSUE TITLE
Consider adding syntax to allow refining `regex` rule matches with metavariables

### ISSUE THREAD

**Issue by bbannier** [ast-grep/ast-grep#1995]
Currently it is impossible to refine `regex` rule matches based on information captured elsewhere; in my concrete use case I would like to make use of a metavariable to only match regexps including it.

### Example
A possible use case is enforcing naming conventions, e.g.,

```javascript
// IDs of function-local variables should always start with the function name.
function fun() {
    var fun_x = 2; // NO MATCH INTENDED.
    var x = 1;     // WANT TO MATCH x here.
}
```

While I can extract IDs of the function and its local variables, there is no way to constrain matches based on their relationship.

```yaml
language: JavaScript
rule:
  kind: identifier
  pattern: $ID
  # FIXME: how to check $ID against $MOD so we only match if we do not find `/$FUN_.*/`?
  inside:
    kind: variable_declaration
    stopBy: end
    inside:
      kind: function_declaration
      stopBy: end
      has:
        kind: identifier
        pattern: $FUN
``` 

### Possible solution

Being able to further constrain the matcher for `ID` with a regexp would solve this for me. A naive idea would be to allow the string of a `regex` to access metavariables like e.g., `regex: $MOD_.*`, but this probably not a good API as it would inject arbitrary strings into what should be a valid regexp; a cleaner approach might be to instead expose regexp captures to the rule language by adding another variant for `regex` (similar to what is possible with e.g., `pattern`). An imaginary syntax for that could be:

```yaml
regex:
    selector: "(?<prefix>.*?_)?.*"  # String.
    captures:                       # Orderered list of pattern.
        - name: prefix              # String for capture group name.
          not:                      # Ordinary rule?
            pattern: $FUN
```
