### ISSUE TITLE
[feature] Add tracing for YAML rule execution

### ISSUE THREAD

**Issue by samwightt** [ast-grep/ast-grep#2001]
# ⭐ Suggestion

Sometimes when I'm writing a complicated rule, it can be hard to figure out why it's not working. From looking through the code I know _sort of_ how YAML rules are evaluated, but it's still tricky to figure that out.

It would be nice if there was a way to trace rule execution on a specific input file. This would help users better understand how `ast-grep` works internally and debug what's going on in more complicated rules.

In my head, I'm thinking that a big JSON object could be outputted that could then be read by something like the playground. Basically just a flamegraph? But it would need additional context added onto it. Specifically what I've needed:

- What nodes are matched by the specific rule (in text)
- What the metavariables at that specific step are
- ??

One of these trees would be outputted for each match.

This would allow a new pane in the playground to be created where you click a 'debug' button and you can switch through these call stacks / debug traces like you can switch through metavariables. 

# 💻 Use Cases

Given how vague this issue has been it's probably better if I give examples lol.

I have this rule (note: it's kind of long) that I was trying to write:

```yml
id: no-dupe-else-if
language: TypeScript
severity: error
message: This condition is already evaluated previously.
rule:
  pattern: $CONDITION
  any:
    - kind: identifier
      any:
        - inside:
            kind: binary_expression
            all:
              - has:
                  field: operator
                  regex: ^\&\&$
              - has:
                  field: operator
                  regex: ^\|\|
        - inside:
            kind: parenthesized_expression
  not:
    inside:
      kind: binary_expression
      stopBy:
        kind: if_statement
      has:
        field: operator
        regex: ^&&$
  inside:
    kind: if_statement
    pattern: $IF
    stopBy:
      any:
        - kind: else_clause
        - kind: statement_block
    inside:
      kind: else_clause
      inside:
        kind: if_statement
        stopBy: { kind: statement_block }
        not:
          pattern: $IF
        has:
          field: condition
          has:
            pattern: $CONDITION
            stopBy: end # Go all the way down...
            all:
              - pattern: $OTHER_CONDITION
            not:
              inside:
                kind: binary_expression
                stopBy: { kind: if_statement }
               
                # BELOW THIS IS THE PROBLEM
                has:
                  stopBy: neighbor
                  field: operator
                  regex: ^||$

```

I was having a brainfart and couldn't figure out why the last `has: { ... regex: ^||$ }` was causing some stuff to match and not others.

To debug this I had to go through and comment out small parts of the rule over and over, and then add them back on slowly. It wasn't until 15 mins in that I remembered that pipe is a regex thing and I have to escape it :/.

In this situation, it would've been helpful if I could've stepped through that last condition and seen what was being accepted and what was being rejected, and _why_. If I could've done that, I would've been able to see that the regex was causing some stuff not to be matched (top level conditions).
