### ISSUE TITLE
[feature] support esquery style selector in `kind` rule

### ISSUE THREAD

**Issue by HerringtonDarkholme** [ast-grep/ast-grep#2007]
# ⭐ Suggestion

See 
https://github.com/estools/esquery

Currently transformation and relational rules are pretty verbose.

For example:

```yaml
rule:
  kind: number
  inside:
    kind: arguments
    inside:
      kind: call_expression
```
We can refer to CSS syntax to simplify them.

# 💻 Use Cases
For relational rule, we can simplify using CSS selector syntax. https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_selectors

```yaml
rule:
  selector: call_expression > arguments > number
```
