### ISSUE TITLE
[feature] support objectStyle `libraryPath`

### ISSUE THREAD

**Issue by HerringtonDarkholme** [ast-grep/ast-grep#2013]
# ⭐ Suggestion

> How to add a custom language on all platforms? I.e what is the syntax to specify which parser to use on Linux, on Mac and Windows assuming I built 3 different shared libraries

https://github.com/ast-grep/ast-grep/discussions/419#discussioncomment-12916449

ast-grep can resolve the dynamic lib using the target triple defined by rust. https://github.com/dtolnay/target-triple

# 💻 Use Cases

```yml
libraryPath:
  aarch64-apple-darwin: darwin.so
  aarch64-unknown-linux-gnu: linux-gnu.so
  i686-pc-windows-msvc: windows.so
```
