### ISSUE TITLE
Allow testing rules which fail based on filename

### ISSUE THREAD

**Issue by thejcannon** [ast-grep/ast-grep#2021]
# ⭐ Suggestion

I'm looking at using `ast-grep`, and wanted to start easy: "use `action.yml` and not `action.yaml` for GitHub Actions Workflows".

That rule looks like:

```yml
id: dont-use-action-yaml
language: yaml
rule:
  kind: document
  inside:
    any:
      - kind: stream
      - kind: document
message: Use 'action.yml' instead of 'action.yaml' for GitHub Actions
severity: error
note: We prefer 'action.yml' as the standard filename
files:
  - "**/action.yaml"
```

But I'm not sure how exactly to test this as currently the tests only take in strings.

# 💻 Use Cases

I like testing! 🥺
