### ISSUE TITLE
[feature] Add `constraints` field to fixes.

### ISSUE THREAD

**Issue by samwightt** [ast-grep/ast-grep#2032]
# ⭐ Suggestion

It would be nice if fixes could be conditionally applied, similarly to how rules can be conditionally applied via the `constraints` field. This would look like:

```yml
id: no-arrow-function-method
language: TypeScript
severity: warning
rule:
  kind: public_field_definition
  pattern: $DEF
  has:
    kind: arrow_function
    field: value
fix:
  template: 'something'
  constraints:
    DEF:
      not: { has: { kind: type_annotation } } # Prevents fix from applying if the class field has a type annotation.
# Rest of rule def.
```

This would prevent the rule from showing up as one of the fixes in VSCode or the terminal (now that #1603 is closed).

# 💻 Use Cases

At work a bunch of new devs are joining, and some of them are writing Angular code using arrow functions. In our codebase the pattern is to use method declarations instead of arrow functions as arrow functions combined with Angular can have unexpected issues with `this` when subclassing. 

I have a (pretty shitty but working) rule that matches arrow functions in a method and has a fix for converting them to methods ([playground link](https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6InR5cGVzY3JpcHQiLCJxdWVyeSI6ImNsYXNzICQkJENCUzpcclxuICAgICcnJyREUycnJ1xyXG4gICAgJCQkQ0JcclxuIiwicmV3cml0ZSI6ImNsYXNzICQkJENCUzpcclxuICAgIFwiXCJcIiREU1wiXCJcIlxyXG4gICAgYmF0Y2hfbW9kZSA9IFRydWVcclxuICAgICQkJENCIiwic3RyaWN0bmVzcyI6InNtYXJ0Iiwic2VsZWN0b3IiOiJFUlJPUiIsImNvbmZpZyI6ImlkOiBuby1hcnJvdy1mdW5jdGlvbi1tZXRob2Rcbmxhbmd1YWdlOiBUeXBlU2NyaXB0XG5zZXZlcml0eTogd2FybmluZ1xucnVsZTpcbiAga2luZDogcHVibGljX2ZpZWxkX2RlZmluaXRpb25cbiAgcGF0dGVybjogJERFRlxuICBoYXM6XG4gICAga2luZDogYXJyb3dfZnVuY3Rpb25cbiAgICBmaWVsZDogdmFsdWVcbmZpeDpcbiAgJEFDVFVBTF9ERUZcbnRyYW5zZm9ybTpcbiAgQUNUVUFMX0RFRjpcbiAgICByZXdyaXRlOlxuICAgICAgcmV3cml0ZXJzOlxuICAgICAgICAtIGJyYWNrZXQtYm9keVxuICAgICAgICAtIGNvbnZlcnQtbWV0aG9kXG4gICAgICAgIC0gcmVtb3ZlLWFycm93XG4gICAgICBzb3VyY2U6ICRERUZcbnJld3JpdGVyczpcbiAgLSBpZDogYnJhY2tldC1ib2R5XG4gICAgcnVsZTpcbiAgICAgIHBhdHRlcm46ICRFWFBSXG4gICAgICBub3Q6XG4gICAgICAgIGtpbmQ6IHN0YXRlbWVudF9ibG9ja1xuICAgICAgaW5zaWRlOlxuICAgICAgICBraW5kOiBhcnJvd19mdW5jdGlvblxuICAgICAgICBmaWVsZDogYm9keVxuICAgIGZpeDogfFxuICAgICAge1xuICAgICAgICByZXR1cm4gJEVYUFJcbiAgICAgIH1cbiAgLSBpZDogY29udmVydC1tZXRob2RcbiAgICBydWxlOlxuICAgICAga2luZDogcHJvcGVydHlfaWRlbnRpZmllclxuICAgICAgcGF0dGVybjogJE1FVEhPRFxuICAgICAgaW5zaWRlOlxuICAgICAgICBraW5kOiBwdWJsaWNfZmllbGRfZGVmaW5pdGlvblxuICAgICAgICBwYXR0ZXJuOiAkREVGXG4gICAgICAgIGZpZWxkOiBuYW1lXG4gICAgICAgIGhhczpcbiAgICAgICAgICBmaWVsZDogdmFsdWVcbiAgICAgICAgICBwYXR0ZXJuOiAkVkFMVUVcbiAgICBmaXg6XG4gICAgICB0ZW1wbGF0ZTogJyRNRVRIT0QnXG4gICAgICBleHBhbmRFbmQ6XG4gICAgICAgIG5vdDpcbiAgICAgICAgICBraW5kOiBhcnJvd19mdW5jdGlvblxuICAtIGlkOiByZW1vdmUtYXJyb3dcbiAgICBydWxlOlxuICAgICAgcmVnZXg6ID0+XG4gICAgICBpbnNpZGU6XG4gICAgICAgIGtpbmQ6IGFycm93X2Z1bmN0aW9uXG4gICAgZml4OiAnJyIsInNvdXJjZSI6ImNsYXNzIFRlc3Rpbmcge1xuICAgIG1ldGhvZCA9IChhcmcsIGFub3RoZXJBcmcpID0+IHRoaXMuc29tZXRoaW5nKClcbiAgICBhbm90aGVyTWV0aG9kID0gKGFyZyk6IHN0cmluZyA9PiB0aGlzLnNvbWV0aGluZygpXG4gICAgZXZlbk1vcmVNZXRob2RzID0gKHVnaGdoKSA9PiB7XG4gICAgICAgIHJldHVybiB0aGlzLnNvbWV0aGluZygpXG4gICAgfVxuICAgIG1ldGhvZFdpdGhTdHJpbmcgPSAoYXNkZiwgYXNkZmxqLCBhc2RmbGtqd2VyKTogc3RyaW5nID0+IHtcbiAgICAgICAgcmV0dXJuIHRoaXMuYW5vdGhlclRoaW5nKClcbiAgICB9XG4gICAgcHJpdmF0ZSByZWFkb25seSBzb21ldGhpbmcgPSAoKTogc3RyaW5nID0+IHtcbiAgICAgICAgcmV0dXJuIHRoaXMuc29tZXRoaW5nRWxzZSgpO1xuICAgIH1cblxuICAgIHNvbWV0aGluZzogKCkgPT4gc3RyaW5nID0gKCkgPT4gdGhpcy5zb21ldGhpbmcoKVxufSJ9)):

```yml
id: no-arrow-function-method
language: TypeScript
severity: warning
rule:
  kind: public_field_definition
  pattern: $DEF
  has:
    kind: arrow_function
    field: value
fix:
  $ACTUAL_DEF
transform:
  ACTUAL_DEF:
    rewrite:
      rewriters:
        - bracket-body
        - convert-method
        - remove-arrow
      source: $DEF
rewriters:
  - id: bracket-body
    rule:
      pattern: $EXPR
      not:
        kind: statement_block
      inside:
        kind: arrow_function
        field: body
    fix: |
      {
        return $EXPR
      }
  - id: convert-method
    rule:
      kind: property_identifier
      pattern: $METHOD
      inside:
        kind: public_field_definition
        pattern: $DEF
        field: name
        has:
          field: value
          pattern: $VALUE
    fix:
      template: '$METHOD'
      expandEnd:
        not:
          kind: arrow_function
  - id: remove-arrow
    rule:
      regex: =>
      inside:
        kind: arrow_function
    fix: ''
```

This fix works in all cases _except_ for when a field definition has a type annotation for the arrow function, like:

```ts
class Example {
  method: SomeType = () => {} // SomeType gets erased, making `method` untyped suddenly
}
```

I still want the rule to alert when there is an arrow function, but leave it up to the dev to solve when there is a type definition like that.

If we had a constraints property on the `fix` object, I could do this:

```yml
fix:
  template: $ACTUAL_DEF
  constraints:
    DEF:
      not: { has: { kind: type_declaration } }
```

This would let the _rule_ match (allowing it to still show up in the IDE), but not show the fix.

# Alternatives

I could make two separate rules, but they'd have to have separate IDs and that might be slightly confusing to people. It's also duplicate code.

Something like #433 could allow me to _maybe_ fill in the types of the fields, but I'm not sure that would work super well.
