### ISSUE TITLE
[feature] Parametrized rules

### ISSUE THREAD

**Issue by pvdrz** [ast-grep/ast-grep#2034]
# ⭐ Suggestion

It would be great to have a way to parametrize rules so we can reuse them.

# 💻 Use Cases

## What do you want to use this for?

Basically, incremental refactors. As an example, lets say I have some Rust code with a trait:
```rust
trait Trait {
    fn foo();
    fn bar();
    fn baz();
}

// Trait` is implemented for several (maybe too many) types.
impl Trait for u8 {
    fn foo() {}
    fn bar() {}
    fn baz() {}
}

impl Trait for u64 {
    fn foo() {}
    fn bar() {}
    fn baz() {}
}
```

Now, I decide I want to change `foo` to be an `async` function. So I'd probably update the `Trait` item to do that manually and then use `ast-grep scan` with a rule like this:
```yml
rule:
  kind: function_item
  pattern: $FN 
  # Check that the function is called `foo`
  has: 
    kind: identifier
    regex: "^foo$"
  # Check that the function is not async already
  not:
    has:
      kind: function_modifiers
      regex: "^async$"
  # Check that the function is inside an `impl Trait` item
  inside:
    kind: declaration_list
    inside:
      kind: impl_item
      has:
        kind: type_identifier
        field: trait
        regex: "^Trait$"

fix: 'async $FN'
```
All nice and dandy, I can even do it interactively and incrementally catch any compilation errors that might arise.

But then I want to repeat this for a different method in the same trait, or with another trait. So I'd like to do something like:

```bash
$ ast-grep scan -r my_rule.yml --params="target_trait=Trait,target_fn=bar" .
```

Where `target_trait` and `target_fn` would be parameters of the rule that let me easily run this command with different targets.

## What shortcomings exist with current approaches?

The only approach that doesn't rely on other tools is manually updating the rule each time.

## What workarounds are you using in the meantime?

Writing shell scripts that use `--inline-rule` and interpolate the parameters I need into the rule.
