### ISSUE TITLE
[feature] Allow multiple metavariables (and/or arbitrary string) in `transformation.replace.source`

### ISSUE THREAD

**Issue by vergenzt** [ast-grep/ast-grep#2062]
# ⭐ Suggestion

I'd love if the `source` of a [`replace`-type transform](https://ast-grep.github.io/reference/yaml/transformation.html#replace) could allow more than one meta-variable, and perhaps other arbitrary text too! (*à la* [`fix` strings](https://ast-grep.github.io/reference/yaml/fix.html#string-fix))

E.g.:

```yaml
rule:
  kind: expression
  pattern: $_.myFunctionCall($$$)
  all:
  - any:
    - has: { stopBy: end, kind: foo }
      pattern: $MAYBE_FOO
    - regex: .*
  - any:
    - has: { stopBy: end, kind: bar }
      pattern: $MAYBE_BAR
    - regex: .*

transform:
  BAZ:
    replace:
      source: $FOO$BAR  # ← ‼️ this part does not work
      replace: (?s).+
      by: ReplacementStringIfFooOrBarMatches

fix: 'MyPrettyFunctionCall (btw also $BAZ)'
```

# 💻 Use Case

A useful pattern I've come up with to *optionally* match metavariables if a certain pattern shows up inside a larger pattern:

```yaml
...

rule:
  all:
  - kind: expression_statement  # ← main rule I'm matching
  - any:  # optionally match a chained `.required(true)` call inside the expression
    - pattern: $IS_REQUIRED
      has:
        stopBy: { kind: argument_list }
        pattern: '$_.required(true)'
    - regex: (?s).+  # match anything

transform:
  STRING_TO_INSERT_IF_REQUIRED:
    replace:
      source: $IS_REQUIRED
      replace: (?s).+
      by: ... # whatever string I want to insert into the final `fix` *only* if there's a `.required(true)` nested call

fix: ... $STRING_TO_INSERT_IF_REQUIRED ...
```

This works great!

But I'm finding myself wanting to do this if *any of a list of meta-variables* is non-empty.

My broader use case is that I'm trying to translate Java [argparse4j](https://github.com/argparse4j/argparse4j) `addArgument` calls (the library is basically a Java port of Python's `argparse`) into Python `@dataclass` type annotations. 🙃 (It's overkill but I'm having fun with it...)

This specific feature will be helpful with constructing the type annotations, which can end up being defined based on multiple different matched subpatterns within the main pattern.

I'm not sure of another way to do this, other than to stop using this pattern and extract separate `rewriters` for each optional subpart. 😕 That gets messy though -- I've already got ~half a dozen rewriters in this rule. 😅 

Not a huge priority, but it seemed like it'd be easy to add so I figured I'd file the request. 🙂 Thanks for making this tool!

**Comment by vergenzt** [comment]
Looking through the codebase, I see that `MetaVariable` is a generic type passed as the type of `source` for all four transform configs:

- https://github.com/ast-grep/ast-grep/blob/a5a011b3c6add149df9da410ae5a272f96832019/crates/config/src/transform/mod.rs#L53
- https://github.com/ast-grep/ast-grep/blob/a5a011b3c6add149df9da410ae5a272f96832019/crates/config/src/transform/trans.rs#L117-L120


... so it sounds like if this change were to happen it would have to affect (or at least be easiest if it affects) all transform types?

**Comment by HerringtonDarkholme** [comment]
> this change were to happen it would have to affect (or at least be easiest if it affects) all transform types

yes. and mltuple metavariables do not make sense for `rewrite`
I think a better way for two replaced string and merge them together in the fix string.

```yaml
transform:
  BAZ:
    replace:
      source: $FOO
      replace: (?s).+
      by: ReplacementStringIfFooOrBarMatches
  QUX: replace($BAR, replace="(?s).+", by=ReplacementStringIfFooOrBarMatches)
fix:
  $BAZ$QUX
```
