### ISSUE TITLE
[feature] report error if a field is null

### ISSUE THREAD

**Issue by HerringtonDarkholme** [ast-grep/ast-grep#241]
Consider this rule

```yml
rule:
  all:
    - not:
      kind: program # should indent
```

is probably wrong because `not` rule's value is `null` instead of `kind`.

This is the ugly part of yaml. We can mitigate by https://stackoverflow.com/questions/44331037/how-can-i-distinguish-between-a-deserialized-field-that-is-missing-and-one-that

related #240
