### ISSUE TITLE
[feature] add a new composite rule for referencing existing rule

### ISSUE THREAD

**Issue by HerringtonDarkholme** [ast-grep/ast-grep#251]
It is hard to reuse rule in yaml. So we need to somehow reinvent code reuse in yaml. :(

```yml
rule:
  reference: existing-rule-id
```

Note the `reference` atomic rule also unlocks recursive rule

```yml
id: is-constant-node
rule:
  any:
     - kind: literal
     - kind: unary_expression
        has:
           stopBy: neighbor
           reference: is-constant-node
```
