### ISSUE TITLE
[feature] add thrift support

### ISSUE THREAD

**Issue by HerringtonDarkholme** [ast-grep/ast-grep#255]
https://docs.rs/tree-sitter-thrift/latest/tree_sitter_thrift/

**Comment by HerringtonDarkholme** [comment]
Example usage: find fields without comments.

```yml
id: no-field-commend
message: field should have comment.
severity: error
language: Thrift
rule:
  kind: field
  not:
    follows:
      kind: comment
```

<img width="625" alt="image" src="https://user-images.githubusercontent.com/2883231/219539693-3fa46192-1e1d-4166-a583-4117a0d196c3.png">
