### ISSUE TITLE
[bug] sometimes there will be panic

### ISSUE THREAD

**Issue by HerringtonDarkholme** [ast-grep/ast-grep#269]
<img width="974" alt="image" src="https://user-images.githubusercontent.com/2883231/221345986-e49b799a-5173-4ff4-9697-e543454b4f91.png">

Caused by racy condition.

**Comment by HerringtonDarkholme** [comment]
Minimal Reproduction
```yml
rule:
  matches: accessor-name
utils:
  accessor-name:
    matches: member-name
    regex: whatever
  member-name:
    kind: identifier

```
