### ISSUE TITLE
[bug] indirect cyclic dependencies are not reported

### ISSUE THREAD

**Issue by HerringtonDarkholme** [ast-grep/ast-grep#272]
```yml
utils:
  rule-a:
    matches: rule-b
  rule-b:
    matches: rule-a
```

This should be an error
