### ISSUE TITLE
[Question] Does the `inside` field support any nested levels and metaword references?

### ISSUE THREAD

**Issue by magic-akari** [ast-grep/ast-grep#316]
```JavaScript
export function foo() {
  foo = 1;
  bar = 2;

  if (x) {
    foo = 2;
  } else {
    foo = 3;
  }
}
```

```yaml
rule:
  pattern: $NAME
  kind: identifier
  inside:
    kind: assignment_expression
    field: left
    inside:
      pattern: export function $NAME($$$) { $$$ }

```

I am attempting to match every identifier of the assignment target `foo` within the export named function.

[playground](https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6ImphdmFzY3JpcHQiLCJxdWVyeSI6ImNvbnNvbGUubG9nKCRNQVRDSCkiLCJjb25maWciOiJydWxlOlxuICBwYXR0ZXJuOiAkTkFNRVxuICBraW5kOiBpZGVudGlmaWVyXG4gIGluc2lkZTpcbiAgICBraW5kOiBhc3NpZ25tZW50X2V4cHJlc3Npb25cbiAgICBmaWVsZDogbGVmdFxuICAgIGluc2lkZTpcbiAgICAgIHBhdHRlcm46IGV4cG9ydCBmdW5jdGlvbiAkTkFNRSgkJCQpIHsgJCQkIH1cbiIsInNvdXJjZSI6ImV4cG9ydCBmdW5jdGlvbiBmb28oKSB7XG4gIGZvbyA9IDE7XG4gIGJhciA9IDI7XG5cbiAgaWYgKHgpIHtcbiAgICBmb28gPSAyO1xuICB9IGVsc2Uge1xuICAgIGZvbyA9IDM7XG4gIH1cbn1cbiJ9)

## keyword 

- stopBy
- relational rule
- inside
- nested levels
