### ISSUE TITLE
[bug] replace does not work on Python playground

### ISSUE THREAD

**Issue by HerringtonDarkholme** [ast-grep/ast-grep#395]
```yaml
rule:
  pattern: '$A = lambda: $B'
fix:
  '$A + $B'
```
