### ISSUE TITLE
[feature] Test rule fix

### ISSUE THREAD

**Issue by q0w** [ast-grep/ast-grep#429]
Support snapshot testing for rule fixes.

**Comment by HerringtonDarkholme** [comment]
Thanks for reporting! 
Do you have any suggestion on the syntax of rule fixing?
Say, in the spec-test.yml

```yml
fix:
  - source: a = 123
     fix: b = 456
```
