### ISSUE TITLE
[perf]

### ISSUE THREAD

**Issue by HerringtonDarkholme** [ast-grep/ast-grep#449]
# ⭐ Suggestion

We can use ahash to improve HashMap performance. ast-grep does not need cryptographically good hash.

# 💻 Use Cases

Use this rule to find potential refactoring.

```yaml
id: replace-hash
message: use ahash?
severity: info
language: Rust
rule:
  pattern: use std::collections::HashMap;
  not:
    inside:
      stopBy: end
      pattern: mod test { $$$ }
```
