### ISSUE TITLE
Multi Meta Variable  "lookbehinds" not captured on variable constraint

### ISSUE THREAD

**Issue by mkatychev** [ast-grep/ast-grep#523]
# ⏯ Playground Link
[Playground link with relevant code](https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6InJ1c3QiLCJxdWVyeSI6IiIsInJld3JpdGUiOiJsb2dnZXIubG9nKCRNQVRDSCkiLCJjb25maWciOiJpZDogcGF0aF9yZXBsYWNlXG5sYW5ndWFnZTogcnVzdFxuXG5ydWxlOlxuICBwYXR0ZXJuOiB1c2UgY3JhdGU6OnskJCRBLCAkTVlfUEFUSCwgJCQkQn07XG5jb25zdHJhaW50czpcbiAgTVlfUEFUSDpcbiAgICByZWdleDogXCIoTXlNYXRjaHxNeU90aGVyTWF0Y2gpXCJcbiIsInNvdXJjZSI6InVzZSBjcmF0ZTo6e015TWF0Y2gsIEZvbywgQmFyfTtcbnVzZSBjcmF0ZTo6e1ByZWNlZGVudCwgTXlNYXRjaCwgRm9vLCBCYXJ9O1xudXNlIGNyYXRlOjp7TXlPdGhlck1hdGNoLCBGb28sIEJhcn07In0=)

# 💻 Code

Code:

```rust
use crate::{MyMatch, Foo, Bar};
use crate::{Precedent, MyMatch, Foo, Bar};
use crate::{MyOtherMatch, Foo, Bar};
```

Pattern:

```yml
id: path_replace
language: rust

rule:
  pattern: use crate::{$$$A, $MY_PATH, $$$B};
constraints:
  MY_PATH:
    regex: "(MyMatch|MyOtherMatch)"
```

# 🙁 Actual behavior

A match is successful only if there is no `Precedent`
* Two matches: `MyMatch` on line 1 and `MyOtherMatch` on line 3.
* Only `$$$B` and `$MY_PATH` get bound

# 🙂 Expected behavior
* Three matches: `MyMatch` on line 1, `MyMatch` on line 2, and `MyOtherMatch` on line 3.
* `$$$A` `$MY_PATH` and `$$$B` get bound

`rule: pattern: "use crate::{$$$A, $MY_PATH, $$$B};"` pattern with a `constraints: MY_PATH: pattern: MyMatch` should behave the same way as  as `rule: pattern: "use crate::{$$$A, MyMatch, $$$B};"`

**Comment by HerringtonDarkholme** [comment]
Hi. This is an expected behavior. ast-grep's multi-metavar does not backtrack. 
So when there are two metavars, the first one will match lazily. Like a non-greedy repetition in regular expression.

The behavior is designed for performance.

If you want to find an item in a list, you can try using `inside`.

```yaml
id: path_replace
language: rust

rule:
  pattern: $MY_PATH
  kind: identifier
  inside:
    pattern: use crate::{$$$B};
    stopBy: end
constraints:
  MY_PATH:
    regex: "(MyMatch|MyOtherMatch)"

```

<img width="1039" alt="image" src="https://github.com/ast-grep/ast-grep/assets/2883231/7240bd88-8ce9-4fe6-8dba-1c810ee54704">

https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6InJ1c3QiLCJxdWVyeSI6IiIsInJld3JpdGUiOiJsb2dnZXIubG9nKCRNQVRDSCkiLCJjb25maWciOiJpZDogcGF0aF9yZXBsYWNlXG5sYW5ndWFnZTogcnVzdFxuXG5ydWxlOlxuICBwYXR0ZXJuOiAkTVlfUEFUSFxuICBraW5kOiBpZGVudGlmaWVyXG4gIGluc2lkZTpcbiAgICBwYXR0ZXJuOiB1c2UgY3JhdGU6OnskJCRCfTtcbiAgICBzdG9wQnk6IGVuZFxuY29uc3RyYWludHM6XG4gIE1ZX1BBVEg6XG4gICAgcmVnZXg6IFwiKE15TWF0Y2h8TXlPdGhlck1hdGNoKVwiXG4iLCJzb3VyY2UiOiJ1c2UgY3JhdGU6OntNeU1hdGNoLCBGb28sIEJhcn07XG51c2UgY3JhdGU6OntQcmVjZWRlbnQsIE15TWF0Y2gsIEZvbywgQmFyfTtcbnVzZSBjcmF0ZTo6e015T3RoZXJNYXRjaCwgRm9vLCBCYXJ9OyJ9
