### ISSUE TITLE
[feature] merge rule and test file

### ISSUE THREAD

**Issue by pd4d10** [ast-grep/ast-grep#527]
# ⭐ Suggestion

The current recommended way is to split the rule and test files into two folders: https://ast-grep.github.io/guide/test-rule.html#test-setup , which seems to be a little redundant (id, file name are quite similar)

How about merging them into one file? For example:

```yml
id: no-await-in-loop
message: Don't use await inside of loops
severity: warning
language: TypeScript
rule:
  all:
    - inside:
        any:
          - kind: for_in_statement
          - kind: while_statement
    - pattern: await $_

# tests placed here
test:
  valid:
    - for (let a of b) { console.log(a) }
    # .... more valid test cases
  invalid:
    - async function foo() { for (var bar of baz) await bar; }
    # .... more invalid test cases
```
