### ISSUE TITLE
[bug] `ast-grep scan -U` only applies one fix at a time

### ISSUE THREAD

**Issue by etiennebacher** [ast-grep/ast-grep#580]
# Playground

No link (I don't think I can use several rules in the playground?)

# 💻 Code

I followed the examples [here](https://ast-grep.github.io/catalog/rust/).

Code:

```rust
pub mod foo;
pub use foo::Foo;

num.to_string().chars().count()
```

Rule 1 (`dup_exports.yml`):
```yml
id: dup-exports
language: rust
severity: hint
rule:
  all:
     - pattern: pub use $B::$C;
     - inside:
        kind: source_file
        has:
          pattern: pub mod $A;
     - has:
        pattern: $A
        stopBy: end
fix: hello
```
Rule 2 (`usize.yml`):
```yml
id: ndigits-usize
language: rust
severity: hint
rule:
  all:
     - pattern: $NUM.to_string().chars().count()
fix: $NUM.checked_ilog10().unwrap_or(0) + 1
```

# 🙁 Actual behavior

Running `ast-grep scan -U` only applies the first rule. I have to rerun it to apply the second one.

# 🙂 Expected behavior

Following the [documentation for `scan` options](https://ast-grep.github.io/reference/cli.html#options-1), I thought that running `ast-grep scan -U` would have applied both rules at once. 

Maybe related to #513 and #539?
