### ISSUE TITLE
[feature] Put several rules in the same `.yml` file

### ISSUE THREAD

**Issue by etiennebacher** [ast-grep/ast-grep#583]
# ⭐ Suggestion

Unless I missed something, it's currently not possible to have several rules in the same `.yml` file. I think this would be a nice feature, maybe using `---` as delimiter between rules?

# 💻 Use Cases

Sometimes, a lot of lints can have very close rules/fixes/messages so it would be nice to be able to put them all in the same file instead of splitting them in many small files with a single rule. I don't think utility rules can solve this.

**Comment by HerringtonDarkholme** [comment]
I believe it is already supported now. https://github.com/ast-grep/ast-grep/blob/main/crates/config/src/lib.rs#L31-L41

But I have not tried/tested myself.

**Comment by etiennebacher** [comment]
I tried putting two rules in the same file and it returned an error:
```
✖ Caused by
╰▻ Fail to parse yaml as RuleConfig
╰▻ duplicate field `id`
```
If there's a specific delimiter to use I don't see it in the code.

**Comment by HerringtonDarkholme** [comment]
Can you paste the rule text? Multiple rules should have distinct ids.

**Comment by etiennebacher** [comment]
`foo.rs`

```rust
pub mod foo;
pub use foo::Foo;

num.to_string().chars().count()
```

`usize.yml`

```yml
id: ndigits-usize
language: rust
severity: hint
rule:
  all:
     - pattern: $NUM.to_string().chars().count()
fix: $NUM.checked_ilog10().unwrap_or(0) + 1

id: dup-exports
language: rust
severity: hint
rule:
  all:
     - pattern: pub use $B::$C;
     - inside:
        kind: source_file
        has:
          pattern: pub mod $A;
     - has:
        pattern: $A
        stopBy: end
fix: hello
```

**Comment by HerringtonDarkholme** [comment]
Try this one?

```yaml
id: ndigits-usize
language: rust
severity: hint
rule:
  all:
     - pattern: $NUM.to_string().chars().count()
fix: $NUM.checked_ilog10().unwrap_or(0) + 1

---

id: dup-exports
language: rust
severity: hint
rule:
  all:
     - pattern: pub use $B::$C;
     - inside:
        kind: source_file
        has:
          pattern: pub mod $A;
     - has:
        pattern: $A
        stopBy: end
fix: hello

```
