### ISSUE TITLE
[feature] support multiple YAML documents in playground

### ISSUE THREAD

**Issue by HerringtonDarkholme** [ast-grep/ast-grep#586]
# ⭐ Suggestion

Currently the playground can only support one YAML rule at a time. But sometimes it is useful to demonstrate multiple rules or test multiple-rule replacement at once.

We can use YAML's conventional separator `----` to separate multiple rules.

# 💻 Use Cases

```yml
id: dup-exports
language: rust
rule:
  pattern: pub use $B::$C;
fix: hello
---
id: ndigits-usize
language: rust
rule:
  all:
     - pattern: $NUM.to_string().chars().count()
fix: $NUM.checked_ilog10().unwrap_or(0) + 1
```

We can demonstrate the feature of multiple rules in one single file and  applying multiple fixes at a time.

related #580 #583
