### ISSUE TITLE
[bug] Unable to match C preproc_arg on playground but on CLI

### ISSUE THREAD

**Issue by chengyuhui** [ast-grep/ast-grep#587]
# ⏯ Playground Link

[Playground link with relevant code](https://ast-grep.github.io/playground.html#eyJtb2RlIjoiUGF0Y2giLCJsYW5nIjoiYyIsInF1ZXJ5IjoiI2RlZmluZSAkQSAkQlxyXG4iLCJyZXdyaXRlIjoiIiwiY29uZmlnIjoiaWQ6IG5vLWV4dGVybi1kZWNsYXJhdGlvbi1pbi1mdW5jdGlvblxubWVzc2FnZTogJzAxMDAwMDEwMTMwMDEwJ1xubGFuZ3VhZ2U6IENcbnJ1bGU6XG4gIGFsbDpcbiAgICAtIHBhdHRlcm46ICcjZGVmaW5lICRBICQkJEInXG4iLCJzb3VyY2UiOiIjcHJhZ21hIHBhY2tcbiNkZWZpbmUgaW50IGNoYXIifQ==)

# 💻 Code

Code:

```
#pragma pack
#define int char
```

Pattern:

```yml
id: no-redefine-types
message: '01000010130010'
language: C
rule:
  all:
    - pattern: '#define $A $B'
```

# 🙁 Actual behavior
`#define $A $B` does not match `#define int char`, nor does `#define $A $$$B` work.

Only `#define $$$AB` works, but this is not optimal.

# 🙂 Expected behavior
`#define $A $B` matches `#define int char`, as they look exactly the same, and generates the same tree.
