### ISSUE TITLE
[feature] `files` should override a language's extension-based detection and filtering

### ISSUE THREAD

**Issue by scheatkode** [ast-grep/ast-grep#601]
Hi, thank you for this awesome project !

The current language detection and file filtering approach is, as far as I could see in the code, extension-based. This is fine on its own, but breaks expectations when used with the `files` field in a rule.

# ⭐ Suggestion

In situations where the `files` field is defined within a rule, the hardcoded extensions should be overridden by the specified globs. This would allow to explicitly specify the files to operate on, irrespective of their extensions.

# 💻 Use Cases

```yaml
id: some-rule-name
message: A rule that concerns C++ header files with non-hardcoded extensions
language: cpp

# ...

files:
- "./**/*.h++"
```

```yaml
id: some-other-rule
message: A rule that concerns cake scripts in the "scripts" directory
language: csharp

# ...

files:
- "./scripts/**/*.cake"
```

**Comment by HerringtonDarkholme** [comment]
Hi scheatkode, thanks for trying out ast-grep.

I will consider if this is doable and desirable for users.

**Comment by HerringtonDarkholme** [comment]
Hi scheatkode, I found current ast-grep implementation does not support overriding language extension. 

However, I am trying to add `aliasLanguage` in configuration to support linking builtin languages to custom extensions.

**Comment by HerringtonDarkholme** [comment]
Proposal: adding `aliasLanguages` in `sgconfig.yml`.

Example

```yaml
aliasLanguages:
  cake:
    aliasOf: csharp
    extensions: [cake]
```

So the rule above can be written as 

```yaml
id: some-other-rule
message: A rule that concerns cake scripts in the "scripts" directory
language: cake

# ...

files:
- "./scripts/**/*.cake"
```

We also have similar scenarios for vue/svelte/astro where we can link them to HTML parsers.

```
aliasLanguages:
  vue:
    aliasOf: HTML
    extensions: [vue]
  svelte:
    aliasOf: HTML
    extensions: [svelete]
```

**Comment by HerringtonDarkholme** [comment]
Thank @scheatkode! The feature is under pilot testing and is not released yet. If you want to test it, you can try installing from source https://github.com/ast-grep/ast-grep#installation

**Comment by scheatkode** [comment]
After a bit of tweaking to figure out the correct config, this works exactly as expected. Thank you !

This made me aware of a missing case though. What about extension-less files ?

- `Makefile`
- `Dockerfile`
- `Taskfile`
- `BUILD`

Off the top of my head, these are a few valid files with no extensions.

For instance this doesn't work.
```yaml
# sgconfig.yml
aliasLanguages:
  build:
    aliasOf: Python
    extensions: ["","BUILD"]
```

```yaml
# rules/some-rule.yml
files:
- "./**/BUILD"
```

This diff seems to fix it, but I'm not familiar enough with Rust to know if it's a good idea.
```diff
diff --git a/crates/cli/src/lang/alias_lang.rs b/crates/cli/src/lang/alias_lang.rs
index 7c74e243d3ce..cb5b07e4ea2c 100644
--- a/crates/cli/src/lang/alias_lang.rs
+++ b/crates/cli/src/lang/alias_lang.rs
@@ -3,6 +3,7 @@ use ignore::types::{Types, TypesBuilder};
 use serde::{Deserialize, Serialize};
 
 use std::collections::HashMap;
+use std::ffi::OsStr;
 use std::ops::Deref;
 use std::path::Path;
 use std::str::FromStr;
@@ -74,7 +75,7 @@ impl AliasLang {
   }
 
   pub fn from_path<P: AsRef<Path>>(path: P) -> Option<Self> {
-    let ext = path.as_ref().extension()?.to_str()?;
+    let ext = path.as_ref().extension().unwrap_or(OsStr::new("")).to_str()?;
     let mapping = unsafe { &LANG_INDEX };
     mapping.iter().find_map(|(p, idx)| {
       if p == ext {
```
