### ISSUE TITLE
[feature] Allow deleting matched nodes in "fix"

### ISSUE THREAD

**Issue by kheyse-oqton** [ast-grep/ast-grep#602]
# ⭐ Suggestion

Current rule configuration allows a ["fix"](https://ast-grep.github.io/reference/yaml.html#fix) through replacement, but does not allow deletion of the matched nodes.

Allowed:
```yml
rule:
  kind: import_specifier
  regex: toReplace
fix: "hasBeenReplaced"
```

No effect:
```yml
rule:
  kind: import_specifier
  regex: toReplace
fix: 
```

# 💻 Use Cases

My goal is to remove all "importToRemove" from the below snippet.

```ts
import { importA, importB, importToRemove } from 'mylib';
import { importA, importToRemove, importB } from 'mylib';
import { importA, importToRemove } from 'mylib';
import { importC, importB } from 'mylib';
import { importToRemove } from 'mylib';
```

Closest I got is with 
```yml
rule:
  kind: import_specifier
  regex: ToRemove
fix: " "
```
which results in the invalid output
```ts
import { importA, importB,  } from "mylib";
import { importA, , importB } from "mylib";
import { importA,  } from "mylib";
import { importC, importB } from "mylib";
import {  } from "mylib";
```
instead of 
```ts
import { importA, importB } from "mylib";
import { importA,  importB } from "mylib";
import { importA } from "mylib";
import { importC, importB } from "mylib";
import {  } from "mylib";
```
