### ISSUE TITLE
[feature] Implement more powerful fix methods

### ISSUE THREAD

**Issue by HerringtonDarkholme** [ast-grep/ast-grep#656]
This is an epic issue to track more powerful fix methods

- [x] Change fix option from string to Fixer 
- [x] Implement selection expander
- [ ] #1105
- [x] update json schema
- [x] update doc

**Comment by HerringtonDarkholme** [comment]
Expand node selection range

# ⭐ Suggestion

ast-grep rule can only fix one target node at one time. This works fine for function statement/calls but it has always been problematic for list-item like items in an array, key-value pairs in a dictionary. We cannot delete an item because we also need to delete the surrounding comma.

Similarly, the problem also applies to a statement if it has a semicolon.

# 💻 Use Cases
Add the `expandTarget` field to rule.

```
language: python
rule:
  kind: pair
  has:
   find: regex
expandTarget:
  forward: 1 # forward one byte?
  forward: 
    regex: , # or a rule object
fix: '' # delete
```

related: https://github.com/ast-grep/ast-grep/discussions/746
