### ISSUE TITLE
[bug] `sg scan -U` fails because of leading and trailing empty lines

### ISSUE THREAD

**Issue by etiennebacher** [ast-grep/ast-grep#668]
Hello, this is a follow-up on #580, thanks a lot for having implemented it!

# ⏯ Playground Link

The issue doesn't appear in the playground: [link](https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6InB5dGhvbiIsInF1ZXJ5IjoiIiwicmV3cml0ZSI6ImxvZ2dlci5sb2coJE1BVENIKSIsImNvbmZpZyI6ImlkOiBjaGFuZ2VfZGVmXG5sYW5ndWFnZTogUHl0aG9uXG5ydWxlOlxuICBwYXR0ZXJuOiB8XG4gICAgZGVmIGZvbygkWCk6XG4gICAgICAkJCRTXG5maXg6IHwtXG4gIGRlZiBiYXooJFgpOlxuICAgICQkJFNcblxuLS0tICMgdGhpcyBpcyBZQU1MIGRvYyBzZXBhcmF0b3IgdG8gaGF2ZSBtdWx0aXBsZSBydWxlcyBpbiBvbmUgZmlsZVxuXG5pZDogY2hhbmdlX3BhcmFtXG5ydWxlOlxuICBwYXR0ZXJuOiBmb28oJFgpXG5maXg6IGJheigkWCkiLCJzb3VyY2UiOiJcbmRlZiBmb28oeCk6XG4gICAgcmV0dXJuIHggKyAxXG5cbnkgPSBmb28oMilcbnByaW50KHkpIn0=)

# 💻 Code

This uses the same code and rules as in [this section](https://ast-grep.github.io/guide/rewrite-code.html#using-fix-in-yaml-rule) of the docs.

Code (it is important that there's an empty line at the beginning and at the end):

```python

def foo(x):
    return x + 1

y = foo(2)
print(y)

```

Pattern:

```yml
id: change_def
language: Python
rule:
  pattern: |
    def foo($X):
      $$$S
fix: |-
  def baz($X):
    $$$S

--- # this is YAML doc separator to have multiple rules in one file

id: change_param
rule:
  pattern: foo($X)
fix: baz($X)
```

# 🙁 Actual behavior

Running `sg scan -U` deletes the leading and trailing empty lines and returns this:
```python
dedef baz(x):
  return x + 1

y = fobaz(2)print(y)

```

# 🙂 Expected behavior

The result should be as in the docs and shouldn't depend on whether there are empty lines at the beginning or at the end.
