### ISSUE TITLE
[bug] follows/precedes does not seem to work for golang

### ISSUE THREAD

**Issue by debugloop** [ast-grep/ast-grep#673]
# ⏯ Playground Link

[Playground link with relevant code](https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6ImdvIiwicXVlcnkiOiIiLCJyZXdyaXRlIjoiIiwiY29uZmlnIjoicnVsZTpcbiAgYWxsOlxuICAgIC0ga2luZDogY2FsbF9leHByZXNzaW9uXG4gICAgLSBmb2xsb3dzOlxuICAgICAgICBraW5kOiBjYWxsX2V4cHJlc3Npb24iLCJzb3VyY2UiOiJmdW5jIG1haW4oKSB7XG4gIGZtdC5QcmludGxuKFwiaGVsbG8gd29ybGRcIilcbiAgZm10LlByaW50bG4oXCJoZWxsbyB3b3JsZFwiKVxufSJ9)

# 💻 Code

Code:

```go
func main() {
  fmt.Println("hello world")
  fmt.Println("hello world")
}
```

Pattern:

```yml
rule:
  all:
    - kind: call_expression
    - follows:
        kind: call_expression
```

# 🙁 Actual behavior

Neither `call_expression` is matched.

# 🙂 Expected behavior

One `call_expression` is matched, depending on whether `follows` or `precedes` is set in the YAML.
