### ISSUE TITLE
[bug] transform: convert to kebab-case introduces incorrect hyphen at the start of the variable

### ISSUE THREAD

**Issue by debugloop** [ast-grep/ast-grep#674]
# ⏯ Playground Link

[Playground link with relevant code](https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6ImdvIiwicXVlcnkiOiJsb2dydXMuRmllbGRzeyQkJH0iLCJyZXdyaXRlIjoiIiwiY29uZmlnIjoicnVsZTpcbiAgcGF0dGVybjpcbiAgICBjb250ZXh0OiAneyBzbG9nLiRGVU5DKCRLRVksICRWQUxVRSkgfSdcbiAgICBzZWxlY3RvcjogY2FsbF9leHByZXNzaW9uXG5jb25zdHJhaW50czpcbiAgRlVOQzpcbiAgICByZWdleDogJ14oU3RyaW5nfEludDY0fEludHxVaW50NjR8RmxvYXQ2NHxCb29sfFRpbWV8RHVyYXRpb258QW55KSQnXG50cmFuc2Zvcm06XG4gIE5FV19LRVk6XG4gICAgY29udmVydDpcbiAgICAgIHNvdXJjZTogJEtFWVxuICAgICAgdG9DYXNlOiBrZWJhYkNhc2VcbiAgICAgIHNlcGFyYXRlZEJ5OiBbY2FzZUNoYW5nZV1cbmZpeDogJ3Nsb2cuJEZVTkMoJE5FV19LRVksICRWQUxVRSknIiwic291cmNlIjoicGFja2FnZSBtYWluXG5cbmltcG9ydCBcImZtdFwiXG5cbmZ1bmMgbWFpbigpIHtcbiAgc2xvZy5BbnkoXCJOYW1lXCIsIGYuTmFtZSlcbn0ifQ==)

# 💻 Code

Code:

```go
package main

import "fmt"

func main() {
  slog.Any("Name", f.Name)
}
```

Pattern:

```yml
rule:
  pattern:
    context: '{ slog.$FUNC($KEY, $VALUE) }'
    selector: call_expression
constraints:
  FUNC:
    regex: '^(String|Int64|Int|Uint64|Float64|Bool|Time|Duration|Any)$'
transform:
  NEW_KEY:
    convert:
      source: $KEY
      toCase: kebabCase
      separatedBy: [caseChange]
fix: 'slog.$FUNC($NEW_KEY, $VALUE)'
```

# 🙁 Actual behavior

`NEW_KEY == "-name"`

# 🙂 Expected behavior

`NEW_KEY == "name"`

It appears the parser starts out in "lower" state and interprets a capital at the start as a `caseChange` as well, leading to the introduction of the `-`
