### ISSUE TITLE
[feature] support quantity/order rule

### ISSUE THREAD

**Issue by HerringtonDarkholme** [ast-grep/ast-grep#676]
# ❓Problem Now
 It is hard to find nodes without children or nodes appearing in specific positions.
For example, user may want to match the first/last argument of an argument list, or to find a node with more than three children (e.g. too many arguments or too many statements).

Though it is possible to use `precedes/follows` and  recursive `matches` to emulate node position rules, the procedure is definitely excruciating. (I can testify this as the author).

# ⭐ Suggestion
Support one additional rule:

```yaml
rule:
  nthChild: 3       
  nthChild: 2n+1
  nthChild:
    position: 3 # or An+B
    ofRule:    # rule object
      pattern: pattern-rule 
```

# 💻 Use Cases
1. Find the first/last argument
2. Find functions with too many statements
3. Find functions with too many arguments
4. Find an argument at specific position of an argument list
5. https://github.com/ast-grep/ast-grep/discussions/1192

Related issue https://github.com/ast-grep/ast-grep/discussions/675

# Design Decision
1. should nthChild only respets named nodes and skip unnamed nodes?
2. should we expose an option to specify named/unnamed rule?
