### ISSUE TITLE
[bug] `follows` documentation example works with js but not python

### ISSUE THREAD

**Issue by symphorien** [ast-grep/ast-grep#689]
# ⏯ Playground Link

https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6InB5dGhvbiIsInF1ZXJ5IjoiY29uc29sZS5sb2coJE1BVENIKSIsInJld3JpdGUiOiIiLCJjb25maWciOiIjIFlBTUwgUnVsZSBpcyBtb3JlIHBvd2VyZnVsIVxuIyBodHRwczovL2FzdC1ncmVwLmdpdGh1Yi5pby9ndWlkZS9ydWxlLWNvbmZpZy5odG1sI3J1bGVcbnJ1bGU6XG4gIGFsbDpcbiAgICAtIHBhdHRlcm46IGNvbnNvbGUubG9nKCdoZWxsbycpXG4gICAgLSBmb2xsb3dzOlxuICAgICAgICBwYXR0ZXJuOiBjb25zb2xlLmxvZygnd29ybGQnKVxuIiwic291cmNlIjoiY29uc29sZS5sb2coJ2hlbGxvJykgIyBkb2VzIG5vdCBtYXRjaFxuY29uc29sZS5sb2coJ3dvcmxkJylcbmNvbnNvbGUubG9nKCdoZWxsbycpICMgbWF0Y2hlcyEhIn0=

# 💻 Code

Code:

```python
console.log('hello') # does not match
console.log('world')
console.log('hello') # matches!!
```

Pattern:

```yml
# YAML Rule is more powerful!
# https://ast-grep.github.io/guide/rule-config.html#rule
rule:
  all:
    - pattern: console.log('hello')
    - follows:
        pattern: console.log('world')
```

# 🙁 Actual behavior

no match

# 🙂 Expected behavior

I expect a match. This example is a python port of the js example given in the documentation https://ast-grep.github.io/guide/rule-config/relational-rule.html#relational-rule-mnemonics
(playground link: https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6ImphdmFzY3JpcHQiLCJxdWVyeSI6ImNvbnNvbGUubG9nKCRNQVRDSCkiLCJyZXdyaXRlIjoiIiwiY29uZmlnIjoiIyBZQU1MIFJ1bGUgaXMgbW9yZSBwb3dlcmZ1bCFcbiMgaHR0cHM6Ly9hc3QtZ3JlcC5naXRodWIuaW8vZ3VpZGUvcnVsZS1jb25maWcuaHRtbCNydWxlXG5ydWxlOlxuICBhbGw6XG4gICAgLSBwYXR0ZXJuOiBjb25zb2xlLmxvZygnaGVsbG8nKTtcbiAgICAtIGZvbGxvd3M6XG4gICAgICAgIHBhdHRlcm46IGNvbnNvbGUubG9nKCd3b3JsZCcpO1xuIiwic291cmNlIjoiY29uc29sZS5sb2coJ2hlbGxvJyk7IC8vIGRvZXMgbm90IG1hdGNoXG5jb25zb2xlLmxvZygnd29ybGQnKTtcbmNvbnNvbGUubG9nKCdoZWxsbycpOyAvLyBtYXRjaGVzISEifQ== ) The js example does work fine.

**Comment by HerringtonDarkholme** [comment]
Hi, thanks for trying ast-grep.

This is an expected match. `console.log($A)` in Python is by default parsed as a `call_expression` in stead of `statement_expression`.

To control how pattern is parsed, you can try object-style pattern. https://ast-grep.github.io/guide/rule-config/atomic-rule.html#pattern

```yaml
rule:
  pattern: 
    context: console.log('hello')
    selector: expression_statement
  follows:
    pattern: 
      context: console.log('world')
      selector: expression_statement

```

https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6InB5dGhvbiIsInF1ZXJ5IjoiY29uc29sZS5sb2coJE1BVENIKSAgICAgIDtcblxuXG4iLCJyZXdyaXRlIjoiIiwiY29uZmlnIjoiIyBZQU1MIFJ1bGUgaXMgbW9yZSBwb3dlcmZ1bCFcbiMgaHR0cHM6Ly9hc3QtZ3JlcC5naXRodWIuaW8vZ3VpZGUvcnVsZS1jb25maWcuaHRtbCNydWxlXG5ydWxlOlxuICBwYXR0ZXJuOiBcbiAgICBjb250ZXh0OiBjb25zb2xlLmxvZygnaGVsbG8nKVxuICAgIHNlbGVjdG9yOiBleHByZXNzaW9uX3N0YXRlbWVudFxuICBmb2xsb3dzOlxuICAgIHBhdHRlcm46IFxuICAgICAgY29udGV4dDogY29uc29sZS5sb2coJ3dvcmxkJylcbiAgICAgIHNlbGVjdG9yOiBleHByZXNzaW9uX3N0YXRlbWVudFxuIiwic291cmNlIjoiY29uc29sZS5sb2coJ2hlbGxvJykgIyBkb2VzIG5vdCBtYXRjaFxuY29uc29sZS5sb2coJ3dvcmxkJylcbmNvbnNvbGUubG9nKCdoZWxsbycpICMgbWF0Y2hlcyEhIn0=
