### ISSUE TITLE
[bug] sg panics on a scan

### ISSUE THREAD

**Issue by zamazan4ik** [ast-grep/ast-grep#736]
# 🙁 Actual behavior

`sg scan ../../llvm-project` panics with the following error: https://gist.github.com/zamazan4ik/f7e89449c7418586b0190f67083a1ac2

`sgconfig.yml` content:
```
id: method_receiver
rule:
  pattern: $R.$METHOD($$$ARGS)
transform:
  MAYBE_COMMA:
    replace:
      source: $$$ARGS
      replace: '^.+'
      by: ', '
fix:
  $METHOD(&$R$MAYBE_COMMA$$$ARGS)
```

Complete copy and paste from https://ast-grep.github.io/catalog/c/ . By the way, if it reports about some missing fields - probably the examples should be updated on the website as well (just a guess).

# 🙂 Expected behavior

`sg scan` should not panic in this - it should just report an error about the configuration issues.

# Other information

* OS: Fedora 39
* Arch: x86-64
* Rust: 1.74
* `sg` version: locally built version with `cargo build --release` from the `main` branch with `76d845162185bed4a5b9a22de456f26e976af0a6` commit
