### ISSUE TITLE
AliasLanguages should report error when users define same extension twice

### ISSUE THREAD

**Issue by zhiyuanzmj** [ast-grep/ast-grep#737]
# ⏯ Playground Link

[Playground link with relevant code](https://github.com/vue-macros/vue-macros-cli/blob/c992ac667c0d4d8ba7f1a17ad23ce9bdc2cc8981/src/sgconfig.yml#L5-L11)

# 💻 Code

Code:

```yml 
ruleDirs:
  - rules
utilDirs:
  - utils
aliasLanguages:
  vue:
    aliasOf: html
    extensions: [vue]
  vueTsx:
    aliasOf: tsx
    extensions: [vue]
```

# 🙁 Actual behavior
The second alias language will be ignored.

# 🙂 Expected behavior
AliasLanguages should report error when users define same extension twice

**Comment by zhiyuanzmj** [comment]
You can define two config to resolved it:
1. `sgconfig.yml` for html.
```yml
ruleDirs:
  - rules
utilDirs:
  - utils
aliasLanguages:
  vue:
    aliasOf: html
    extensions: [vue]
  vueTsx:
    aliasOf: tsx
    extensions: []
```

2. `sgconfig-tsx.yml` for tsx.
```yml
ruleDirs:
  - rules
utilDirs:
  - utils
aliasLanguages:
  vue:
    aliasOf: html
    extensions: []
  vueTsx:
    aliasOf: tsx
    extensions: [vue]
```
