### ISSUE TITLE
[feature] Support conditional fixes

### ISSUE THREAD

**Issue by emosenkis** [ast-grep/ast-grep#779]
# ⭐ Suggestion

Make it easier to write multiple variants of a fix by enabling some parts of the fix to be conditional. This could be implemented as a new kind of transform or as new fix syntax.

# 💻 Use Cases

Example: I'm trying to write a fix that combines multiple decorators in Python into one mega-decorator:
```
@a("foo")
@b("bar")
@c("baz")
def func(...):
    body...

->

@magic(a_something="foo", b_something="bar", c_something="baz")
def func(...):
    body....
```

If I want to make this fix for all subsets of the three possible decorators, I can write utils to match each piece instead of repeating them, but I still need to write a rule and fix for every subset of (a, b, c).

With this feature, I would be able to write the fix once, making the arguments to `@magic` conditional upon the existence of `@a`, `@b`, and `@c` respectively.

**Comment by HerringtonDarkholme** [comment]
Thanks for submitting the issue! It is now tracked by #723.

**Comment by HerringtonDarkholme** [comment]
Let's track this on #723

**Comment by HerringtonDarkholme** [comment]
<img width="448" alt="image" src="https://github.com/ast-grep/ast-grep/assets/2883231/612daea1-f9bf-44b6-8e28-932f707f2edd">

```yaml
id: test
language: py
rule:
  kind: decorated_definition
  pattern: $DECO
  has:
    field: definition
    pattern: 'def func($$$ARGS): $$$BODY'
rewriters:
- id: merge_decorator
  language: py
  rule:
    pattern: $CALL($M)
    inside: { kind: decorator }
  fix: "$CALL=$M"
transform:
  MERGED:
    applyRewriters:
      source: $DECO
      rewrites: [merge_decorator]
      joinBy: ','
fix: |
  @magic($MERGED)
  def func($$$ARGS):
      $$$BODY

```
