### ISSUE TITLE
Find functions without return type

### ISSUE THREAD

**Issue by jack-michaud** [ast-grep/ast-grep#78]
Good afternoon, this is such an interesting project with huge potential! 

I want to write a rule which finds functions without a return type. For example, this code would trigger an error:

```ts
const foo = () => {
	return 1;
}

```

While this code would not:
```ts
const foo = (): int => {
	return 1;
}
```

The TS playground for the latter function looks like this:

![image](https://user-images.githubusercontent.com/13189762/198109477-2f4bc2c7-2ddd-4469-a290-9e2e7f4feea8.png)

My first thought was to make a rule which matches `arrow_function` (easy..) but when it comes time to find a _missing_ value, I hit a wall. 

Any suggestions or direction? This was my latest rule: 

```yml
id: empty-return-type
message: Must supply a return type to a function
severity: warning
language: TypeScript
rule:
  all:
    - not: # doesn't work - matches all ast nodes except a type annotation. 
        kind: type_annotation
    - inside:
        any:
          - kind: arrow_function
          # TODO Insert more function types here
```

Please take care and thank you for reading.
