### ISSUE TITLE
[bug] Ordering woes when matching siblings with varargs

### ISSUE THREAD

**Issue by HerringtonDarkholme** [ast-grep/ast-grep#813]
# Playground

https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6ImphdmFzY3JpcHQiLCJxdWVyeSI6InZhciAkQSA9ICRCIiwicmV3cml0ZSI6ImZmZmYiLCJjb25maWciOiJpZDogc2libGluZ1xubGFuZ3VhZ2U6IGphdmFzY3JpcHRcbnV0aWxzOlxuICB1dGlscGF0OlxuICAgIHBhdHRlcm46ICckQSgkJCRCKTsnXG5ydWxlOlxuICBtYXRjaGVzOiB1dGlscGF0XG4gIGZvbGxvd3M6XG4gICAgbWF0Y2hlczogdXRpbHBhdFxuICAgIHN0b3BCeTogZW5kIiwic291cmNlIjoiYSgpO1xuYSgxMjMpO1xuYSgpO1xuYSgxMjMpOyJ9

Related discussion  https://github.com/ast-grep/ast-grep/discussions/807
# Rule

```yml
id: sibling
language: javascript
utils:
  utilpat:
    pattern: '$A($$$B);'
rule:
  matches: utilpat
  follows:
    matches: utilpat
    stopBy: end
```

```js
a();
a(123);
a(); // should match
a(123); // should match
```

# Expect

The latter two function call statements should match.

# Actual

Nothing matches.

**Comment by HerringtonDarkholme** [comment]
This is caused by undefined matching order of rules.

Consider 

```yml
rule:
  matches: utilpat
  follows:
    matches: utilpat
    stopBy: end
```

is effectively

```yml
rule:
  all:
    - follows:
        matches: is-accessor
        stopBy: end
    - matches: is-accessor
```

The program will first match follows rule then matches rule. So there is no matching at all.
