### ISSUE TITLE
[bug] weird behavior with `any` multiple rules with `parenthesized_expression`

### ISSUE THREAD

**Issue by pionxzh** [ast-grep/ast-grep#839]
# ⏯ Playground Link

[Playground link with relevant code](https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6InR5cGVzY3JpcHQiLCJxdWVyeSI6InZvaWQgJE1BVENIIiwicmV3cml0ZSI6InVuZGVmaW5lZCIsImNvbmZpZyI6ImlkOiB2b2lkIG51bWJlclxubGFuZ3VhZ2U6IHR5cGVzY3JpcHRcbnJ1bGU6XG4gIGFueTpcbiAgLSBwYXR0ZXJuOiB2b2lkICROVU1CRVJcbiAgLSBwYXR0ZXJuOiB2b2lkKCROVU1CRVIpXG5jb25zdHJhaW50czpcbiAgTlVNQkVSOlxuICAgIGtpbmQ6IFwibnVtYmVyXCIiLCJzb3VyY2UiOiJ2b2lkIDBcbnZvaWQgOTlcbnZvaWQoMCkifQ==)

# 💻 Code

Code:

```js
void 0
void 99
void(0)
```

Pattern:

```yml
id: void number
language: typescript
rule:
  any:
  - pattern: void $NUMBER
  - pattern: void($NUMBER)
constraints:
  NUMBER:
    kind: "number"
```

# 🙁 Actual behavior

It only matched the first two lines.

![image](https://github.com/ast-grep/ast-grep/assets/9910706/6372bff7-ba9d-4165-9087-8c4152fe0dbb)

# 🙂 Expected behavior

`void(0)` should be matched as well

There is an interesting workaround. It will work normally by moving `void($NUMBER)` to the first rule...
