### ISSUE TITLE
[refactor] remove MetaVarMatcher

### ISSUE THREAD

**Issue by HerringtonDarkholme** [ast-grep/ast-grep#863]
# ⭐ Suggestion

We don't need another concept of MetaVarMatcher in `constraints`, a rule is pretty good fit.

# 💻 Use Cases

```yaml
rule:
  pattern: $A($B)
constraints:
  A:
    regex: get
    kind: method_call
```
