### ISSUE TITLE
[feature] simplify transformation and introduce `selector`

### ISSUE THREAD

**Issue by HerringtonDarkholme** [ast-grep/ast-grep#902]
# ⭐ Suggestion

Currently transformation and relational rules are pretty verbose.

For example:

transformation
```yaml
transformation:
  NEW:
    substring:
      source: $A
      startChar: 1
```

and 

```yaml
rule:
  kind: number
  inside:
    kind: arguments
    inside:
      kind: call_expression
```
We can refer to CSS syntax to simplify them.

# 💻 Use Cases
For relational rule, we can simplify using CSS selector syntax. https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_selectors

```yaml
rule:
  selector: call_expression > arguments > number
```
For transformation, we can refer to CSS function https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Functions

```yaml
transformation:
  NEW: substring($A, startChar=1)
```
