### ISSUE TITLE
[feature] ignore empty rules in rules.yaml - allow trailing rule separator

### ISSUE THREAD

**Issue by milahu** [ast-grep/ast-grep#942]
actual result with empty rule: error: missing field id

rules.yaml

```yaml
id: rule_1
language: Python
rule:
  pattern: 'aaa'
fix: 'bbb'

---

id: rule_2
language: Python
rule:
  pattern: 'ccc'
fix: 'ddd'

---
```

similar: [trailing commas](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Trailing_commas) in array declarations

allowing empty rules would be useful for generating rules.yaml in a for loop

<details>

```sh
#!/usr/bin/env bash

rules_yaml=""
rule_id=0

function r() {
  rules_yaml+=$(
    echo
    echo
    echo "id: rule_$rule_id"
    echo "language: javascript"
    echo "rule:"
    echo "  pattern: '$1'"
    echo "fix: '$2'"
    echo
    echo "---" # rule separator
  )
  rule_id=$((rule_id + 1))
}

r 'nt' sleep
r 'an' firebaseApiKey
r 'on' typesenseServer

# fix: error: missing field id
rules_yaml=${rules_yaml:0: -4}

# debug: print rules yaml
echo "rules_yaml:"; echo "$rules_yaml" | grep -n ''

ast-grep scan -U -r <(echo "$rules_yaml") src/patchme.js
```

</details>
