### ISSUE TITLE
[feature] rename all symbols between camelCase and snake_case

### ISSUE THREAD

**Issue by milahu** [ast-grep/ast-grep#945]
for python there is [camel-snake-pep8](https://github.com/abarker/camel-snake-pep8)
for javascript there is [eslint/camelcase](https://eslint.org/docs/latest/rules/camelcase) and [eslint/snakecase](https://github.com/ptkdev/eslint-plugin-snakecasejs)
for typescript there is [eslint/naming-convention](https://typescript-eslint.io/rules/naming-convention/)

some languages will require different casings for different types
for example PascalCase for class names

**Comment by milahu** [comment]
> [convert](https://ast-grep.github.io/reference/yaml/transformation.html#convert) can do that already

aah! also [Use transform in Rewrite](https://ast-grep.github.io/guide/rewrite-code.html#use-transform-in-rewrite). but the docs have no full example

i just cant get this working... this should rename `some_var` to `someVar`
ast-grep always shows the interactive screen, but it should just patch `input.py`

```sh
cat >input.py <<'EOF'
some_var = 1
print(some_var)
EOF

cat >rules.yaml <<'EOF'
id: fix-case
language: python
rule:
  pattern: $X
  kind: identifier
transform:
  X2:
    convert:
      toCase: camelCase
      source: $X
EOF

ast-grep scan -U -r rules.yaml input.py
```

**Comment by HerringtonDarkholme** [comment]
You also need a `fix` field to apply the fix.

```yaml
id: fix-case
language: python
rule:
  pattern: $X
  kind: identifier
transform:
  X2:
    convert:
      toCase: camelCase
      source: $X
fix: $X2
```
