### ISSUE TITLE
[bug] Rule file without 'message' property breaks LSP

### ISSUE THREAD

**Issue by StevenLove** [ast-grep/ast-grep#969]
A minimal rule file consisting of just an `id`, `language`, and `rule` should be supported. 
However, rules without `message` will break the LSP
```yml
id: no-console-rule
language: Javascript
rule:
  pattern: console.log($$$)
```

# 🙁 Actual behavior

`sg scan` works fine
LSP stops working. Doesn't log any errors even with changes in https://github.com/ast-grep/ast-grep/pull/968.

# 🙂 Expected behavior

LSP should continue publishing diagnostics and code actions when a rule file has a missing `message`
